- build/docker/ubuntu/Dockerfile
- configure.ac
- lib/Makefile.am
- lib/js/Gruntfile.js
- lib/js/Makefile.am
- lib/js/package.json
- lib/js/test/build.xml
Apparently the code is only available as part of entire repository download (125 MB).
https://code.google.com/archive/p/js-test-driver/source/default/source
Fortunately, the same set of tests were already ported to grunt so we can safely remove affected ant jobs.
> THRIFT-3825 Javascript test dependency is no longer available

- compiler/cpp/src/thrift/parse/t_function.h
- lib/c_glib/src/thrift/c_glib/protocol/thrift_multiplexed_protocol.c
- lib/c_glib/src/thrift/c_glib/protocol/thrift_protocol_decorator.c
- lib/c_glib/src/thrift/c_glib/transport/thrift_buffered_transport.c
- lib/c_glib/src/thrift/c_glib/transport/thrift_framed_transport.c
- lib/c_glib/src/thrift/c_glib/transport/thrift_memory_buffer.c
- lib/c_glib/test/testbinaryprotocol.c
- lib/c_glib/test/testbufferedtransport.c
- lib/c_glib/test/testcompactprotocol.c
- lib/c_glib/test/testdebugproto.c
- lib/c_glib/test/testfdtransport.c
- lib/c_glib/test/testframedtransport.c
- lib/c_glib/test/testmemorybuffer.c
- lib/c_glib/test/testoptionalrequired.c
- lib/c_glib/test/testsimpleserver.c
- lib/c_glib/test/teststruct.c
- lib/c_glib/test/testthrifttest.c
- lib/c_glib/test/testtransportsocket.c
- lib/c_glib/test/testtransportsslsocket.c
- lib/cpp/src/thrift/protocol/TJSONProtocol.cpp
- test/known_failures_Linux.json
1458947: memory leak in compiler
1458787: resource leak in c_glib led to discovery of assert() abuse
1459090: fix string.find result check in JSON processor (unlikely)
This closes #1404
> THRIFT-4376: fix a few high impact coverity defects:

- LANGUAGES.md
- build/docker/README.md
- build/docker/ubuntu-artful/Dockerfile
- lib/go/test/dontexportrwtest/compile_test.go
- lib/go/thrift/application_exception_test.go
- lib/go/thrift/compact_protocol.go
- lib/go/thrift/json_protocol_test.go
- lib/go/thrift/protocol_test.go
- lib/go/thrift/simple_json_protocol.go
- lib/go/thrift/simple_json_protocol_test.go
- test/go/src/common/clientserver_test.go
Opening this here because my free Travis account has its builds killed after 50 minutes.
> THRIFT-4516: Fix "go vet" warnings for Go 1.10

- lib/nodejs/lib/thrift/http_connection.js
`statusCode` on the line 173 is an undeclared variable. It crashes the node server.
> Fix undeclared statusCode variable

- lib/py/src/transport/THttpClient.py
Client: py
Timeout is already set in HttpClient. The reason for removal is issue
with gunicorn and gevent as described here
https://github.com/benoitc/gunicorn/pull/1616
Tested locally, works as expected
> THRIFT-4561: Remove python socket timeout

- contrib/zeromq/Makefile
- contrib/zeromq/TZmqServer.cpp
- contrib/zeromq/TZmqServer.h
- contrib/zeromq/test-client.cpp
- contrib/zeromq/test-client.py
- contrib/zeromq/test-receiver.cpp
- contrib/zeromq/test-sender.cpp
- contrib/zeromq/test-server.cpp
- contrib/zeromq/test-server.py
Some ZeroMQ symbols have changes in version 3.0 of ZeroMQ (before 2014). Current stable branch is 4.2. Additionally, the Python code used `newstyle` language option, which isn't supported in the Thrift compiler anymore. This style is the default now.
> Updated ZeroMQ examples to ZeroMQ version >= 3.0.

- lib/py/test/test_sslsocket.py
`test_ciphers` fails if system SSL doesn't support "DES-CBC3-SHA" which is quite old.
Adding an additional modern cipher fixes it.
Also fixes a bug where unit test execution hanged forever on SSL initialization failure.
> THRIFT-4577 Outdated cipher string in python unit test

- lib/cpp/CMakeLists.txt
- lib/cpp/Makefile.am
Updated CMake and automake files for C++.
> THRIFT-4578 Move `TAsyncProtocolProcessor` into main thrift library

- LANGUAGES.md
- build/docker/README.md
- build/docker/ubuntu-artful/Dockerfile
- lib/d/src/thrift/async/socket.d
- lib/d/src/thrift/server/transport/base.d
- lib/d/src/thrift/transport/file.d
- lib/d/src/thrift/transport/socket.d
- lib/d/test/client_pool_test.d
- lib/d/test/serialization_benchmark.d
This fixes build errors and deprecation warnings on dmd v2.080.0.
> THRIFT-4478 Thrift will not build with dlang 2.078 or later

- compiler/cpp/src/thrift/generate/t_js_generator.cc
- lib/nodejs/lib/thrift/buffered_transport.js
Tested locally using the following thrift IDL on thrift v0.10.0
```
struct Foo {
1: string name
}
service SocketTestService {
i16 countFoos(1: list<Foo> foos)
}
```
The following client request will fail on the client side, but leave data on the buffer:
```
client.countFoos([new thriftTypes.Foo(), null, new thriftTypes.Foo()]);
```
Using the new code, the client side error will be caught and the buffered transport will be reset, allowing for the socket to be used for a subsequent RPC call without causing a parse error on the server side
> THRIFT-4564: Reset buffered transport on serialization errors

- compiler/cpp/src/thrift/generate/t_js_generator.cc
The same testing that was done in #1558 applies to this fix as well. This just makes sure to delete the callback from the `reqs` registry so that they don't build up and cause a memory leak.
> THRIFT-4225: Delete callback if RPC send failed

- lib/js/src/thrift.js
THRIFT-4592: [JS] change readI32 to use Array.reverse/Array.pop vs Array.shift, which is expensive for big arrays in V8
https://issues.apache.org/jira/browse/THRIFT-4592
`readI32` ( https://github.com/apache/thrift/blob/master/lib/js/src/thrift.js#L1311-L1341 ) performance is extremely poor in Chrome when reading values from large arrays. This is due to the use of Array.shift ( https://github.com/apache/thrift/blob/master/lib/js/src/thrift.js#L1322 ) which seems to have performance issues in V8/Chrome.
As Chrome is a high market share browser I propose either changing this to use reverse/pop or detect the appropriate strategy given array length. I think this is due to how V8 handles large arrays and the heuristics used to determine whether data should be stored in a C-backed array or hash …
> THRIFT-4592: [JS] change readI32 to use Array.reverse/Array.pop vs Array.shift

- compiler/cpp/src/thrift/generate/t_cocoa_generator.cc
Cocoa generator generates NSString with copy instead of strong
> THRIFT-4586: Correctly generates NSString with copy instead of strong - Cocoa

- lib/lua/TFramedTransport.lua
THRIFT-4591: [cannot read call result via lua lib]
Client: [lua,  lib/lua]
> THRIFT-4591:cannot read call result via lua lib

- compiler/cpp/src/thrift/generate/t_js_generator.cc
- lib/nodejs/test/test_driver.js
Looks like this was cleaned up for normal JS oneway methods, but not nodejs. This also fixes another issue where promises returned by oneway methods would never resolve (since the callback was never called), so waiting on them would cause the client application to hang forever.
> THRIFT-3950: Memory leak while calling oneway methods

- lib/nodejs/lib/thrift/browser.js
When using the Node.js libs in the browser (via browser.js) Int64 isn't exposed the same way as it is in a Node environment. This just adds Int64 to the exports in browser.js to make consuming the libs more consistent with how we do in an actual Node environment.
> THRIFT-4604: NodeJS: adds Int64 to exports for browserify

- lib/cocoa/src/transport/TNSStreamTransport.m
This fixes a warning in Xcode/clang "Comparison of integers of different signs: 'int' and 'UInt32' (aka 'unsigned int')"
> Fix comparison of integers of different signs

- compiler/cpp/src/thrift/generate/t_java_generator.cc
THRIFT-4614: Generate `@Nullable` annotations for Java iterator getters
Client: Java compiler
This is a straightforward, compile-time-safe, backward-compatible change.
> THRIFT-4614: Generate missing @Nullable annotations for Java iterator getters

- compiler/cpp/src/thrift/generate/t_rs_generator.cc
Client: rs
If a thrift definition file contains multiple services, with functions
having the same name, there would be conflicting *Args and *Result
structs generated by the rust generator.
This commit adds prefixing of `*Args` and `*Result` structs with
the service name, to resolve any conflict.
e.g:
```thrift
service backend {
i32 send();
}
```
`SendArgs` -> `BackendSendArgs`
`SendResult` -> `BackendSendResult`
This change is technically non-backwards compatible (if any code decided to call their own structs `<ServiceName><FunctionName>{Args,Result}`, names would clash. However it seems quite unlikely.
> THRIFT-4617: Prepend service-specific struct names with service name

- compiler/cpp/src/thrift/generate/t_c_glib_generator.cc
With this change the C (GLib) compiler fully resolves the type of a list's elements before generating the C type for the list.
This fixes an issue where the compiler would output broken code for a list containing elements of a typedef'd type.
> THRIFT-4622: Resolve typedef'd list elements (C (GLib))

- lib/go/thrift/binary_protocol.go
- lib/go/thrift/compact_protocol.go
- lib/go/thrift/compact_protocol_test.go
- lib/go/thrift/protocol_test.go
Client: lib/go
Obtaining the remaining bytes isn't supported with some combinations of protocols and transports in the Go library. For example, the binary protocol doesn't work properly with the zlib transport which wraps the framed transport. In libraries for other languages checking is used for directly reading data from a buffer of an underlying transport. If data isn't enough we just read data from the underlying transport and never throw an error as in the Go library. Also, the buffer for the zlib transport is encapsulated in the Go zlib library and we can't access it to get the remaining bytes. So removing that checking is the most simple and convenient method to solve the problem.
> THRIFT-4626: Remove checking of remaining bytes in the Go library.

- compiler/cpp/src/thrift/generate/t_swift_generator.cc
- lib/swift/README.md
Some minor updates to the Swift code generator.
- Source files no longer capitalized (i.e. `index.thrift` now generates `index.swift` and not `Index.swift`, when namespaced it generates `index/index.swift` instead of `index/Index.swift`).  There was an inconsistency with how module names were capitalized which could cause issues when namespacing and using Swift modules.   This change _may_ be breaking for some use cases, but is otherwise resolved by changing the case of the module name where ever it is an issue.  (for most use cases, it shouldn't cause any issues, just a different named file)
- For cases when handling Errors, module name is appropriately prefixed to Error type name if the Error type name happens to be `Error` in order to disambiguate from Swift.Error.  This is a …
> Swift code generator minor updates

- compiler/cpp/src/thrift/generate/t_rb_generator.cc
- test/rb/generation/test_recursive.rb
Client: Ruby
re: https://issues.apache.org/jira/browse/THRIFT-4631
The goal of this PR is to alter the thrift ruby code generator so that in cases where we define structs that rely on recursion, it generates valid ruby.
The codegen include a `generate_forward_declaration` method which gets called before `generate_struct`. It allows us to eagerly declare ruby classes so that all classes are declared before any of the recursion within the classes executes. Without implementing something like this you get an `uninitialized constant` exception.
I've added tests to catch the original issue as well.
The delta caused by the this change is adding class declarations at the top of the generated files. Here's the delta alone. Full copies of the before / after below.
```
class RecTree; end
class …
```
> THRIFT-4631 Fix Ruby codegen to gen valid ruby for recursive structs

- .gitignore
- dub.json
- lib/d/src/thrift/server/base.d
- lib/d/src/thrift/server/nonblocking.d
This is in preparation to add thrift to the dub package manager for dlang.  This allows "dub build" and "dub test" to complete successfully when run from the top level directory.
This closes #723
> THRIFT-3458: add dub support for dlang

- lib/php/lib/Transport/TCurlClient.php
Tested and deployed on our production system. The change changes behavior for TCurlClient when non-200 response is received. However, other languages, such as Java and go do check for status code.
> THRIFT-4641: Check HTTP Status Code in TCurlClient

- lib/php/lib/Transport/TCurlClient.php
When curl_exec fails, more detailed failure information is available by calling curl_error.  Include this error information in the message in the thrown TTransportException.
Also change the comparison of the return value of curl_exec to explicitly check for boolean false, so as to distinguish from an empty response body (per the PHP documentation on this subject).
Changes have been tested and running in production at Thumbtack for the past several days, and it's working as expected.  TCurlClient doesn't seem to have any existing test suite to update.
> THRIFT-4645: TCurlClient: include failure reason in exception

- compiler/cpp/src/thrift/generate/t_dart_generator.cc
Tested locally, and is generating correctly.  The description of the issue being addressed is described in the JIRA ticket.
> THRIFT-4646: change dart generation of exception to exception

- lib/js/test/server_http.js
- lib/js/test/server_https.js
- lib/nodejs/lib/thrift/web_server.js
Updates the node.js fileserver to have a fixed based webroot which can
not be escaped by end users.
> Thrift-4647: Node.js Filesever webroot fixed path

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- lib/go/test/Makefile.am
- lib/go/test/RequiredFieldTest.thrift
- lib/go/test/tests/required_fields_test.go
Fixes THRIFT-4650 where required fields were incorrectly being marked as having been set even if they weren't.
Client: go
> THRIFT-4650: fixes incorrectly marking required fields as being set

- compiler/cpp/src/thrift/generate/t_perl_generator.cc
- lib/perl/lib/Thrift/BinaryProtocol.pm
- lib/perl/lib/Thrift/Exception.pm
- lib/perl/lib/Thrift/FramedTransport.pm
- lib/perl/lib/Thrift/HttpClient.pm
- lib/perl/lib/Thrift/MemoryBuffer.pm
- lib/perl/lib/Thrift/MultiplexedProcessor.pm
- lib/perl/lib/Thrift/MultiplexedProtocol.pm
- lib/perl/lib/Thrift/Protocol.pm
- lib/perl/lib/Thrift/SSLServerSocket.pm
- lib/perl/lib/Thrift/SSLSocket.pm
- lib/perl/lib/Thrift/Server.pm
- lib/perl/lib/Thrift/ServerSocket.pm
- lib/perl/lib/Thrift/Socket.pm
- lib/perl/lib/Thrift/Transport.pm
- lib/perl/lib/Thrift/UnixServerSocket.pm
- lib/perl/lib/Thrift/UnixSocket.pm
- test/perl/TestClient.pl
- test/perl/TestServer.pl
- tutorial/perl/PerlClient.pl
- tutorial/perl/PerlServer.pl
Using Indirect Object Syntax to instantiate objects is not recommended as per https://perldoc.perl.org/perlobj.html#Invoking-Class-Methods I have update the output to follow the recommended Class->new() syntax
See also https://github.com/apache/thrift/pull/1261
> THRIFT-4382: Replace the use of Indirect Object Syntax calls to new()

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- lib/go/README.md
- tutorial/go/Makefile.am
- tutorial/go/src/client.go
- tutorial/go/src/main.go
- tutorial/go/src/server.go
Github has been the canonical repo for a while now and I plan to merge this before 0.12 is tagged. I'm opening a PR to see if anyone has any feedback.
If you think this should be reverted or delayed, please say so.
> Replace git.apache.org imports with github.com

- compiler/cpp/src/thrift/generate/t_java_generator.cc
THRIFT-4657: Include `@javax.annotation.Generated` annotation for generated union classes
Client: Java compiler
This is a straightforward, compile-time-safe, backward-compatible change.
> THRIFT-4657: Include @javax.annotation.Generated annotation for unions

- compiler/cpp/src/thrift/generate/t_java_generator.cc
Follow up to THRIFT-4530 and THRIFT-4614.
In that patch, we neglected to add Nullable and Generated annotations to enums, in addition to classes. This PR fixes that.
Client: Java compiler
This is a straightforward, compile-time-safe, backward-compatible change.
> THRIFT-4660: Include @javax.annotation.Generated and Nullable as needed for enums

- compiler/cpp/src/thrift/generate/t_rs_generator.cc
- lib/rs/test/src/bin/kitchen_sink_server.rs
- lib/rs/test/thrifts/Base_Two.thrift
Client: rs
Small fix with test.
> THRIFT-4661: Rust enum name wrong case in generated structs

- CHANGES
- compiler/cpp/src/thrift/generate/t_rs_generator.cc
- lib/rs/README.md
- lib/rs/test/src/bin/kitchen_sink_server.rs
- lib/rs/test/thrifts/Midlayer.thrift
- lib/rs/test/thrifts/Ultimate.thrift
- test/rs/src/bin/test_client.rs
- test/rs/src/bin/test_server.rs
- tutorial/rs/src/bin/tutorial_client.rs
- tutorial/rs/src/bin/tutorial_server.rs
> THRIFT-4529: Rust enum variants are now camel-cased

- lib/rs/src/transport/mod.rs
- lib/rs/src/transport/socket.rs
Client: rs
Trivial change.  Add a `pub` method for users of the library.
> THRIFT-4664: Rust cannot create ReadHalf/WriteHalf

- compiler/cpp/src/thrift/generate/t_py_generator.cc
For a void method, there is no success value, so, it is an error to
attempt to assign one to the result object. This error is harmless
unless slots is also specified - with slots specified, the attempt to
assign to a non-existent field causes an error which makes the service
method fail.
Client: py
> THRIFT-4670: Twisted, slots, and void method fails with "object has no attribute 'success'"

- lib/py/src/transport/TSocket.py
The backlog parameter of socket.listen was hard coded, so I can't customize it in my code.
Adding `setBacklog`  to `TServerSocket` can resolve my problem.  :)
> THRIFT-4668: make socket backlog configurable for python

- lib/c_glib/src/thrift/c_glib/protocol/thrift_protocol.c
THRIFT-4671: handle client's unexpected close. Avoid the server work thread falling into dead loop.
Client: c_glib
> THRIFT-4671: handle client's unexpected close.

- lib/php/lib/Transport/TCurlClient.php
Infinite loop happens when response body is empty and HTTP status is
200. This patch fixes it.
* tested in production
> THRIFT-4656: Fix infinite loop in PHP TCurlClient

- lib/nodejs/lib/thrift/json_protocol.js
Changes are backwards compatible (as this line never did anything)
https://issues.apache.org/jira/browse/THRIFT-4679
> THRIFT-4679: Remove unused variable declaration

- compiler/cpp/CMakeLists.txt
This seems an obvious problem, don't know why it works with others. Maybe I do something wrong. 
I follow with the [README](https://github.com/apache/thrift/tree/master/compiler/cpp#build-using-cmake) to build the compiler using cmake, but failed with "Undefined symbols". It is because `compiler_core` sources is not append to `thrift-compiler_SOURCES`.
* cmake version: 3.12.3
* OS: mac os Mojave version 10.14
> Fix build compiler with cmake

- lib/cpp/src/thrift/transport/TSocketPool.cpp
random_shuffle is deprecated and removed in c++17
https://en.cppreference.com/w/cpp/algorithm/random_shuffle
> Fix build with c++17

- compiler/cpp/src/thrift/generate/t_csharp_generator.cc
THRIFT-4684: Fix WCF related C# code generation
Client: C#
Complete the namespace in System.ServiceModel in WCF related code.
Also when generating fields in fault classes, we follow the same behavior in normal struct,
to avoid generating unused private fields, when auto properties are also generated.
> THRIFT-4684: Fix WCF related C# code generation

- build/docker/ubuntu-bionic/Dockerfile
The upstream deimos repository for openssl support in dlang now has a tag supporting OpenSSL 1.1 so we can use that instead of a branch from jking's fork in our CI builds.
> THRIFT-4690: update bionic docker image to use upstream deimos OpenSSL 1.1 tag for dlang

- .gitignore
- build/docker/ubuntu-bionic/Dockerfile
- configure.ac
- lib/Makefile.am
- lib/swift/Makefile.am
- lib/swift/README.md
This is a prerequisite to writing and running swift clients and servers in the cross test.
> THRIFT-4547: add swift to bionic build image and run unit tests

- contrib/Vagrantfile
- contrib/thrift-maven-plugin/pom.xml
- contrib/vagrant/centos-6.5/Vagrantfile
- doc/install/README.md
- doc/install/debian.md
- doc/install/windows.md
- lib/java/gradle/codeQualityChecks.gradle
- lib/java/gradle/sourceConfiguration.gradle
Some places reference JDK 6, others JDK 7.  Upgrade all to JDK 8
> THRIFT-4694: Upgrade Java to Java 1.8

- lib/java/src/org/apache/thrift/transport/AutoExpandingBufferWriteTransport.java
- lib/java/src/org/apache/thrift/transport/TFastFramedTransport.java
- lib/java/src/org/apache/thrift/transport/TFramedTransport.java
- lib/java/test/org/apache/thrift/transport/TestAutoExpandingBufferWriteTransport.java
- lib/java/test/org/apache/thrift/transport/TestTFramedTransport.java
Code calls two writes to the underlying transport per flush: one for the frame size and one for the payload.  The result is that folks use TBufferedTransport on top of TFramedTransport to avoid getting two ethernet frames for small packets.  This means everything is double-buffered!
Based on THRIFT-1121 and THRIFT-959 this may have been an issue for a long time - the fix was easy however.  We make room for the frame size before writing to the buffer, then we only have to pull out the buffer, drop the frame size into the 4 bytes that we pre-allocated, and then write to the underlying transport once.
> THRIFT-4714: optimize java TFramedTransports to call write only once per flush

- lib/rb/Rakefile
Installing the ruby gem on systems without make fails in the build_ext task.
> Skip native extension build on jruby platforms

- lib/nodejs/lib/thrift/connection.js
I can't destroy the connection while the server is still alive, so do this modify.
When will this happen ?
I use consul to register and discover the servers, and save the clients in an array.
But I found sometimes the server is alive, but it's deregistered from consul, so I splice the  deregistered instance, and hope that the connection destroy auto.
If the server is really down, the connection destroy automatically, but the problem is, the server maybe still alive, so the connection never destroy. So the connection is leak, as it was splice out from the clients array, never accessible.
When server register again, new connection will be create, and put into clients array.
So I want to destroy the connection manually before splice it out. But find out I can't, as it will reconnect.
>  Fix: do not reconnect if connection.destroyed, prevent connection leak

- lib/js/Gruntfile.js
- lib/js/test/test-double-rendering.html
- lib/js/test/test-double-rendering.js
All the changes in this PR are backward compatible. 
See the related issue: https://issues.apache.org/jira/browse/THRIFT-4728
> THRIFT-4728: automate the double rendering test

- doc/ReleaseManagement.md
I haven't checked these against the ones on the web site already however this is the workflow I'd like to move towards.
> THRIFT-4697: Add release management docs to GitHub [ci skip]

- lib/js/src/thrift.js
THRIFT-4737: [added beforeSend to add customHeaders to jqXHR in jqRequest]
Client: [lib/js]
locally tested - custom headers where missing when using jq. So I added these lines to fix it.
Fix should be compatibel with 0.10.0, 0.11.0, 0.12.0 - but only tested with 0.11.0.
> THRIFT-4737: fixed - added beforeSend to add customHeaders to jqXHR in jqRequest

- lib/php/lib/Protocol/TProtocol.php
Client: php
TProtocol interface use phpdoc `@return` tags without corresponding imports. This cause some (minor) issues with IDEs and static analysis tools like phpstan.
> THRIFT-4751: Missing imports in TProtocol (phpdoc related only)

- build/veralign.sh
- lib/js/package-lock.json
- lib/js/package.json
- lib/ts/Makefile.am
- lib/ts/package-lock.json
- lib/ts/package.json
The direct dependency `grunt-shell-spawn` was updated to no longer need `sync-exec`.  Also fixed version and package meta for `lib/ts`.
> THRIFT-4757: fix npm identified security vulnerability in transient dependency on sync-exec

- compiler/cpp/src/thrift/generate/t_html_generator.cc
- package-lock.json
- package.json
- test/Makefile.am
Steps to reproduce:
- Create an simple thrift file like the following:
service MyService {}
- generate the HTML documentation for it via thrift -gen html MyService.thrift
The HTML compiler generates the following invalid stream:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
{{ "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">}}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link href="style.css" rel="stylesheet" type="text/css"/>
<title>Thrift module: test</title></head><body>
<div class="container-fluid">
<h1>Thrift module: test</h1>
<table class="table-bordered table-striped table-condensed"><thead><th>Module</th><th>Services</th><th>Data types</th><th>Constants</th></thead>
<tr> …
```
> THRIFT-4763: HTML compiler produces invalid HTML document

- .flake8
- CHANGES.md
- Makefile.am
- build/appveyor/CYGW-appveyor-install.bat
- build/docker/scripts/sca.sh
- compiler/cpp/src/thrift/generate/t_js_generator.cc
- doc/specs/SequenceNumbers.md
- lib/c_glib/src/thrift/c_glib/protocol/thrift_stored_message_protocol.c
- lib/cpp/src/thrift/TBase.h
- lib/cpp/src/thrift/Thrift.h
- lib/cpp/src/thrift/concurrency/Thread.h
- lib/cpp/src/thrift/protocol/TJSONProtocol.cpp
- lib/nodejs/examples/httpServer.py
- lib/py/src/ext/endian.h
- lib/py/src/protocol/TCompactProtocol.py
- test/cpp/src/TestClient.cpp
- test/crossrunner/run.py
- test/py/TestClient.py
- tutorial/php/runserver.py
- tutorial/py.twisted/PythonClient.py
- tutorial/py.twisted/PythonServer.py
The following tests were added:
- The cpp client for cross test now uses a sequence ID that starts at INT32_MAX - 10, and advances until it wraps around.
- The cpp client verifies the sequence ID that returns matches what was sent.
- The python client was changed to use pedantic sequence ID checking on all protocols.
The following errors were identified and fixed:
- In c_glib, thrift_stored_message_protocol was limiting the sequence ID to [0..G_INTMAX].  This was changed to allow any 32-bit value, matching other implementations.
- In cpp, JSON protocol, when the server read the header, it used a uint64_t for processing; this interacted with a bugfix from 2017 that dropped boost::lexical_cast and switched to std::stringstream, and this corrupted the negative sequence IDs.
- In python, …
> THRIFT-4405: identify and fix sequence id handling errors

- build/docker/ubuntu-bionic/Dockerfile
- debian/control
- lib/java/gradle.properties
- lib/java/gradle/environment.gradle
Otherwise it will fail with:
```
make[4]: Entering directory '/thrift/tutorial/cpp'
make[4]: Nothing to be done for 'install-exec-am'.
make[4]: Nothing to be done for 'install-data-am'.
make[4]: Leaving directory '/thrift/tutorial/cpp'
make[3]: Leaving directory '/thrift/tutorial/cpp'
make[2]: Leaving directory '/thrift/tutorial/cpp'
Making install in java
make[2]: Entering directory '/thrift/tutorial/java'
/usr/bin/ant  compile
Buildfile: /thrift/tutorial/java/build.xml
init:
[mkdir] Created dir: /thrift/tutorial/java/build
[mkdir] Created dir: /thrift/tutorial/java/build/log
generate:
compile:
[javac] Compiling 7 source files to /thrift/tutorial/java/build
[javac] /thrift/tutorial/java/gen-java/shared/SharedService.java:10: error: package javax.annotation does not exist
[javac] …
```
> THRIFT-4766: Fix JDK11 build

- lib/java/src/org/apache/thrift/transport/TSaslTransport.java
Client: java
The error for sasl negotiation failure dropped the root cause, which makes troubleshooting sometimes difficult.
The [Contributing Guide](https://github.com/apache/thrift/blob/master/CONTRIBUTING.md) has more details and tips for
committing properly.
Review the following checklist to ensure a smooth pull request experience.
</details>
</details>
- Add a note to the …
> THRIFT-4773: Provide root cause for sasl negotiation failure

- CMakeLists.txt
- build/cmake/DefinePlatformSpecifc.cmake
- build/cmake/FindClangTools.cmake
- build/cmake/StaticCodeAnalysis.cmake
- lib/c_glib/CMakeLists.txt
- lib/c_glib/src/thrift/c_glib/protocol/thrift_multiplexed_protocol.c
- lib/c_glib/src/thrift/c_glib/transport/thrift_ssl_socket.c
- test/c_glib/CMakeLists.txt
1.add -wall option for all major compilers.
2.add cmake support in test/c_glib
3.add static analysis targets
> THRIFT-4732:refine cmake scripts 

- lib/java/src/org/apache/thrift/TMultiplexedProcessor.java
- lib/py/src/TMultiplexedProcessor.py
fix exception type in TMultiplexedProcessor
</details>
</details>
</details>
- `No` for documentation-only changes
- `No` for trivial changes, …
> THRIFT-4779: fix exception type in TMultiplexedProcessor

- build/docker/ubuntu-bionic/Dockerfile
- build/docker/ubuntu-xenial/Dockerfile
- test/php/Makefile.am
- test/php/test_php.ini
- test/tests.json
The code was implemented in the test client but nothing was invoking it.
</details>
</details>
</details>
- `No` for documentation-only changes …
> THRIFT-4794: finish php json cross test

- lib/c_glib/src/thrift/c_glib/protocol/thrift_protocol.c
- lib/cpp/src/thrift/protocol/TProtocol.h
- lib/d/src/thrift/protocol/base.d
- lib/dart/lib/src/protocol/t_protocol_util.dart
- lib/go/thrift/protocol.go
- lib/javame/src/org/apache/thrift/protocol/TProtocolUtil.java
- lib/js/src/thrift.js
- lib/lua/TProtocol.lua
- lib/nodejs/lib/thrift/binary_protocol.js
- lib/nodejs/lib/thrift/compact_protocol.js
- lib/nodejs/lib/thrift/json_protocol.js
- lib/ocaml/src/Thrift.ml
- lib/py/src/protocol/TProtocol.py
- lib/rb/lib/thrift/protocol/base_protocol.rb
- lib/rb/spec/base_protocol_spec.rb
- lib/swift/Sources/TProtocol.swift
Modify protocol skip code to throw when encountering an unexpected type.
</details>
</details>
</details>
- `No` for documentation-only changes …
> THRIFT-4024, THRIFT-4783: throw when skipping invalid type

- compiler/cpp/src/thrift/generate/t_netstd_generator.cc
- compiler/cpp/src/thrift/generate/t_netstd_generator.h
Client: netstd
Removes the (already  disabled) "nullable" option from the netstd generator code
> THRIFT-4768 Remove "nullable" option from the code base (netstd ONLY)

- lib/php/src/ext/thrift_protocol/php_thrift_protocol.cpp
Client: php (extension)
When reference is passed to php extension, it's unreferenced (instead of
derefrenced). The next time one tries to use the same variable PHP
segaults. Even if not used again, php segfaults on
user_shutdown_function_call.
Tested by rerunning code in Jira THRIFT-4807 with the patch - passes
> THRIFT-4807: Fix php segfault on reference pass

- build/docker/ubuntu-bionic/Dockerfile
- build/docker/ubuntu-xenial/Dockerfile
Fix the build system errors in Xenial.  Minimum go version required to use some components we rely on is now 1.10.
> Fix xenial and bump go version on bionic

- compiler/cpp/src/thrift/generate/t_rs_generator.cc
- lib/rs/Cargo.toml
- lib/rs/src/errors.rs
- lib/rs/src/lib.rs
- lib/rs/src/protocol/binary.rs
- lib/rs/src/protocol/compact.rs
- lib/rs/src/protocol/mod.rs
- lib/rs/test/src/lib.rs
Submitting this as a draft PR to determine issues that should be created and which parts of PR should be merged.
TryFrom is now stable, so use that instead of try_from crate. Additionally re-export OrderedFloat since
it is used by the generated code. Relax dependencies to reduce downstream
conflicts.
> THRIFT-4536: TryFrom stable

- test/go/Makefile.am
- test/go/genmock.sh
The latest version (1.3.0) of golang/mock requires us to switch to Go modules for our tests, but that's not trivial given our directory structure.
Additionally, modules are still considered experimental and won't be finalized until at least Go 1.13, so we have some time to consider our options.
For now, this commit just fixes the CI issues by pinning the version.
> THRIFT-4855: Pin golang/mock to 1.2.0

- lib/js/package.json
Build failures occurred since jsdoc was updated to v3.6, since it requires Node 8.5 and we support Node 4.x on Xenial.  This fixes the js package.json file.
> Update and fix js dependencies

- doc/specs/idl.md
I think this is a violation of your Literal syntax.
Could you explain what i'm missing in the language definition?
Is this supposed to be a litteral '='?
Literal         ::=  ('"' [^"]* '"') | ("'" [^']* "'")
> Make Field definition follow Literal definition

- lib/java/src/org/apache/thrift/protocol/TField.java
- lib/java/test/org/apache/thrift/protocol/TestTField.java
Client: java
This change fixes a bug in which the `TField` class was broken with respect to the `Object` API requirements for `hashCode()` and `equals()` being consistent, as explained in [THRIFT-4857](https://issues.apache.org/jira/browse/THRIFT-4857).
As this class had no unit tests, and I'm not yet ready to install the entire build infrastructure on my Windows machine, I did not add any unit tests.
I have my own opinions about approaches to generating hash codes, as well comments about the approach to checking for class equivalence, but those issues are separate from the central hash code bug. As this is my first contribution, I therefore made my change as surgical as possible.
> THRIFT-4857: Made Java TField class hash code consistent with equals.

- lib/php/lib/Transport/TCurlClient.php
Client: php
CURLOPT_TIMEOUT requires a long [0], so it seems that small values
like 0.2 are being rounded to 0, resulting in a lack of any timeout.
This change uses CURLOPT_TIMEOUT_MS, which the PHP documentation
says was "added in cURL 7.16.2. Available since PHP 5.2.3."
[0] https://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT.html
> THRIFT-4845: Stop ignoring small timeouts

- lib/nodejs/lib/thrift/connection.js
This PR addresses an issue in the NodeJS module where data would be sent multiple times when the socket reconnects multiple times because the `offline_queue` would never be emptied.
This fix clears the `offline_queue` when the socket reconnects and the queued data is written. 
Fixes [THRIFT-3060](https://issues.apache.org/jira/browse/THRIFT-3060).
> THRIFT-3060: clear the offline queue when written

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- test/ThriftTest.thrift
See [THRIFT-4868](https://issues.apache.org/jira/browse/THRIFT-4868) for details. In short, Golang compilation is broken for optional sets with default values. For example:
`1: optional set<string> with_default = [ "test" ]`
> THRIFT-4868: Golang: Fix compilation for optional sets with default values

- lib/cpp/test/processor/EventLog.cpp
Recommended to catch exception by references.
> CPP generator test, catching exceptions by ref instead.

- build/appveyor/MING-appveyor-install.bat
Builds on mingw ran into a package dependency issue during installation (reproduced locally):
```
Jim@pulsar MINGW64 ~
$ pacman -Syu --noconfirm
:: Synchronizing package databases...
mingw32 is up to date
mingw64 is up to date
msys is up to date
:: Starting core system upgrade...
there is nothing to do
:: Starting full system upgrade...
:: Replace mingw-w64-x86_64-ncurses with mingw64/mingw-w64-x86_64-pdcurses? [Y/n]
:: Replace mingw-w64-x86_64-termcap with mingw64/mingw-w64-x86_64-pdcurses? [Y/n]
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing mingw-w64-x86_64-gcc (9.1.0-2) breaks dependency 'mingw-w64-x86_64-gcc=8.3.0-2' required by mingw-w64-x86_64-gcc-ada
:: installing …
```
> Fix mingw appveyor build issue [skip travis]

- lib/py/src/transport/TTransport.py
A small data type  mistake were observed during usage of SASL mechanism="PLAIN".
on 379-380 lines there're 2 calls of send_sasl_msg, where 1st uses sels.sasl.mechanism, which is of type str(), while 2nd uses self.sasl.process(), which generates bytes().
exception happens on line 402, where header generated on line 401 using pack() which returns type bytes() being concatenated with body provided to send_sasl_msg() func.
Since self.transport.write accepts bytes() only, it's better to use bytes everywhere...
on the line 420 we have similar error, where str().join() is being called, but both parameters passed to it are of type bytes(), which raises an exception.
> THRIFT-4892: fixed data type conflict with simoultaneus usage of bytes and str

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- lib/go/test/ConflictNamespaceServiceTest.thrift
- lib/go/test/ConflictNamespaceTestA.thrift
- lib/go/test/ConflictNamespaceTestB.thrift
- lib/go/test/ConflictNamespaceTestC.thrift
- lib/go/test/ConflictNamespaceTestD.thrift
- lib/go/test/ConflictNamespaceTestSuperThing.thrift
- lib/go/test/Makefile.am
See [THRIFT-4797](https://issues.apache.org/jira/browse/THRIFT-4797) for details. In short, Golang compilation fails when a Thrift file includes two files that have the same final namespace component (e.g. `namespace go packagea.common` and `namespace go packageb.common`)
Somewhat based on [fbthrift's implementation](https://github.com/facebook/fbthrift/commit/b6754fe7a6a6e00ce288f14cd4e88cfa3d0cc3e4#diff-803353e952116d4e88caab467a62f35b) though their implementation simply always adds an alias with a unique numerical prefix.
> THRIFT-4797: Golang: Fix import collisions

- tutorial/rs/README.md
upgrade to thrift 0.12.0
[THRIFT-4529] - Rust enum variants are now camel-cased instead of uppercased to conform to Rust naming conventions
> Fix rust tutorial following enum output change

- compiler/cpp/Makefile.am
- compiler/cpp/src/Makefile.am
- compiler/cpp/test/Makefile.am
- configure.ac
- lib/c_glib/Makefile.am
- lib/c_glib/test/Makefile.am
- lib/cpp/Makefile.am
- lib/cpp/test/Makefile.am
- lib/lua/Makefile.am
- test/c_glib/Makefile.am
- test/cpp/Makefile.am
- tutorial/c_glib/Makefile.am
- tutorial/cpp/Makefile.am
`configure.ac` uses `AC_CONFIG_HEADERS` for cpp and c_glib to generate config.h files. However automake by default will add the parent directory of the config.h files to the `DEFAULT_INCLUDES` variable, which appears to be used in all other projects. This leaks the include paths to other targets that probably don't want them. Currently, it's not an issue, but I am looking at adding Objective-C (Cocoa) tests, and these classes use the same Thrift library header file names as the C++ library, which come first in the include path. This ends up trying to compile C++ for Objective-C, which fails.
To fix this, we can turn on the `nostdinc` option, which disables the default include directories. This requires adding back the include directories to some targets.
I tested by compiling: …
> THRIFT-4896 - prevent cpp and c_glib include directories from leaking into other targets

- lib/c_glib/src/thrift/c_glib/transport/thrift_server_socket.c
- lib/c_glib/src/thrift/c_glib/transport/thrift_server_socket.h
- lib/c_glib/src/thrift/c_glib/transport/thrift_socket.c
- lib/c_glib/src/thrift/c_glib/transport/thrift_socket.h
- test/c_glib/src/test_client.c
- test/c_glib/src/test_server.c
- test/tests.json
ThriftSocket only supports connecting to a socket via a host and port, so this adds support for unix domain sockets for communication between local processes.
> THRIFT-4878 - [c_glib] add unix domain socket support to ThriftSocket

- lib/c_glib/src/thrift/c_glib/protocol/thrift_multiplexed_protocol.c
I've just release a string created in the constructor or previous call to set. 
It was not freed so it was leaked by previous commit.
The original issue is here: https://issues.apache.org/jira/browse/THRIFT-4842
> THRIFT-4842 - Fix memory leak on set property c_glib

- compiler/cpp/src/thrift/generate/t_cpp_generator.cc
- lib/cpp/test/EnumTest.cpp
ITNOA
Hi,
I add to_string helper function for enum in cpp, because it is increase usability and performance.
> THRIFT-4830: Add to_string helper function for cpp generator

- lib/cpp/src/thrift/transport/TFileTransport.cpp
There is one usage of `::write` in `TFileTransport.cpp`
> Use THRIFT_WRITE instead of ::write in TFileTransport.cpp

- tutorial/rs/README.md
The crate is named `ordered-float`, not `ordered_float`.
> Fix a typo in rust tutorial README.md. [skip ci]

- .travis.yml
- Thrift.podspec
- lib/swift/Sources/TBinaryProtocol.swift
- lib/swift/Sources/TCompactProtocol.swift
- lib/swift/Sources/TFramedTransport.swift
- lib/swift/Sources/TMap.swift
- lib/swift/Sources/TProtocol.swift
- lib/swift/Sources/TSSLSocketTransport.swift
- lib/swift/Sources/TSet.swift
- lib/swift/Sources/TSocketServer.swift
- lib/swift/Sources/TSocketTransport.swift
- lib/swift/Sources/TStreamTransport.swift
- lib/swift/Sources/TStruct.swift
This pull request:
- keeps compatibility with Swift 3
- adds support for Swift 4.0, 4.2, 5.0 and 5.1
- fixes the podspec:
- the pod name must match the filename in current versions of CocoaPods
- `requires_arc  = true` is already the default in CocoaPods
- `mutating func removeAtIndex` is removed because it wasn't implemented to begin with: it was just calling itself in an infinite loop.
> THRIFT-4902: Swift 4 and 5 compatibility

- lib/nodejs/lib/thrift/connection.js
To fix the defect I passed connect_timeout option or timeout option directly to net.createConnection.
This allows to use the nodeJs's internal mechanism for connection timeout handling.
> THRIFT-4844: createConnection ignores connect_timeout option

- lib/java/src/org/apache/thrift/server/TNonblockingServer.java
Do not ignore interrupted exceptions in TNonblockingServer.java
> THRIFT-4849: Do not Ignore InterruptedException

- lib/go/thrift/binary_protocol.go
Client: go
It seems the reader and writer in TBinaryProtocol is not necessary, because this class is serialize/deserialize the struct and write/read the data stream via trans, `reader` & `writer` here are duplicated with `trans` in this struct
- [Y ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [Y ] Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?  (not required for trivial changes)
- [Y ] Did you squash your changes to a single commit?  (not required, but preferred)
- [ Y] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [Y ] If your change does not involve any code, add ` [skip ci]` at the end …
> THRIFT-4908: remove reader&writer in Golang's TBinaryProtocol

- lib/go/thrift/pointerize.go
Added pointer helper functions for int8 and int16 types.
> Add pointer helpers for missing types

- lib/go/thrift/header_transport.go
- lib/go/thrift/header_transport_test.go
Client: go
Previously we did not check against that, so when people using
NewTSimpleServerN with both THeaderTransportFactory and
THeaderProtocolFactory, inside THeaderProtocolFactory we will actually
double wrap the transport with THeaderTransport. What make things worse
is that in that case, the transport still appear to work, because
THeaderTransport has backward compatible to TBinaryProtocol and
TCompactProtocol so the outer layer of THeaderTransport wrap (the one
directly accessible from the protocol) will only think that the client
does not support THeader, and fallback. So when double wrapping happens,
it will appear that everything works, except you cannot get the headers
from the protocol (because they are actually in the inner
THeaderTransport, not the outer one that's directly …
> THRIFT-4612: Avoid double wrapping THeaderTransport

- lib/go/thrift/header_context.go
- lib/go/thrift/header_context_test.go
- lib/go/thrift/header_protocol.go
- lib/go/thrift/header_transport_test.go
- lib/go/thrift/simple_server.go
Client: go
This is the first part of THRIFT-4914, which handles the server reading
part in the requests (client -> server direction).
In TSimpleServer implementation, when the protocol is THeaderProtocol,
auto add all the headers read into the context object before passing
that to processor, so the processor code can access them from the
context object directly, via the new helper functions added in
header_context.go file.
> THRIFT-4914: Add THeader to context object for server reads

- compiler/cpp/src/thrift/generate/t_d_generator.cc
Currently Thrift will generate members that are invalid because
they are D reserved words.  This change appends a '_' to member
names that are reserved words.
* binary search and more reserved names
* some refactoring
d keyword used in thrift files with get a underscore '_' postfix.
> THRIFT-4918: dlang name conflict

- compiler/cpp/src/thrift/generate/t_d_generator.cc
Initialisation of immutable data in static constructors has been deprecated.
They now need to be initialised in shared static constructors.
This trivial change brings the generator for D up to date with the latest
version of the compiler, but it should continue to work with older
versions.
> Fix deprecation for init immutable data in static constructors.

- lib/go/thrift/client.go
- lib/go/thrift/header_context.go
- lib/go/thrift/header_context_test.go
- lib/go/thrift/simple_server.go
Client: go
This is the second part of THRIFT-4914, which handles the client writing
part in the requests (client -> server direction).
In TStandardClient, when the context has write headers set, and the
protocol is THeaderProtocol, automatically extract all headers from the
context object and set to THeaderProtocol to send over the wire.
Client code can set headers into the context object by using the helper
functions in header_context.go.
Note that we have separated keys for read and write header key list, so
that for code that's both a server and a client (example: a server that
calls other upstream thrift servers), they don't automatically forward
all headers to their upstream servers, and need to explicitly set which
headers to forward.
In order to make auto forwarding easier, also …
> THRIFT-4914: Send context THeaders for client writes

- doc/install/README.md
- doc/install/debian.md
Starting with version 0.12.0, the lib/java build method has been changed to Gradle.
so I changed the error description in the documentation.
Thanks.
best regards.
> THRIFT-4933 Java build mode is incorrect in doc/install

- compiler/cpp/src/thrift/generate/t_java_generator.cc
- lib/java/gradle/generateTestThrift.gradle
- test/JavaBinaryDefault.thrift
- test/JavaTypes.thrift
- test/Makefile.am
When a binary field has a default value the value is treated as a String. However you cannot set a string to a bytebuffer so this fails to compile.
- [x ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
> THRIFT-4932: Using a default string on a binary field results in invalid Java code.

- build/docker/README.md
I tried to run tests locally following the instructions in `build/docker/README.md`, but the following command failed:
```
thrift$ dockerrun ubuntu-bionic
```
It requires a preceding repository name, specified as `$DOCKER_REPO` in the previous command:
```
thrift$ DOCKER_REPO=thrift/thrift-build DISTRO=ubuntu-bionic build/docker/refresh.sh
```
No, because it's a trivial change just for the documentation.
> Fix wrong command examples in build/docker/README.md [skip ci]

- tutorial/perl/PerlServer.pl
This PR fixes Perl tutorial server failure by adding a missing use statement.
> THRIFT-4965: Perl tutorial server doesn't work due to the lack of use statement

- compiler/cpp/src/thrift/generate/t_py_generator.cc
Currently, the thrift compiler generates regular string literals for
string constants marked as `binary`.  This makes the resulting type
inconsistent under Python 3.
> THRIFT-4920: Fix generation of binary string constants

- test/php/Makefile.am
Client: PHP
`make check` in test/php tests some options such as `:inlined` and `:classmap`, but the latter is not specified mistakenly. This PR fixes it.
> THRIFT-4969: PHP test doesn't check the code generation with php:classmap

- tutorial/nodejs/NodeServer.js
Client: nodejs
This PR fixes tutorial/nodejs/NodeServer.js not to fail when receiving an invocation for the zip function.
> THRIFT-4967: Node.js tutorial server fails if the zip function invoked

- lib/java/src/org/apache/thrift/transport/TFileTransport.java
> THRIFT-4945 Log output mode is not standardized

- lib/java/src/org/apache/thrift/transport/TIOStreamTransport.java
When the peer closes the socket, currently TIOStreamTransport throws an TTransportException without message, this is sometimes confusing.
> THRIFT-4858: Provide a meaningful error message

- test/AnnotationTest.thrift
- test/SmallTest.thrift
clean up unsupported senum base type from 0.9.1
> THRIFT-4951 clean up unsupported senum base type from 0.9.1

- CHANGES.md
- lib/java/src/org/apache/thrift/transport/TIOStreamTransport.java
isOpen always returning true (even after close is called) should be considered as anti-pattern behavior.
> THRIFT-2530: Fix TIOStreamTransport#isOpen

- lib/cpp/src/thrift/transport/TSSLSocket.cpp
- lib/cpp/src/thrift/transport/TSSLSocket.h
- lib/cpp/test/CMakeLists.txt
- lib/cpp/test/Makefile.am
- lib/cpp/test/SecurityFromBufferTest.cpp
Added new methods to lib/cpp/src/thrift/transport/TSSLSocket.* that allow to load OpenSSL certificates from a `const char*` memory buffer. We have tested the methods on Linux CentOS 7.4, Ubuntu 16.04 and 18.04, macOS 10.13, and Windows VS2015 and VS2017.
> Added new methods to load OpenSSL certificates from memory buffer

- lib/go/thrift/debug_protocol.go
- lib/go/thrift/logger.go
- lib/go/thrift/simple_server.go
- lib/go/thrift/zlib_transport.go
Client: go
As discussed in https://issues.apache.org/jira/browse/THRIFT-4985:
1. Remove logging in TZlibTransport
2. Add a new Logger type to help users to better control logging in this
library
3. Use the new Logger type in TSimpleServer and TDebugProtocol
4. Remove panic recovery from TSimpleServer
> THRIFT-4985: Cleanup logging in go library

- lib/lua/TCompactProtocol.lua
when TCompactProtocol write a struct, the self.lastFieldIndex + 1 first,  then store the self.lastFieldId;
but when write end, the self.lastFieldId is taken after  self.lastFieldIndex - 1. so it may result some field has a wrong index!
> thrift lua TcompactProtocol bug fix

- lib/go/test/tests/thrifttest_driver.go
- lib/go/thrift/simple_server.go
Client: go
This is a different approach to take THRIFT-4984: Instead of checking
EOF errors in place, handle them in a consolidated, deferred function.
Also improve test error messages.
> THRIFT-4984: Ignore EOF errors in TSimpleServer, take 2

- lib/go/thrift/simple_server.go
Client: go
TCompactProtocol (which is used by THeaderTransport to read headers)
could wrap the underlying error with TProtocolException, which breaks
err == io.EOF test in some cases.
> THRIFT-4984: Handle wrapped io.EOF errors

- lib/go/thrift/response_helper.go
- lib/go/thrift/response_helper_test.go
- lib/go/thrift/simple_server.go
Client: go
This is the third part of THRIFT-4914, which handles the server writing
part in the response (server -> client direction).
Define a new type, TResponseHelper, which only contains THeader related
functions for now, but can be extended for other functions in the
future.
In TSimpleServer, inject a TResponseHelper into the context object
passed into the handler functions. Handler function code could retrieve
the injected TResponseHelper to set headers to be written to the client.
> THRIFT-4914: Add TResponseHelper

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- lib/go/test/Makefile.am
- lib/go/test/ServicesTest.thrift
See [THRIFT-5002](https://issues.apache.org/jira/browse/THRIFT-5002) for more details.
Currently the remote.go client fails to compile when services extend other services and the parent service has a function that needs a container for its arguments.
> THRIFT-5002: Golang: Fix for argument containers for inherited functions

- lib/go/thrift/header_protocol.go
Clients: go
This is the fourth and final part of THRIFT-4914, which handles the
client reading part in the response (server -> client direction).
> THRIFT-4914: Add GetResponseHeadersFromClient helper function

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- lib/go/test/DuplicateImportsTest.thrift
- lib/go/test/Makefile.am
- lib/go/test/common/a.thrift
- lib/go/test/common/b.thrift
If a thrift file includes two files from the same namespace into a
separate file, the generated Go code has duplicate imports for that
namespace. This fixes that.
Client: go
> THRIFT-5019: Duplicate imports from multiple includes from a namespace

- CHANGES.md
- lib/java/src/org/apache/thrift/transport/TIOStreamTransport.java
- lib/java/test/org/apache/thrift/transport/TestTIOStreamTransport.java
Fix for  TIOStreamTransport.isOpen
[THRIFT-5022](https://issues.apache.org/jira/browse/THRIFT-5022)
> THRIFT-5022: Fix TIOStreamTransport.isOpen for input or output only use

- compiler/cpp/src/thrift/generate/t_py_generator.cc
- lib/py/src/Thrift.py
- lib/py/src/protocol/TBase.py
- lib/py/src/protocol/TProtocol.py
- test/DebugProtoTest.thrift
- test/py.tornado/test_suite.py
- test/py.twisted/test_suite.py
- test/py/TestFrozen.py
Currently, the generated exception classes are not hashable under Python 3
because of the generated `__eq__` method.  Exception objects are generally
expected to be hashable by the Python standard library. Post-construction
mutation of an exception object seems like a very unlikely case, so enable
hashing for all exceptions by making them immutable by default.  This also
adds a way to opt-out of immutability by setting the `python.immutable`
annotation to `"false"`.
> THRIFT-4002: Make generated exception classes immutable by default

- lib/js/package.json
The latest published `thrift` version (0.13.0):
* does not contain `index.js` at the package root
* has no "main" entry point in package.json.
So module request throws an exception:
```javascript
require('thrift')
Thrown:
Error: Cannot find module 'thrift'
Require stack:
- <repl>
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
at Function.Module._load (internal/modules/cjs/loader.js:527:27)
```
This PR adds missed "main" field to `package.json`.
> THRIFT-5029: Fix Node.js lib entry point

- lib/java/src/org/apache/thrift/server/TThreadPoolServer.java
- lib/java/test/org/apache/thrift/server/TestThreadPoolServer.java
In TThreadPoolServer, threads are blocking in io with open sockets,
as long as clients don't close the connection, server threads are
never stopped even after a shutdown is called on server (because
they are blocked waiting for io).
To be able to stop all server threads properly, server should
proactively close sockets once a shutdown is initiated.
> THRIFT-4252: Close sockets when shut down server

- lib/cpp/src/thrift/transport/TBufferTransports.cpp
This fixes a MSVC warning seen in the logs:
> C:\projects\thrift\lib\cpp\src\thrift\transport\TBufferTransports.cpp(375): warning C4244: 'argument': conversion from 'uint64_t' to 'std::size_t', possible loss of data [C:\projects\build\MSVC2015\x86\lib\cpp\thrift.vcxproj]
> Fix casting uint64_t to size_t

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- lib/go/test/GoTagTest.thrift
- lib/go/test/tests/gotag_test.go
Custom go.tag in an IDL no longer removes the existing "db" and "json"
tags but can override them.
This allows us to change default tags in the future without affecting
user defined ones.
Client: go
> THRIFT-5046: Better struct tag overrides

- compiler/cpp/src/thrift/generate/t_java_generator.cc
Instead, use Boolean#compare to compare the raw values instead of having to call Boolean.ValueOf first in Java compiler.
> THRIFT-5014: Do Direct Comparison on Raw Values Instead of Objects

- lib/rs/src/server/threaded.rs
- lib/rs/src/transport/socket.rs
Right now addresses must be a ```&str``` and must match format ```host:port```. However, there are no obstacles for replacing ```&str``` with types bound by ```ToSocketAddrs``` trait.
> THRIFT-4995 Use `ToSocketAddrs` for expressing network addresses

- build/docker/scripts/autotools.sh
Modify docker build scripts used in CI test environments in order to put
in place a Maven .m2/settings.xml configuration file that overrides the
repository with the id 'central' with an equivalent "mirror" that uses
https instead of http.
> THRIFT-5068: Force secure Maven Central in Travis CI

- CHANGES.md
- lib/go/thrift/deserializer.go
- lib/go/thrift/serializer.go
- lib/go/thrift/serializer_test.go
Client: go
This change improves performance when using TDeserializer with a
resource pool. See https://issues.apache.org/jira/browse/THRIFT-5069 for
more context.
Also add TSerializerPool and TDeserializerPool, which are thread-safe
versions of TSerializer and TDeserializer. Benchmark result shows that
they are both faster and use less memory than the plain version:
$ go test -bench Serializer -benchmem
goos: darwin
goarch: amd64
BenchmarkSerializer/baseline-8            577558              1930 ns/op             512 B/op          6 allocs/op
BenchmarkSerializer/plain-8               452712              2638 ns/op            2976 B/op         16 allocs/op
BenchmarkSerializer/pool-8                591698              2032 ns/op             512 B/op          6 allocs/op
PASS
> THRIFT-5069: Make TDeserializer resource pool friendly

- lib/js/package.json
I discovered this repo because Synk had flagged one of our dependencies as having a security vulnerability. That vulnerability is a ReDos attack that resides in the `marked` module that is part of `jsdoc`. From what I can tell all the modules listed as `dependencies` are not required at runtime and can be made `devDependencies`. This also happens to fix the security issue.
I cannot find any explicit reference to these modules in the build artifact. The builds pass and everything appears to be fine when I run the tests in Docker. So, from what I can tell this change should have zero noticeable impact on consumers of Thrift.
> Non-Required JS Dependencies

- compiler/cpp/src/thrift/generate/t_rs_generator.cc
Client: rs
Reapply the changes in https://github.com/apache/thrift/pull/1726 given that the Rust version has been updated.
> THRIFT-4764: Use new syntax for clippy skipping

- lib/go/thrift/header_context.go
- lib/go/thrift/header_context_test.go
Client: go
We already have SetHeader and GetHeader helper functions in the go
library to deal with THeader injected into the context object. But we
didn't provide a way to unset/delete a key from the context object.
This will be useful with the TSimpleServer.SetForwardHeaders API. In the
scenario that a thrift server want to auto forward certain headers to
other upstream thrift servers as the fallback, but during the handling
of the request might decide to remove some of the auto forward headers.
This is also achievable through mutate the write header list, but since
that's a list, finding one key from the list and remove it is much more
hassle.
> Add UnsetHeader to go library

- lib/js/test/build.xml
- lib/json/test/build.xml
Client: JavaScript, JSON
`make check` in the lib/js or lib/json directory fails because maven-ant-tasks tries to download jar files using HTTP, that is not allowed to access. This PR fixes it to use HTTPS instead.
> THRIFT-5171: Fix maven-ant-tasks to use HTTPS instead of HTTP

- lib/go/thrift/header_transport.go
- lib/go/thrift/header_transport_test.go
Client: go
Trying to read the next frame will likely cause the Read call blocking
indefinitely and eventually lead to timeout. See the JIRA ticket for
more context.
> THRIFT-5183: Don't try to read next frame in THeaderTransport.Read

- lib/cpp/src/thrift/transport/TPipeServer.cpp
- lib/cpp/src/thrift/transport/TPipeServer.h
- lib/cpp/src/thrift/transport/TServerSocket.cpp
- lib/cpp/src/thrift/transport/TServerSocket.h
- lib/cpp/src/thrift/transport/TServerTransport.h
- lib/cpp/test/TServerSocketTest.cpp
- lib/cpp/test/TSocketInterruptTest.cpp
This PR adds a new method isOpen() to the TServerTransport and implementations TServerSocket and TPipeServer. I've added tests for TServerSocket and tested on a number of platforms. The change is rather small so I did not create a Jira ticket.
> Added isOpen() to TServerTransport

- appveyor.yml
- test/cpp/CMakeLists.txt
This PR disables StressTestNonBlocking on Windows, not just in AppVeyor but generally. This is required because the test is flaky.
> THRIFT-4282: Disabled StressTestNonBlocking on Windows

- lib/cpp/src/thrift/TOutput.cpp
This change has mostly an impact on Windows. Currently Thrift does not resolve error strings on Windows (for me). A typical error message may look like `Could not bind: errno = 10049`. With C++11 the newer formatting method `strerror_s()` is available on MSVC, however it fails to resolve many error messages. The most complete error handling on MSVC is possible only via Windows methods.
This PR adds support for decoding error codes on MSVC via `FormatMessageA()` into an ASCII string. In effect, above error id `10049` can be decoded as `Could not bind: The requested address is not valid in its context`.
Furthermore, on platforms that do not have `strerror_r` available (non-Posix systems), this PR turns to `strerror_s` from C++11 to decode the message.
> TOutput: Add further parsers for errno-to-string conversion

- .travis.yml
- compiler/cpp/src/thrift/generate/t_swift_generator.cc
- lib/swift/Sources/TApplicationError.swift
- lib/swift/Sources/TClient.swift
- lib/swift/Sources/TCompactProtocol.swift
- lib/swift/Sources/TEnum.swift
- lib/swift/Sources/TFileTransport.swift
- lib/swift/Sources/TList.swift
- lib/swift/Sources/TMap.swift
- lib/swift/Sources/TSerializable.swift
- lib/swift/Sources/TSet.swift
- lib/swift/Sources/TSocketServer.swift
- lib/swift/Sources/TSocketTransport.swift
- lib/swift/Sources/TStreamTransport.swift
- lib/swift/Sources/TStruct.swift
Xcode 11.3 (Swift 5.1) generates deprecation warnings for:
* Hashable protocol conformance using new Hasher type
* Use of `withUnsafeBytes`
`TAsyncResult<T>` is also redundant with the advent of `Result<T, Error>` in the stdlib.
This PR addresses all of the above and removes old versions of Swift from the CI job.
> THRIFT-5155: Swift 5.1 support

- lib/js/src/thrift.js
- lib/nodejs/lib/thrift/browser.js
- lib/nodejs/lib/thrift/header_protocol.js
- lib/nodejs/lib/thrift/header_transport.js
- lib/nodejs/lib/thrift/http_connection.js
- lib/nodejs/lib/thrift/index.js
- lib/nodejs/lib/thrift/input_buffer_underrun_error.js
- lib/nodejs/lib/thrift/thrift.js
The Thrift implementations for NodeJS and Javascript seem to have come from the same origins, and the code shares a strong resemblance. However it seems the implementations have deviated over time. The differences I could identify in this PR are mostly harmless minor syntax differences. I've also identified a number of issues where exports have been inconsistent. So the overall user experience and the maintainability should be significantly improved by this PR.
This PR contains a second, related commit. The property `Error.captureStackTrace` exists only in Node and can not be used in the browser implementation (via webpack or browserify). Therefore it must be qualified with existence checks. This is a trivial change that should not do any harm.
But in any case, it may be good if someone …
> Rework the consistency between NodeJS and Javascript

- compiler/cpp/test/CMakeLists.txt
- compiler/cpp/test/Makefile.am
- compiler/cpp/test/bincat.sh
This is a minor PR that removes the (now deprecated) boost dependency from the tests of Thrift compiler, and removes the (unused) script `bincat.sh`. I'm curious if the CI finds any problems...
> Removed boost from compiler test, and deleted unused bincat.sh

- lib/cpp/src/thrift/transport/TZlibTransport.cpp
- lib/cpp/src/thrift/transport/TZlibTransport.h
- test/cpp/src/TestServer.cpp
This PR adds wrapping to the TZlibTransportFactory. This is very helpful so that servers can create their "normal" transport factory like before, then wrap it into a TZlibTransportFactory.
This makes the server code very consistent with the client code. It has also been a frequent request, and the lack of this wrapping was explicitly commented in `TestClient.cpp`.
I've used the wrapped TZlibTransportFactory with a large number of transports and protocols on multiple platforms successfully. Also, a similar wrapper was added recently for Go in https://issues.apache.org/jira/browse/THRIFT-4346.
> Allow wrapping TTransportFactory into a TZlibTransportFactory

- lib/swift/Sources/TSet.swift
- lib/swift/Sources/TSocketServer.swift
When compiling with swift 5.2 (Xcode 11.4):
- (OS X and Linux) type 'TSet<Element>' does not conform to protocol 'Collection'
- (Linux only) kCFSocketCloseOnInvalidate has Int type
- [x ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
> THRIFT-5150: Fix compilation with Swift 5.2

- lib/d/src/thrift/transport/websocket.d
When establishing a WebSocket connection, Firefox sends Connection: keep-alive, Upgrade instead of just Connection: Upgrade. Check to see if Upgrade is in the header instead of checking to see if it is the entire header value.
> THRIFT-5184: Fix Connection header check for Firefox when establishing a WebSocket connection.

- CHANGES.md
- lib/go/thrift/common_test.go
- lib/go/thrift/example_middleware_test.go
- lib/go/thrift/middleware.go
- lib/go/thrift/middleware_test.go
- lib/go/thrift/multiplexed_protocol.go
- lib/go/thrift/multiplexed_protocol_test.go
- lib/go/thrift/processor_factory.go
Client: go
This PR adds a simple middleware framework for Go servers.
It provides:
1. A `ProcessorMiddleware` function interface used to define the actual middleware
2. `WrapProcessor`, the function that you use to wrap a `TProcessor` in a list of middleware
3. A helper `WrappedTProcessorFunction` struct to help with developing middleware.
This is may be breaking change for any custom implementations of the `TProcessor` interface, but should not effect the code generated by compiling Thrift files.  It adds two functions to the interface that are a part of the generated `TProcessor` code, but were not defined in the interface explicitly.
> THRIFT-5164: add middleware framework for Go servers

- compiler/cpp/src/thrift/generate/t_cpp_generator.cc
- test/Makefile.am
- test/SpecificNameTest.thrift
- test/cpp/CMakeLists.txt
- test/cpp/Makefile.am
- test/cpp/src/SpecificNameTest.cpp
> THRIFT-5179:  Thrift compiler will generate wrong code if IDL struct's name is 'a' or 'b'

- lib/go/thrift/example_client_middleware_test.go
- lib/go/thrift/example_processor_middleware_test.go
- lib/go/thrift/middleware.go
- lib/go/thrift/middleware_test.go
This commit adds a simple middleware framework for Go clients.
It provides:
* A `ClientMiddleware` function interface used to define the actual middleware
* `WrapClient`, the function that you use to wrap a `TClient` in a list of middleware
* A helper `WrappedTClient` struct to help with developing middleware
> THRIFT-5164: Add middleware framework for Go clients

- CHANGES.md
- lib/go/thrift/example_client_middleware_test.go
- lib/go/thrift/example_processor_middleware_test.go
Client: go
Godoc requires at least one other exported type/function to render the
whole example file in the example, so export
simpleProcessorLoggingMiddleware to make the example of
ProcessorMiddleware more helpful.
Currently it's rendered in a not very helpful way:
https://pkg.go.dev/github.com/apache/thrift@v0.13.1-0.20200430141240-5cffef964a08/lib/go/thrift?tab=doc#example-ProcessorMiddleware
Compare to the client middleware example rendering:
https://pkg.go.dev/github.com/apache/thrift@v0.13.1-0.20200430141240-5cffef964a08/lib/go/thrift?tab=doc#example-ClientMiddleware
While I'm here, also update CHANGES.md to mention ClientMiddleware.
[skip ci]
> THRIFT-5164: Small cleanup on the example code

- CHANGES.md
- LANGUAGES.md
- build/docker/ubuntu-xenial/Dockerfile
This PR updates NodeJS on Ubuntu Xenial to 10.x. This is because NodeJS 6.x that was previously used does not support newer node modules. Also, since January 2020, NodeJS 8.x is EOL. Therefore 10.x is the currently oldest, supported NodeJS version.
The Dockerfile was tested locally so the docker build should work. Also, NodeJS is the currently successfully employed version on other thrift docker builds.
This PR fixes the issue https://travis-ci.org/apache/thrift/jobs/654070652 that is now solved in https://travis-ci.org/apache/thrift/jobs/654644828, so please review and merge. However note that the build still does not fully succeed with a later error about a required Ruby update. This second issue is very likely unrelated to this PR.
> THRIFT-5116: Update NodeJS to supported version on Ubuntu Xenial

- lib/go/thrift/transport_exception.go
- lib/go/thrift/transport_exception_test.go
Client: go
Go 1.13 introduced a new, optional, hidden interface for error
implementations to make them unwrappable [1]. We currently already kind
of support that (via TTransportException.Err), so just add a new
function to make it Go 1.13+ compatible.
I know thrift go library itself hasn't dropped support for pre-go1.13
yet, but this enables users already on go1.13 to do error inspections
more easily.
I didn't implement it for PrependError, because git grep shows that it's
currently only used by test code.
[1] https://pkg.go.dev/errors@go1.13?tab=doc#pkg-overview
> Make TTransportException unwrappable on go1.13+

- lib/go/thrift/socket.go
- lib/go/thrift/socket_conn.go
- lib/go/thrift/socket_conn_test.go
- lib/go/thrift/socket_unix_conn.go
- lib/go/thrift/socket_unix_conn_test.go
- lib/go/thrift/socket_windows_conn.go
- lib/go/thrift/ssl_socket.go
Client: go
Implement connectivity check on go's TSocket and TSSLSocket for
non-Windows systems.
The implementation is inspired by
https://github.blog/2020-05-20-three-bugs-in-the-go-mysql-driver//
> THRIFT-5214: Connectivity check on go's TSocket

- lib/go/thrift/header_transport.go
Client: go
In THeaderTransport implementation, use io.CopyN instead of
io.Copy+io.LimitReader.
Underlying io.CopyN is actually implemented with io.Copy+io.LimitReader
[0], but it also does some extra checks we can take advantage of. It
also simplifies the code in thrift repo.
[0] https://github.com/golang/go/blob/83b181c68bf332ac7948f145f33d128377a09c42/src/io/io.go#L340
> Use io.CopyN to simplify THeaderTransport code

- lib/go/thrift/socket.go
- lib/go/thrift/socket_conn.go
- lib/go/thrift/socket_unix_conn.go
- lib/go/thrift/ssl_socket.go
Client: go
We added socketConn to go library for connectivity check in
https://github.com/apache/thrift/pull/2153, but forgot to push read
deadline on the socket when doing the connectivity checks. This caused
the issue of large number of connectivity checks to fail with I/O
timeout errors.
> THRIFT-5214: Push read deadline in socketConn

- lib/go/thrift/socket.go
- lib/go/thrift/socket_conn.go
- lib/go/thrift/socket_unix_conn.go
- lib/go/thrift/ssl_socket.go
Client: go
This is a slightly different, and less error-prone approach from the
fix in e382275.
The previous approach relies on passing the set socket timeout into the
underlying socketConn from TSocket and TSSLSocket. But since we have so
many different constructors for TSocket and TSSLSocket, some makes the
initial connection in the constructor and some does not, there are so
many different places we would need to remember to pass socketTimeout
into socketConn. In the future, when we add another constructor to them,
we could either forget to pass the socket timeout into socketConn, or
try to pass it while we haven't constructed socketConn yet (which will
cause panic), both are bad.
In this approach we just clear the read deadline in the connectivity
check read. Because that's a …
> THRIFT-5214: Reset read deadline in socketConn

- CHANGES.md
- lib/go/thrift/socket.go
- lib/go/thrift/ssl_socket.go
Client: go
We separated timeout in go's TSocket into connect timeout and socket
timeout in 81334cd, this change does the same for TSSLSocket to keep
them consistent.
Also rename the arg in NewTSocketFromConnTimeout from connTimeout to
socketTimeout, because in that function we already have a connection,
so connect timeout is never used again. The timeout passed into that
function is really for socket timeout, not connect timeout. The name of
that function actually means "New TSocket From Conn (with) Timeout", not
"New TSocket From ConnTimeout" (I guess that's where the original
confusion came from).
Also add the missing change note for the breaking change.
> THRIFT-5152: Separate timeout in TSSLSocket

- CHANGES.md
- compiler/cpp/src/thrift/generate/t_go_generator.cc
- lib/go/README.md
- lib/go/thrift/simple_server.go
Client: go
In compiler generated TProcessorFunction implementations, add a
goroutine after read the request to do connectivity check on the input
transport. If the transport is no longer open, cancel the context object
passed into the handler implementation.
Also define ErrAbandonRequest error, to help TSimpleServer closing
client connections that's already closed on the other end.
> THRIFT-5240: Do connectivity check in Go server

- lib/go/thrift/header_transport.go
- lib/go/thrift/header_transport_test.go
Client: go
In the current implementation, we only call endOfFrame when we hit EOF
when reading from the frameReader. The problem is in go stdlib the Read
call finished reading the remaining data from frameReader will not
return EOF, the next Read will. This caused us in most cases only call
endOfFrame at the beginning of the next frame, which could cause
troubles because we didn't read the beginning of the frame properly.
> THRIFT-5257: Fix Go THeaderTransport endOfFrame handling

- lib/go/thrift/socket_conn.go
- lib/go/thrift/socket_unix_conn.go
- lib/go/thrift/socket_unix_conn_test.go
Client: go
In previous implementation of socket connectivity check, we try to read
1 byte and put it into buffer when succeeded. The buffer complicates
the implementation of Read function. Change to use syscall.Recvfrom with
MSG_PEEK flag instead so that the buffer is no longer needed.
> THRIFT-5214: Use peek to implement socket connectivity check

- lib/py/Makefile.am
- lib/py/src/transport/TSocket.py
- lib/py/test/test_socket.py
Client: py
This is inspired by changes to the Go library (THRIFT-5214) and, by proxy, [this blog post][1]. The idea is that if the other end of the socket has closed their end of the connection, we can figure that out by doing a non-blocking read on our socket before we waste time serializing and sending a message just to find out the socket is closed when we try to read the response.
I've done some [benchmarking](https://gist.github.com/spladug/91483032d410714e1d416467a476a1ad) on the addition and found it performs reasonably: costing about 2 microseconds per `isOpen()` call.
I've tested on Python 2.7, 3.7, and 3.8 on Linux. I've tested on Python 3.8 on Windows.
We have been running this in production at reddit for several high-throughput services for several days. There was no …
> THRIFT-5248: Python: Make TSocket.isOpen check if server still connected

- lib/cpp/CMakeLists.txt
- lib/cpp/Makefile.am
- lib/cpp/src/thrift/transport/SocketCommon.cpp
- lib/cpp/src/thrift/transport/SocketCommon.h
- lib/cpp/src/thrift/transport/TNonblockingServerSocket.cpp
- lib/cpp/src/thrift/transport/TServerSocket.cpp
- lib/cpp/src/thrift/transport/TSocket.cpp
For the abstract unix socket address type, the string in the
'sun_path' field of the 'sockaddr_un struct', is a not null-terminated
string (see unix(7)).
Fix the lentgh calculation of the 'sun_path' field to don't add
the termination null byte.
> Fix abstract unix socket name

- lib/go/thrift/header_protocol.go
- lib/go/thrift/header_protocol_test.go
- lib/go/thrift/header_transport.go
- lib/go/thrift/header_transport_test.go
Client: go
In Go library code, allow setting the underlying protoID to a
non-default (TCompactProtocol) one for THeaderTransport/THeaderProtocol.
> THRIFT-5278: Allow set protoID in go THeader transport/protocol

- lib/go/thrift/http_transport.go
b67cad4 introduced transparent gzip support for the HTTP transport but
calling gzip.NewWriter() with every request causes a large number of
memory allocations [1] and can create GC pressure.
Avoid this issue by using a sync.Pool for gzip writers.
[1] https://old.reddit.com/r/golang/comments/9uejp4/usage_of_syncpool_for_gzipwriter_in_http_handlers/e94jh8c/
> go: Use sync.Pool for gzip in HTTP transport

- lib/go/README.md
- lib/go/thrift/simple_server.go
Client: go
This is a follow up to 4db7a0af13ac9614e3e9758d42b2791040f4dc7e.
Because of the Go runtime bug [1], the previous default value of 1ms is
not a great default as it could cause excessive cpu usage. Use 5ms
instead as a balance between being useful and not causing too much cpu
overhead.
It's still configurable.
[1]: https://github.com/golang/go/issues/27707
> THRIFT-5240: Tweak the default go server connectivity check interval

- lib/go/thrift/compact_protocol.go
- lib/go/thrift/json_protocol.go
- lib/go/thrift/json_protocol_test.go
- lib/go/thrift/protocol_test.go
- lib/go/thrift/simple_json_protocol.go
- lib/go/thrift/simple_json_protocol_test.go
Client: go
In go library's TSimpleJSONProtocol and TJSONProtocol implementations,
we use slices as stacks for context info, but didn't do proper boundary
check when peeking/popping, result in it might panic with using -1 as
slice index in certain cases of calling Write*End without matching
Write*Begin before.
Refactor the code to properly implement the stack, and return a
TProtocolException instead on those cases.
Also add unit tests for all protocols. The unit tests shown that
TCompactProtocol.[Read|Write]StructEnd would also panic with unmatched
Begin calls, so fix them as well.
> THRIFT-5294: Fix panic in go TSimpleJSONProtocol

- lib/go/thrift/debug_protocol.go
This also comes from the discussion of
https://github.com/apache/thrift/pull/1992#issuecomment-705903922.
I think TDebugProtocol is a better fit for this feature than creating a
new TProtocol implementation.
The DuplicateTo field is not added to TDebugProtocolFactory because I
don't think it makes sense from the factory setup. In vast majority
cases users would need direct access to the underlying TMemoryBuffer to
make it useful, which is easier this way than an additional
TTransportFactory plus TProtocolFactory to make TDebugProtocolFactory
way too complicated.
> Add DuplicateTo protocol to go's TDebugProtocol

- lib/java/gradle/sourceConfiguration.gradle
This adds an Automatic-Module-Name entry to the Thrift jar manifest
in order to provide Thrift with a stable module name when used in a
JPMS modular context. The name chosen here is "org.apache.thrift",
which matches the symbolic name used for OSGi.
See: http://branchandbound.net/blog/java/2017/12/automatic-module-name/
> Add an Automatic-Module-Name entry

- .gitignore
- LANGUAGES.md
- compiler/cpp/src/thrift/generate/t_rs_generator.cc
- lib/rs/Cargo.toml
- lib/rs/README.md
- lib/rs/src/errors.rs
- lib/rs/src/lib.rs
- lib/rs/src/protocol/binary.rs
- lib/rs/src/protocol/compact.rs
- lib/rs/src/protocol/mod.rs
- lib/rs/src/protocol/multiplexed.rs
- lib/rs/src/protocol/stored.rs
- lib/rs/src/server/multiplexed.rs
- lib/rs/src/server/threaded.rs
- lib/rs/src/transport/buffered.rs
- lib/rs/src/transport/mem.rs
- lib/rs/test/Cargo.toml
- lib/rs/test/src/bin/kitchen_sink_client.rs
- lib/rs/test/src/bin/kitchen_sink_server.rs
- lib/rs/test/src/lib.rs
- test/rs/Cargo.toml
- test/rs/src/bin/test_client.rs
- test/rs/src/bin/test_server.rs
- test/rs/src/lib.rs
- tutorial/rs/Cargo.toml
- tutorial/rs/README.md
- tutorial/rs/src/bin/tutorial_client.rs
- tutorial/rs/src/bin/tutorial_server.rs
Client: rs
* Update all `clippy`/`rustfmt` attributes to use new syntax
* Use new numeric literal syntax
* Use shorthand syntax for initializing structs
* Use elided lifetimes for `Formatter`
* Remove `extern crate`
* Update all `Cargo.toml` files (except `lib/rs`) to remove direct references to `ordered-float` crate (use Thrift redefinition)
* Update all `Cargo.toml` files (except `lib/rs`) to use updated, and a consistent set of crates
* Remove unnecessary `()` return and `else` branch when writing fields
* Use `_f64` suffix for float literals during const initialization
* Take ownership of `self` when writing a Thrift enum (represented by a Rust enum with integers) to an output protocol
* Use shorthand syntax for initializing structs
**NOTE**: This does _not_ fix any bugs. It simply …
> THRIFT-5306: Rust code and generated code no longer has clippy warnings (Rust 1.40)

- tutorial/cl/Makefile.am
- tutorial/cl/ensure-externals.sh
There is a symbolic link in the repository to point to a shell script. I'm under the impression that a relative path in the corresponding `Makefile.am` serves the same purpose. Lets see if the CI agrees.
> Removed symbolic link tutorial/cl/ensure-externals.sh

- lib/go/thrift/http_client.go
- lib/go/thrift/http_client_test.go
Client: go
THttpClient did not reset it's internal buffer when http client returned
an error, leaving the whole or partially read message in the buffer.
Now we reset the buffer in defer.
Details: https://issues.apache.org/jira/browse/THRIFT-5324
> THRIFT-5324: reset http client buffer after flush

- build/cmake/DefineOptions.cmake
Currently the logic of the `CMAKE_DEPENDENT_OPTION` for `BUILD_SHARED_LIBS` does not work correctly. For this setting in particular, its better to use a standard cmake option, and set the default corresponding to the individual platforms (Windows OFF, other platforms ON).
> build/cmake/DefineOptions.cmake: Fixed the logic of BUILD_SHARED_LIBS

- lib/go/thrift/binary_protocol.go
- lib/go/thrift/binary_protocol_test.go
- lib/go/thrift/compact_protocol.go
Client: go
In TBinaryProtocol.ReadString, TBinaryProtocol.ReadBinary,
TCompactProtocol.ReadString, and TCompactProtocol.ReadBinary, use
safeReadBytes to prevent from large allocation on malformed sizes.
$ go test -bench=SafeReadBytes -benchmem
goos: linux
goarch: amd64
BenchmarkSafeReadBytes/normal-12                 2664687               424 ns/op            2176 B/op          5 allocs/op
BenchmarkSafeReadBytes/max-size-12                462532              2494 ns/op           14464 B/op          7 allocs/op
PASS
ok      _/home/fishy/work/thrift/lib/go/thrift  2.901s
> THRIFT-5322: Guard against large string/binary lengths in Go

- lib/py/src/protocol/THeaderProtocol.py
- lib/py/src/transport/THeaderTransport.py
Client: Py
This allows clients to choose which subprotocol (TBinary/TCompact) to frame with headers. The server will already accept either protocol and reply correctly.
> THRIFT-5331: Py: make THeader subprotocol configurable

- CHANGES.md
- lib/go/thrift/binary_protocol.go
- lib/go/thrift/buffered_transport.go
- lib/go/thrift/compact_protocol.go
- lib/go/thrift/configuration.go
- lib/go/thrift/configuration_test.go
- lib/go/thrift/debug_protocol.go
- lib/go/thrift/framed_transport.go
- lib/go/thrift/header_protocol.go
- lib/go/thrift/header_protocol_test.go
- lib/go/thrift/header_transport.go
- lib/go/thrift/header_transport_test.go
- lib/go/thrift/iostream_transport.go
- lib/go/thrift/json_protocol.go
- lib/go/thrift/simple_json_protocol.go
- lib/go/thrift/socket.go
- lib/go/thrift/ssl_socket.go
- lib/go/thrift/zlib_transport.go
Client: go
Define TConfiguration following the spec, and also move the following
configurations scattered around different TTransport/TProtocol into it:
- connect and socket timeouts for TSocket and TSSLSocket
- tls config for TSSLSocket
- max frame size for TFramedTransport
- strict read and strict write for TBinaryProtocol
- proto id for THeaderTransport
Also add TConfiguration support for the following and their factories:
- THeaderTransport and THeaderProtocol
- TBinaryProtocol
- TCompactProtocol
- TFramedTransport
- TSocket
- TSSLSocket
Also define TConfigurationSetter interface for easier TConfiguration
propagation between wrapped TTransports/TProtocols , and add
implementations to the following for propagation
(they don't use anything from TConfiguration themselves):
- …
> THRIFT-5322: Implement TConfiguration in Go library

- lib/go/thrift/exception.go
- lib/go/thrift/protocol_exception.go
- lib/go/thrift/transport_exception.go
Client: go
As a follow up to https://github.com/apache/thrift/pull/2298, make the
error returned by PrependError unwrap-able in certain cases.
> THRIFT-5326: Make PrependError more unwrap-able

- LANGUAGES.md
- build/docker/README.md
- build/docker/ubuntu-bionic/Dockerfile
- build/docker/ubuntu-disco/Dockerfile
- build/docker/ubuntu-xenial/Dockerfile
- lib/go/test/tests/client_error_test.go
- lib/go/thrift/exception.go
- lib/go/thrift/go.mod
- lib/go/thrift/header_protocol.go
- lib/go/thrift/header_transport.go
- lib/go/thrift/http_client.go
- lib/go/thrift/protocol_exception.go
- lib/go/thrift/rich_transport.go
- lib/go/thrift/simple_server.go
- lib/go/thrift/socket_unix_conn.go
- lib/go/thrift/transport_exception.go
- lib/go/thrift/transport_exception_test.go
Client: go
- Update Dockerfiles used by travis
- Add go.mod file
- Modify error handling code to take advantage of errors package updates
in go1.13
> THRIFT-5338: Raise minimal supported go version to 1.14.14

- lib/go/thrift/go.mod
Client: go
Having it under a subdirectory has some unexpected consequences, so
remove it for now. Another PR will be open up later to add it back to
the root directory.
> THRIFT-5338: Remove lib/go/thrift/go.mod

- lib/go/thrift/header_transport.go
- lib/go/thrift/header_transport_test.go
Client: go
This fixes a bug introduced in
https://github.com/apache/thrift/pull/2296, that we mixed the preferred
proto id and the detected proto id, which was a bad idea.
This change separates them, so when we propagate TConfiguration, we only
change the preferred one, which will only be used for new connections,
and leave the detected one from existing connections untouched.
> THRIFT-5322: THeaderTransport protocol id fix

- CHANGES.md
- compiler/cpp/src/thrift/generate/t_go_generator.cc
- lib/go/thrift/client.go
- lib/go/thrift/example_client_middleware_test.go
- lib/go/thrift/header_protocol.go
- lib/go/thrift/middleware.go
- lib/go/thrift/middleware_test.go
Client: go
Make a breaking change so that TClient.Call returns the response
meta, currently only contains headers but could be expanded in the
future, and make a compiler change to compiler generated clients to take
advantage of that and provide access to response metadata to users.
> THRIFT-4914: Make TClient.Call to return the response meta

- lib/java/CMakeLists.txt
- lib/js/CMakeLists.txt
When building components that use an external build tool (like Java gradle or Javascript grunt), cmake does currently not track if a rebuild is required. This PR creates a cmake-dependency between the sources and the target of these components "Java" and "Javascript". Assuming that all sources are fully contained in their respective component folder, cmake can infer if a require is required (i.e. the target is missing or one or more sources are more current). This drastically reduces build times.
However please be aware that if the dependency between sources and target should *not* be complete for some reason, then cmake may miss to rebuild a component. I could not observe this problem but it may be well advised to carefully check this PR.
> CMake: Added better dependency tracking for external build tools

- lib/cpp/Makefile.am
- lib/cpp/src/thrift/TNonCopyable.h
- lib/cpp/src/thrift/concurrency/Monitor.h
- lib/cpp/src/thrift/concurrency/Mutex.h
- lib/cpp/src/thrift/transport/TPipe.cpp
- lib/cpp/src/thrift/transport/TPipe.h
- lib/cpp/src/thrift/transport/TPipeServer.cpp
- lib/cpp/src/thrift/windows/OverlappedSubmissionThread.cpp
- lib/cpp/src/thrift/windows/OverlappedSubmissionThread.h
- lib/cpp/src/thrift/windows/Sync.h
- lib/cpp/src/thrift/windows/TWinsockSingleton.h
There is currently a thrift dependency on `boost/noncopyable.hpp`, but the design pattern of non-copyable base class is very small (only ~15 lines of code, including namespaces). To reduce the boost dependency (as discussed before), this PR adds a non-copyable base class pattern in its own header `thrift/TNonCopyable.h`.
> Added TNonCopyable.h in favor of boost dependency

- lib/py/src/Thrift.py
- test/DebugProtoTest.thrift
- test/py/TestFrozen.py
Client: py
When no fields are present, we don't get the special constructor that
uses `__setattr__` to avoid these checks. So the default constructor sets
message normally and triggers the anti-mutation tripwires.
Before:
```console
$ thrift --version
Thrift version 0.14.0
$ pip freeze | grep thrift
thrift==0.14.0
$ cat test.thrift
exception LookMaNoFields {}
$ thrift -out . -gen py test.thrift
$ python
>>> from test.ttypes import LookMaNoFields
>>> LookMaNoFields()
Traceback (most recent call last):
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/src/thrift/lib/py/thrift/Thrift.py", line 93, in __init__
super(TException, self).__setattr__("message", message)
File "/src/example/test/ttypes.py", line 23, in __setattr__
raise TypeError("can't modify immutable …
```
> THRIFT-5352: Fix construction of Py exceptions with no fields

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- test/ThriftTest.thrift
Client: go
This fixes the bug reported in
https://github.com/apache/thrift/pull/2315#discussion_r577919697.
> THRIFT-4914: Fix name redeclaration bug in compiled go code

- compiler/cpp/src/thrift/generate/t_go_generator.cc
Client: go
When a thrift file includes 2 or more other thrift files, and those
included thrift files do not have explicit go namespaces defined, the
current import dedup logic would wrongly use their empty namespace and
skip the second one, while the real import namespace should be inferred
from the filename.
> THRIFT-5353: Fix import dedup without explicit go namespace

- lib/rs/src/protocol/compact.rs
> THRIFT-5299: Encode sequence numbers as non-zigzag varint

- lib/go/test/ConflictArgNamesTest.thrift
- lib/go/test/EqualsTest.thrift
- lib/go/test/Makefile.am
- lib/go/test/tests/conflict_arg_names_test.go
- lib/go/test/tests/equals_test.go
- test/ThriftTest.thrift
Client: go
Also add missing copyright header for files added in
https://github.com/apache/thrift/pull/2307.
> Move ConflictingNamesTest to lib/go/test

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- lib/go/test/ConflictArgNamesTest.thrift
- lib/go/test/EqualsTest.thrift
- lib/go/test/Makefile.am
- lib/go/test/tests/conflict_arg_names_test.go
- lib/go/test/tests/equals_test.go
- lib/py/src/Thrift.py
- test/DebugProtoTest.thrift
- test/ThriftTest.thrift
- test/py/TestFrozen.py
Cherry pick the following PRs into 0.14.0 branch:
- https://github.com/apache/thrift/pull/2330
- https://github.com/apache/thrift/pull/2332
- https://github.com/apache/thrift/pull/2334
- https://github.com/apache/thrift/pull/2335
> Cherry picks for 0.14.0 branch

- compiler/cpp/src/thrift/generate/t_rs_generator.cc
> THRIFT-5363 Render all-caps constants correctly in Rust generated code

- CHANGES.md
- lib/go/thrift/binary_protocol.go
- lib/go/thrift/compact_protocol.go
- lib/go/thrift/json_protocol.go
- lib/go/thrift/simple_json_protocol.go
Client: go
~Also remove size arg from make() calls in compiler.~
> THRIFT-5369: Use MaxMessageSize to check container sizes

- CHANGES.md
- build/docker/ubuntu-bionic/Dockerfile
- build/docker/ubuntu-disco/Dockerfile
- build/docker/ubuntu-xenial/Dockerfile
- lib/go/thrift/socket.go
- lib/go/thrift/ssl_socket.go
- lib/go/thrift/transport_exception.go
Client: go
Currently we only treat TTransportException with typeId == TIMED_OUT as
timeout (return true in Timeout function). When opening a new socket, if
we got a connect timeout from net.Dial, we wrap the error as
TTransportException with typeId == NOT_OPEN, thus it's no longer treated
as a timeout error.
Change the error to be directly wrapping the original error (instead of
recreate a new error with the same error message), and change
tTransportException.Exception to also return true if the wrapped error
is a timeout error. This way we don't have to break anything (if code
rely on TTransportException.TypeId being NOT_OPEN in this case, that's
still true).
While I'm here, also update CHANGES.md from #2359.
> THRIFT-5404: Allow other types of TTransportException to be timeouts

- lib/c_glib/test/CMakeLists.txt
- lib/cpp/test/CMakeLists.txt
This PR adds a trivial cleanup of two cmake files. It contains mostly whitespace changes to fix indenting and syntax in cmake. It also removes some unused boost dependencies.
> Minor cleanup of two CMake files, and removed (unused) boost deps

- lib/cpp/src/thrift/transport/TSSLSocket.cpp
- lib/cpp/test/SecurityTest.cpp
The PR adds a slight improvement with respect to calling `free()` in case of error. There are two cases where the current implementation does not call `free()` on the buffer in case of error. These cases are addressed here.
> Robustness improvements when loading OpenSSL certificates

- build/docker/ubuntu-bionic/Dockerfile
- build/docker/ubuntu-disco/Dockerfile
- build/docker/ubuntu-xenial/Dockerfile
- lib/cpp/src/thrift/TToString.h
- lib/cpp/test/JSONProtoTest.cpp
- lib/cpp/test/ToStringTest.cpp
Add unit test for system locale with thousands separator comma
Install en_US.UTF-8 locale in Dockerfile
The global locale affects integer formatting. Some LC_NUMERIC locales specify a thousands separator "," which would break integer formatting. Add a unit test that sets the global locale to "en_US.UTF-8" (which uses a comma thousands separator). Fix the integer formatting by imbue'ing the "C" locale in ostringstream.
> THRIFT-3840: C++ TJSONProtocol still using locale dependent formatting

- lib/java/src/org/apache/thrift/meta_data/FieldMetaData.java
- lib/javame/src/org/apache/thrift/meta_data/FieldMetaData.java
Details of the deadlock are in the ticket.
This PR addresses the deadlock by limiting the scope of the locks
acquired in FieldMetaData.java to only protect calls to the structMap
hashtable. No locks should be held when the call to sClass.newInstance()
is in progress.
Tested: Regular CI builds should pass.
The synchronized locks for the Java SE and Java ME versions are scoped to just the behavior needed to be locked. 
- [yes] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [yes] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [yes] Did you squash your changes to a single commit?  (not required, but preferred)
- [yes] Did you do your best to avoid …
> THRIFT-5430: Fix deadlock triggered by FieldMetaData.class.

- lib/rs/Cargo.toml
I'm the author of integer-encoding; since it was used for the first time in thrift, new major versions have been released. The use by thrift is unaffected by this: the thrift crate compiles and runs tests fine. I recommend upgrading, as the current version is more likely to see attention in case of bug fixes (which, despite the crate being simple, have unfortunately occasionally needed to take place). At the same time, unbounded versions (like `>=1.1.4`) are not good for long-term stability, in case the API will change in a major version.
> Rust: Upgrade dependency integer-encoding to 3.0

- lib/py/src/transport/TTransport.py
Client: python
isOpen return None,  which is equivalent to False,  fix it to be consistent with other transport
> fix isOpen return None, to be consistent with other transport

- compiler/cpp/src/thrift/generate/t_rs_generator.cc
The methods `write_container_end` should be call after the for loop, not within it.
Currently this does not affect anything, because these methods are no-ops for all the implemented protocols. But it may cause an error when more protocols are implemented.
By the way, could anyone please release version 0.14.0, 0.14.1, and 0.14.2 to crates.io?
> Small bug in Rust generated code for writing container types

- lib/go/README.md
Because we briefly had go.mod file under lib/go/thrift in e27e82c46b
(it was later removed in d9fcdd3dba), using
go get github.com/apache/thrift/lib/go/thrift/...
(as suggested by the current README) will get that particular version
instead of the latest released version. So update README to use
go get github.com/apache/thrift
instead.
Also instead of saying we support Go 1.7+, say we support the officially
supported Go releases, as that's our new support policy.
> Update README for go library

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- lib/go/test/ConstOptionalField.thrift
- lib/go/test/ConstOptionalFieldImport.thrift
- lib/go/test/Makefile.am
- lib/go/test/tests/const_optional_field_test.go
Client: go
The current compiler will generate uncompilable code when we use
optional enum and/or typedef'd types in a thrift constant.
This fixes the issue, also adds a test for that.
> THRIFT-5389: Fix const generation for optional fields

- compiler/cpp/src/thrift/generate/t_netstd_generator.cc
- compiler/cpp/src/thrift/generate/t_netstd_generator.h
- lib/netstd/Tests/Thrift.PublicInterfaces.Compile.Tests/name_conflicts.thrift
> THRIFT-5445 "cancellationToken" cannot be used as argument name

- CHANGES.md
- compiler/cpp/src/thrift/generate/t_go_generator.cc
- lib/go/test/ConflictNamespaceTestE.thrift
- lib/go/test/ConflictNamespaceTestF.thrift
- lib/go/test/Makefile.am
- lib/go/test/tests/conflict_namespace_test.go
This change improves two problems in go code imports:
1. Always rename import the thrift package into "thrift", as we allow
the user to use a different library to replace the official one from
the compiler command line, this makes sure that in compiler generated
go code we can always blindly use "thrift.*".
2. We added auto rename import dedup in d9019fc5a4, but in that change
for system packages we always use the full import path as the dedup
identifier, so system package "database/sql/driver" would not be
detected as a conflict against a thrift go namespace of
"foo.bar.driver". Use the part after the last "/" in system packages
as the dedup identifier instead.
> THRIFT-4797: Go import improvements

- CHANGES.md
- go.sum
- lib/go/thrift/configuration.go
- lib/go/thrift/socket.go
- test/go/genmock.sh
- test/go/src/bin/stress/main.go
- test/go/src/common/client.go
Client: go
We used to do DNS lookups in NewTSocketConf, without any timeout checks.
Stop doing that and do DNS lookups in TSocket.Open instead, which
already checks for ConnectTimeout set in TConfiguration.
This will be cherry-picked into 0.15.0 branch.
> THRIFT-5453: Defer DNS from NewTSocketConf to TSocket.Open

- lib/cpp/test/ToStringTest.cpp
This PR disables the locale-based tests for string conversion on Windows, due to problems in the Thrift CI on AppVeyor.
> lib/cpp/test/ToStringTest.cpp: Disabled locale-based tests on Windows

- build/cmake/BoostMacros.cmake
- build/cmake/DefineOptions.cmake
- lib/cpp/src/thrift/protocol/TCompactProtocol.tcc
- lib/cpp/src/thrift/transport/TBufferTransports.h
- lib/cpp/src/thrift/transport/TServerSocket.cpp
- lib/cpp/src/thrift/transport/TServerSocket.h
- lib/cpp/src/thrift/transport/TSocket.cpp
- lib/cpp/src/thrift/transport/TSocket.h
- lib/cpp/test/CMakeLists.txt
- lib/cpp/test/SecurityFromBufferTest.cpp
- lib/cpp/test/SecurityTest.cpp
- lib/cpp/test/TNonblockingSSLServerTest.cpp
- lib/cpp/test/TSSLSocketInterruptTest.cpp
This PR contains a number of small, self-contained improvements. The changes are:
- lib/cpp/src/thrift/transport/TBufferTransports.h: Minor whitespace changes
- TSocket.cpp: Print THRIFT_EAGAIN (timed out) to global error
- build/cmake/DefineOptions.cmake: Minor improvement in logging for 'WITH_MT'
- lib/cpp/test/CMakeLists.txt: Added missing boost::chrono
- build/cmake/BoostMacros.cmake: Removed 'Boost_NO_BOOST_CMAKE' and minor cleanup
- TCompactProtocol.tcc: add missing include cstdlib
- Include signal.h depending on HAVE_SIGNAL_H, not depending on __linux__
- Added new method isUnixDomainSocket() to check type of socket
> Several diverse improvements

- .gitignore
- LANGUAGES.md
- build/docker/ubuntu-bionic/Dockerfile
- build/docker/ubuntu-disco/Dockerfile
- build/docker/ubuntu-xenial/Dockerfile
- go.mod
- lib/go/README.md
- lib/go/test/fuzz/go.mod
- lib/go/test/fuzz/go.sum
- test/go/genmock.sh
Client: go
Update go versions used in travis to 1.16.7 and 1.17, update
LANGUAGES.md, and update go's README to clarify on support policy.
This change will be cherry-picked into 0.15.0 branch after merged.
> THRIFT-5447: Update supported Go versions

- lib/java/src/org/apache/thrift/protocol/TSimpleJSONProtocol.java
In a single-threaded scenario, StringBuilder has better performance than StringBuffer.
> Change StringBuffer to StringBuilder for more efficiency

- doc/specs/thrift-binary-protocol.md
- doc/specs/thrift-compact-protocol.md
As stated in THRIFT-5300, the specification was wrong and type identifiers for collections DO match the field types (except for the obvious boolean type which is then represented as only `BOOL_TRUE`).
Also replaced `BYTE` name with `I8` as the former is documented as a compatibility name only (especially since some languages have an unsigned byte type).
[skip ci] Trivial documentation changes only.
> Fix specification to match implementation

- build/docker/old/debian-stretch/Dockerfile
- build/docker/old/ubuntu-artful/Dockerfile
- build/docker/ubuntu-bionic/Dockerfile
- build/docker/ubuntu-disco/Dockerfile
- build/docker/ubuntu-xenial/Dockerfile
This PR adds a few additional dotnet dependencies to the docker containers. This may help to resolve build issue https://app.travis-ci.com/github/apache/thrift/jobs/534147247
The additional dependencies are:
dotnet-runtime-5.0 \
aspnetcore-runtime-5.0 \
dotnet-apphost-pack-5.0
> build/docker/*/Dockerfile: Added dotnet additional dependencies

- build/cmake/ConfigureChecks.cmake
- build/cmake/config.h.in
- lib/cpp/src/thrift/server/TNonblockingServer.cpp
- lib/cpp/src/thrift/thrift-config.h
Currently the cmake-generated header `config.h` is not used on MSVC. However it can be helpful to have the option to use this header, for example to detect the presence of newer Windows SDK features (like used in https://github.com/apache/thrift/pull/2327). 
I've tested this addition for over a year successfully on various combinations of Windows and did not find any issues or problems. I've also tried to make sure that previous Windows defines remain available unless overridden by cmake (which should be a good thing).
> Use the cmake-generated thrift config also on MSVC

- lib/cpp/src/thrift/transport/SocketCommon.cpp
- lib/cpp/src/thrift/transport/SocketCommon.h
- lib/cpp/src/thrift/transport/TServerSocket.cpp
- lib/cpp/src/thrift/transport/TSocket.cpp
- lib/cpp/src/thrift/windows/config.h
This PR adds support for domain sockets for Windows.
It is a follow-up of #2127 because the former ran into a timeout and can no be reopened (due to https://github.com/isaacs/github/issues/361).
In order to implement this change I've changed a basic property of C++ build configuration for Windows. This would not be strictly required but is quite helpful. Domain sockets are only available on recent versions of the Windows platform SDK. Therefore I've enabled the automatic configuration of `config.h` with cmake. I've checked the results and on my platform(s) the generated config header is sensible and matches the hard-coded default. However this change is not easily portable to autotools.
During the implementation I found a number of minor issues in TServerSocket and TSocket that I believe …
> THRIFT-5187: Added Win32 support for domain sockets (AF_UNIX)

- lib/cpp/src/thrift/transport/TPipeServer.cpp
- lib/cpp/src/thrift/transport/TPipeServer.h
- lib/cpp/src/thrift/windows/OverlappedSubmissionThread.h
- lib/cpp/src/thrift/windows/Sync.h
Thrift requires the header "Windows.h" in a few places. This header can be problematic to include, i.e. when included in headers, because it can affect standard C++ code. This PR tries to reduce the effects of including Windows.h.
> Reduce the usage of Windows.h, and add macros to slim Windows.h

- build/cmake/ThriftMacros.cmake
- lib/c_glib/CMakeLists.txt
- lib/c_glib/test/CMakeLists.txt
- lib/cpp/CMakeLists.txt
- lib/cpp/src/thrift/qt/CMakeLists.txt
- lib/cpp/test/CMakeLists.txt
- lib/cpp/test/qt/CMakeLists.txt
- test/c_glib/CMakeLists.txt
- test/cpp/CMakeLists.txt
- tutorial/cpp/CMakeLists.txt
This PR makes some changes to the cmake C++ build:
- When available, it will prefer the OpenSSL targets `OpenSSL::OpenSSL` and `OpenSSL::Crypto` over the older libraries variable.
-  It removes the use of a number of cmake macros that have basically no effect (instead they obscure what will happen), like `TARGET_INCLUDE_DIRECTORIES_THRIFT`, `TARGET_LINK_LIBRARIES_THRIFT`, `LINK_AGAINST_THRIFT_LIBRARY` and `TARGET_LINK_LIBRARIES_THRIFT_AGAINST_THRIFT_LIBRARY`.
> Minor cmake cleanup

- CHANGES.md
- compiler/cpp/src/thrift/generate/t_go_generator.cc
Client: go
Currently in the compiler generated go code, adding a new exception to
an existing endpoint can cause unexpected behaviors when the client
isn't updated. Fix the issue.
Will be cherry-picked into 0.15.0 after merged.
> THRIFT-5459: Fix breaking issue when adding a new exception

- lib/rs/src/protocol/compact.rs
The panic!() macro supports formatting. And if panic message is not a string literal, it will cause a compilation warning in the latest toolchain(1.54.0) .
> Remove redundant `format!(..)` macro calls

- lib/go/thrift/socket_non_unix_conn.go
- lib/go/thrift/socket_unix_conn.go
I tried the golang implementation to be used for wasm platform, and found that I can do so by disabling the unix (not windows) specific `checkConn` and `read0` implementations.
> Modified build tags to allow js/wasm target

- lib/py/src/server/TProcessPoolServer.py
Before this change, when using Python TProcessPoolServer with more than 1 workers, only one worker process will be successfully spawned and all the other processes will reach a pickling error and exit.
When [starting the worker process](https://github.com/apache/thrift/blob/82504b395e2d3e67f506a75ad51aa5734a9ad98a/lib/py/src/server/TProcessPoolServer.py#L99), the entire TProcessPoolServer is pickled and it seems that an alive `Process` contains a `weakref` which is  not picklable. 
Adding the `__getState__` function to exclude the information about all the other processes can solve this, thanks to the answer in https://stackoverflow.com/questions/62830911/typeerror-cannot-pickle-weakref-object .
> THRIFT-5454: add __getState__ function to TProcessPoolServer to enable correct multiprocessing behavior related to pickling

- lib/rs/test/Cargo.toml
- test/rs/Cargo.toml
- tutorial/rs/Cargo.toml
CI (cross tests) is currently failing due to the `clap` dependency being pinned as `2.33` instead of `~2.33`. In practice  `2.33` is interpreted as a caret requirement which translates to `>=2.33, < 3.0.0` and thus 2.34 is attempted which results in the following error:
```
error[E0658]: use of unstable library feature 'matches_macro'
--> /home/aliakber.saifee/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.34.0/src/errors.rs:392:10
|
392 |         !matches!(
|          ^^^^^^^
|
= note: for more information, see https://github.com/rust-lang/rust/issues/65721
```
An example build failure can be seen in [travis](https://app.travis-ci.com/github/apache/thrift/jobs/551099274#L5789)
> Fix CI build failure due to rust dependency (clap) compilation error

- lib/java/src/org/apache/thrift/TDeserializer.java
- lib/java/src/org/apache/thrift/partial/PartialThriftComparer.java
- lib/java/src/org/apache/thrift/partial/ThriftMetadata.java
Fixes the following issues found by spotbugs:
1. Private method org.apache.thrift.partial.ThriftMetadata$ThriftPrimitive.getParentStruct() is never called
2. Private method org.apache.thrift.TDeserializer.createNewStruct(ThriftMetadata$ThriftStruct) is never called
3. org.apache.thrift.partial.PartialThriftComparer.areEqual(ThriftMetadata$ThriftMap, Object, Object, StringBuilder) makes inefficient use of keySet iterator instead of entrySet iterator
> THRIFT-5486 : fix issues found by spotbugs

- lib/py/Makefile.am
- lib/py/src/ext/binary.cpp
- lib/py/src/ext/compact.cpp
- lib/py/test/test_thrift_file/TestServer.thrift
- lib/py/test/thrift_TSerializer.py
[THRIFT-5488](https://issues.apache.org/jira/browse/THRIFT-5488)
When using the refill  python functions for the fallback scenario in `ProtocolBase<Impl>::readBytes` ([protocol.tcc](../blob/master/lib/py/src/ext/protocol.tcc#L279)), a `SystemError` is raised in python 3.10 (this was only a warning till python 3.9) due to the use of `#yi` for the output buffer argument. The removal of the warning and dropped support is described in [Python issue 40943](https://bugs.python.org/issue40943).
Extra test cases have been added to cover serialization/deserialization both with compact & binary protocol both with and without the c-extension
~~Additionally the environment variable `PYTHONWARNINGS=error` has been added to the configuration of the python cross tests so as to verify this fix, and also …
> THRIFT-5488: Define PY_SSIZE_T_CLEAN to fix error with using PyObject_CallFunction in python 3.10

- lib/go/thrift/buf_pool.go
- lib/go/thrift/header_transport.go
- lib/go/thrift/header_transport_test.go
Client: go
Instead of binding 2 buffers (read/write) to each THeaderTransport, grab
one from the pool to be used for the whole read/write, and return it
back to the pool after the read/write is done. This would help reduce
the memory footprint from idle connections.
> THRIFT-5490: Use pooled buffer for THeaderTransport

- lib/go/thrift/framed_transport.go
- lib/go/thrift/framed_transport_test.go
- lib/go/thrift/header_transport_test.go
Client: go
Follow up on d582a8614, do the same thing on TFramedTransport.
> THRIFT-5490: Use pooled buffer for TFramedTransport

- lib/go/thrift/framed_transport_test.go
- lib/go/thrift/header_transport_test.go
Client: go
This is a trivial unit test improvement from the last commit. Of course
I only discovered the existence of testing/iotest package after I
re-invented the wheel.
> Use iotest.OneByteReader instead of self implemented one

- lib/py/test/thrift_TSerializer.py
Asserting on trying to deserialize None, or an invalid serialized buffer result in different exceptions being raised in python2 versus 3.
These errors can be seen for example in [travis ci](https://app.travis-ci.com/github/apache/thrift/jobs/554567087#L5586).
Removing these assertions since the tests were originally added to verify the compatibility issue with python 3.10 in #2487 and that fix can be verified by just asserting on passing an empty buffer.
> Remove excess assertions in python unit tests for serialization/deserialization

- lib/go/thrift/socket.go
- lib/go/thrift/socket_conn.go
- lib/go/thrift/ssl_socket.go
Client: go
We used to rely on setting the connection inside TSocket/TSSLSocket as
nil after Close is called to mark the connection as closed, but that is
not thread safe and causing TSocket.Close/TSSLSocket.Close cannot be
called concurrently. Use an atomic int to mark closure instead.
> go: Make socketConn.Close thread-safe

- LANGUAGES.md
- build/docker/ubuntu-bionic/Dockerfile
- build/docker/ubuntu-disco/Dockerfile
- build/docker/ubuntu-xenial/Dockerfile
Bump the versions of Go used in Travis to the latest point releases in
preparing for the upcoming v0.16.0 release.
Also switch the go download URL to the new go.dev domain.
Also update LANGUAGES.md accordingly, and mark that we support THeader
in Go now (we added the support in v0.13.0, just forgot to update
LANGUAGES.md accordingly).
> Bump the versions of Go used in Travis

- lib/java/build.gradle
There are repeated gradle errors since the jcenter server is currently not working. The build works for me when removing jcenter from the gradle / maven repositories.
> lib/java/build.gradle: Removed jcenter() after repeated errors

- compiler/cpp/src/thrift/generate/t_cpp_generator.cc
If a thrift file only contains an enum, then the c++ source file with
the implementation for to_string and ostream operator<< is not
generated.
This bug was introduced in PR #2095 / THRIFT-5168.
To fix this issue also set `has_members_` to true in `t_cpp_generator::generate_enum`, not only in `t_cpp_generator::generate_cpp_struct`.
> THRIFT-5418: C++ to_string and ostream operator not always generated

- lib/cpp/src/thrift/protocol/TList.h
- lib/cpp/src/thrift/protocol/TMap.h
- lib/cpp/src/thrift/protocol/TSet.h
This warning can been seen when compiling generated code using Visual Studio 16.11.
> Fix warning C4515: 'protocol': namespace uses itself

- compiler/cpp/src/thrift/generate/t_netstd_generator.cc
https://issues.apache.org/jira/projects/THRIFT/issues/THRIFT-5500
Fixes by adding `global::` in front of the call to `System.Object.Equals(...)`
> THRIFT-5500 uncompilable code when a .thrift struct named 'System' is present

- lib/rs/src/protocol/binary.rs
Is there something wrong with the thrift strict header comparing? 
The strict header highest bit should be 1, and as u8 in rust, maybe we should compare it to 0x80 which is 0x10000000.
I didn't submit the issue on apache jira because I was unable to reset my password. Sorry for that.
> fix wrong thrift strict header comparing

- compiler/cpp/src/thrift/generate/t_netstd_generator.h
- compiler/cpp/src/thrift/parse/t_field.h
* THRIFT-5506 C26495 variable "t_field::req_" not initialized, t_field.h:40
Compiler General
* THRIFT-5505 error: 'close_generator' overrides a member function but is not marked 'override'
Client: netstd
> THRIFT-5506 + THRIFT-5505

- compiler/cpp/src/thrift/generate/t_netstd_generator.cc
Client netstd
There's another location with the same issue.
> THRIFT-5504 CA2254 Message template should be compile time constant

- lib/cpp/src/thrift/protocol/TProtocol.h
- lib/cpp/src/thrift/windows/GetTimeOfDay.cpp
- lib/cpp/src/thrift/windows/SocketPair.h
- lib/cpp/src/thrift/windows/WinFcntl.h
- lib/cpp/src/thrift/windows/config.h
- lib/cpp/test/OpenSSLManualInitTest.cpp
- lib/py/src/ext/endian.h
I get the following error when this is not patched while cross-compiling form x86 linux via mingw32:
```bash
[11:36:52] /workspace/srcdir/duckdb/extension/parquet/../../third_party/thrift/thrift/protocol/TProtocol.h:25:22: fatal error: Winsock2.h: No such file or directory
[11:36:52]  #include <Winsock2.h>
[11:36:52]                       ^
[11:36:52] compilation terminated.
```
> Fix winsock capitalization for case sensitive cross-compilation

- test/netstd/Client/TestClient.cs
> THRIFT-5514 netstd test client slow in multithread mode

- lib/go/README.md
- lib/go/thrift/simple_server.go
- lib/go/thrift/simple_server_test.go
- test/go/src/common/clientserver_test.go
Client: [go]
If there is client connection and no data is send，we will encounter hang druing server stop:
1>If transport factory conf with socket timeout,we will hang until the deadline of the socket
2>If transport factory conf without socket timeout,we will hang forever
Stack As below:
goroutine 140800 [IO wait, 2706 minutes]:
internal/poll.runtime_pollWait(0x7fbf804fb100, 0x72)
runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc009087700, 0xc008196000, 0x0)
internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc009087700, {0xc008196000, 0x10000, 0x10000})
internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc009087700, {0xc008196000, 0x0, 0xc0061089b8})
net/fd_posix.go:56 +0x29 …
> THRIFT-5495: close client when shutdown server in go lib

- lib/py/src/transport/THttpClient.py
Based on the python source for `http.client`, `HTTPConnection.putheader`
can only be called after a request has been started, and before it's
been sent. Otherwise it will throw a `http.client.CannotSendHeader`
exception.
If the server returns a `Set-Cookie` header, the client will always
fail with the `CannotSendHeader` exception because `HTTPConnection.putheader`
is called after reading the response.
With this patch we will call this method before the request has been sent.
> THRIFT-5467 Python: fix CannotSendHeader exception

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- lib/go/test/Makefile.am
- lib/go/test/ProcessorMiddlewareTest.thrift
- lib/go/test/tests/processor_middleware_test.go
Client: go
This allows ProcessorMiddlewares to access such exceptions, unless
there's a network error writing the response (which takes priority).
> THRIFT-5527: Don't swallow idl exceptions in Process function

- lib/perl/lib/Thrift/HttpClient.pm
This fixes a bug in the headers being passed into HTTP::Request. Previously these were being set as a hash reference which is incorrect as it should be either an HTTP::Headers object or an array reference. The details are in the Jira issue.
> THRIFT-5532: Fix headers bug in Thrift/HttpClient.pm

- compiler/cpp/src/thrift/generate/t_java_generator.cc
- lib/java/gradle/generateTestThrift.gradle
- lib/java/test/org/apache/thrift/test/voidmethexceptions/ServiceAsyncImp.java
- lib/java/test/org/apache/thrift/test/voidmethexceptions/ServiceBase.java
- lib/java/test/org/apache/thrift/test/voidmethexceptions/ServiceSyncImp.java
- lib/java/test/org/apache/thrift/test/voidmethexceptions/TestVoidMethExceptions.java
- test/Makefile.am
- test/VoidMethExceptionsTest.thrift
Fix [THRIFT-5519 Java async client loses exceptions in void methods](https://issues.apache.org/jira/browse/THRIFT-5519).
> THRIFT-5519 Java async client loses exceptions in void methods

- lib/rs/Cargo.toml
In the Rust library, this updates the `ordered-float` dependency to its latest major version for inclusion in a potential future release.  There are an assortment of (mostly minor) improvements in the 2.x.x series.
> lib/rs/Cargo.toml:  Update ordered-float

- compiler/cpp/src/thrift/generate/t_generator.h
On recent MSVC versions, the thrift compiler fails to build under C++17 or C++20 -- as far as I can tell this is a bug in MSVC.
Splitting that clever "read the whole file into a string"-line into several seems to avoid it, with no functional change.
> workaround MSVC compiler bug

- lib/nodejs/lib/thrift/browser.js
- lib/nodejs/lib/thrift/ohos_connection.js
Related to [THRIFT-5535](https://issues.apache.org/jira/browse/THRIFT-5535).
In a word, I modified `lib/nodejs/lib/thrift/http_connection.js` to support OpenHarmony OS data request [API](https://developer.harmonyos.com/en/docs/documentation/doc-references/js-apis-net-http-0000001168304341#section24678814124).
> Maybe what you propose fits better under /contrib than in the general library.
OpenHarmony OS supports importing node.js module as dependency, and that this module required other node.js modules such as `TJSONProtocol`, so I still do that under nodejs lib.
Because OpenHarmony OS runs with the browserify environment, these interfaces were exported in `browser.js`.
It's hard to write test use case, but I created a [demo](https://github.com/konpeki622/openHarmony-thrift-demo) for …
> THRIFT-5535 support creating connection on OpenHarmonyOS

- CHANGES.md
- lib/go/thrift/debug_protocol.go
- lib/go/thrift/duplicate_protocol.go
Client: go
Currently go's TDebugProtocol does two things: log the read/writes, and
duplicate all the reads/writes to another TProtocol. For people who only
need the second feature, even if they use NopLogger for the logging
part, they still need to pay the price of all the fmt.Sprintf calls used
by logging, and on some cases those fmt.Sprintf calls alone can cause
significant CPU to be wasted (in one of our services fmt.Sprintf called
by TDebugProtocol used ~10% of CPU).
Create a dedicated TDuplicateToProtocol to reduce cpu waste, and mark
TDebugProtocol.DuplicateTo as deprecated.
> THRIFT-5539: Decouple TDuplicateToProtocol out of TDebugProtocol

- lib/rs/src/server/threaded.rs
- lib/rs/src/transport/socket.rs
- lib/rs/test/Cargo.toml
- lib/rs/test/src/bin/kitchen_sink_client.rs
- lib/rs/test/src/bin/kitchen_sink_server.rs
- test/rs/src/bin/test_client.rs
- test/rs/src/bin/test_server.rs
- test/rs/src/lib.rs
- test/tests.json
Client: rs
The Thrift crate does not support Unix Domain Sockets (UDS). After reviewing and expressing my thoughts on THRIFT-5283, I added support for UDS.
This is not a breaking change. Inspired by how actix_web::HttpServer supports UDS, I added an additional fn to listen to UDS. I reorganized some other existing code to be able to reuse it for UDS. I also had to implement the trait TIoChannel for UnixStream. This went to transport::socket.
As UnixStream is only available on Unix, I tagged the code with #[cfg(unix)]. I also cross compiled lib/rs to Windows with the following cargo targets:
i686-pc-windows-gnu
i686-pc-windows-msvc
x86_64-pc-windows-gnu
x86_64-pc-windows-msvc
Last but not least I ran the rust <-> rust test harnesses as well as the cross test harnesses. This looks good. At …
> THRIFT-5283: add support for Unix Domain Sockets in lib/rs

- doc/specs/HeaderFormat.md
> THRIFT-5541: Clarify on THeader key/value format in the spec

- doc/specs/thrift-rpc.md
based on TBinaryProtocol.java, the strictWrite would write VERSION_1 | message.type  first. and the first byte would be 0x80. but in thrift-rpc.md, it's described as 0x81.
> fix binary protocol's first byte value description in thrift-rpc.md

- compiler/cpp/src/thrift/generate/t_rs_generator.cc
- lib/rs/src/protocol/mod.rs
Client: rs
In order for code to be generic over any generated Thrift object, extract the read and write methods into a `trait`.
[THRIFT-4100](https://issues.apache.org/jira/browse/THRIFT-4100)
> THRIFT-4100: Extract Rust read/write struct methods into a trait

- lib/java/gradle/sourceConfiguration.gradle
- lib/java/src/org/apache/thrift/partial/TFieldData.java
- lib/java/src/org/apache/thrift/partial/ThriftMetadata.java
- lib/java/src/org/apache/thrift/protocol/TCompactProtocol.java
- lib/java/src/org/apache/thrift/transport/THttpClient.java
- lib/java/test/org/apache/thrift/protocol/ProtocolTestBase.java
- lib/java/test/org/apache/thrift/test/JavaBeansTest.java
fix deprecation and enable xlint for java library
> THRIFT-5563: fix deprecation and enable xlint for java library

- .travis.yml
travis ci to use xenial as base image  
currently the base image for travis ci is trusty but currently the default is xenial. the ci job itself is done with docker image so upgrading should be easy and low risk.
upgrading to using default distro may improve the wait time for CI given it's the default now and a more recent distro
> THRIFT-5565: travis ci to use xenial as base image

- compiler/cpp/src/thrift/generate/t_go_generator.cc
This adds a negative size checks in the Go generator for code generated when reading maps, sets and lists.
> THRIFT-5569: add negative size checks in Go generator when reading maps, sets and lists

- compiler/cpp/src/thrift/generate/t_js_generator.cc
Fixes two cases where the optional flag `?` is generated incorrectly for typescript, leading to invalid typescript generation that cannot pass `tsc` builds. 
It is possible to set an optional message parameter on thrift exception types. 
```thrift
exception Bad { 
1: string message = "";
}
```
However, for the javascript runtime, thrift exception types ultimately derive from `Error` which has a *required* message field. 
**Before**
```ts
export declare class Bad extends Thrift.TException {
message?: string;
}
/*
Error: TS2416
Property 'message' in type 'T' is not assignable to the same property in base type 'Error'.
Type 'string | undefined' is not assignable to type 'string'.
Type 'undefined' is not assignable to type 'string'.(2416)
*/
```
**After**
Special case `message` fields for …
> Fix invalid optional members and argument generation for typescript

- lib/nodejs/lib/thrift/framed_transport.js
1.  use `array.push` instread of `Array.concat`, `array.push` is more effective than `Array.concat`, see benchmark results
2.  reduce data copy action for improving performance.
```javascript
const Benchmark = require('benchmark');
const buffer = Buffer.alloc(1024)
buffer.fill('A')
const loop = 1024;
const suite = new Benchmark.Suite()
suite
.add('Buffer.concat', function () {
let target = Buffer.alloc(0)
for(let i = 0; i < loop; ++i){
target = Buffer.concat([target, buffer], target.length + buffer.length)
}
})
.add('Array.push', function () {
const target = []
for(let i = 0; i < loop; ++i){
for(let j = 0; j < buffer.length; ++j){
target.push(buffer[i])
}
}
})
.on('cycle', function(event) {
console.log(String(event.target));
})
.on('complete', function() {
console.log('Fastest is ' + …
```
> Enhance TFramedTransport performance for nodejs

- LANGUAGES.md
- build/docker/ubuntu-bionic/Dockerfile
- build/docker/ubuntu-disco/Dockerfile
- build/docker/ubuntu-xenial/Dockerfile
- configure.ac
- lib/go/Makefile.am
- lib/go/test/Makefile.am
- lib/go/test/fuzz/Makefile.am
- lib/go/thrift/binary_protocol.go
- lib/go/thrift/protocol.go
- lib/go/thrift/serializer_test.go
- test/go/Makefile.am
- test/go/genmock.sh
- tutorial/go/Makefile.am
Client: go
Per our support policy, drop support of go 1.16 and add support of go
1.18.
Also enable go vet in make check, and fix issues reported by go vet.
> Update Go versions used in travis and LANGUAGES.md

- .travis.yml
- build/docker/refresh.sh
because building image requires kerl to build erlang, which requires >10
min to build and meanwhile not printing to stdout, failing the travis
build
Currently the travis CI is broken because the step when kerl is building erlang OTP from source but the build process produces no output for >10 mins and travis will then fail the build if no output is detected.
The max number of build errors has been reached so now the travis CI build is suspended.
The easy fix is to allow travis to wait a bit longer (the erlang build itself takes around 1100 seconds).
this is a follow up on:
- https://github.com/apache/thrift/pull/2541
> THRIFT-5572: add travis_wait for rebuilding docker image

- .github/workflows/build.yml
setup a basic github action. this is part of THRIFT-5564 but does not completely close it yet.
> THRIFT-5564: setup compiler-building github action [skip ci]

- compiler/cpp/src/thrift/generate/t_java_generator.cc
- lib/java/gradle/generateTestThrift.gradle
- lib/java/src/main/java/org/apache/thrift/meta_data/FieldMetaData.java
- lib/java/src/test/java/org/apache/thrift/TestAnnotationMetadata.java
- lib/java/src/test/resources/JavaAnnotationTest.thrift
add java code gen param to support including field annotation as metadata
Currently the code generator has a map of string to string field that denotes the "annotations" for a field: https://github.com/apache/thrift/blob/90ea2e8398eda32da8be0b3514516e7ad932a869/compiler/cpp/src/thrift/parse/t_field.h#L109
It is made available to generators such as JSON (in https://github.com/apache/thrift/blob/90ea2e8398eda32da8be0b3514516e7ad932a869/compiler/cpp/src/thrift/generate/t_json_generator.cc#L267-L274) to allow (runtime) interpretation of such metadata.
In Java, similar mechanism exists to register field metadata (via https://github.com/apache/thrift/blob/90ea2e8398eda32da8be0b3514516e7ad932a869/compiler/cpp/src/thrift/generate/t_java_generator.cc#L2862-L2865 which calls …
> THRIFT-5544: add java code gen param to support including field annotation as metadata

- tutorial/shared.thrift
- tutorial/tutorial.thrift
warnings in build:
```
generate:
[exec] [WARNING:/opt/thrift/src/tutorial/shared.thrift:26] No generator named 'cl' could be found!
[exec] [WARNING:/opt/thrift/src/tutorial/tutorial.thrift:67] No generator named 'cl' could be found!
```
> THRIFT-5567: remove cl namespace references

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- lib/go/thrift/compact_protocol.go
Client: go
This was a copy-paste error in the original implementation in
6583f4e52345c3b05a76f0b188836599628356e8.
> THRIFT-5569: Fix size check in TCompactProtocol.ReadListBegin

- lib/go/thrift/simple_server.go
- lib/go/thrift/simple_server_test.go
Client: go
Make it unwrap to context.Canceled, since the main use case of it is to
be returned in lieu of context.Canceled to avoid extra writing to the
client, so that if user has any processor middleware that checks for
context.Canceled error those would still work.
> Minor tweak to ErrAbandonRequest in go library

- lib/py/src/transport/TSocket.py
- lib/py/test/test_socket.py
- lib/py/test/test_sslsocket.py
The update to TSocket in https://github.com/MikaelSmith/thrift/commit/01d53f483a7531ad4899b522060e8913dca309fb errors for TSSLSocket with
```
ValueError: non-zero flags not allowed in calls to recv() on <class 'ssl.SSLSocket'>
```
Handles ValueError from ssl.SSLSocket to fix isOpen when using TSSLSocket.
> THRIFT-5595: Avoid peek request with SSLSocket

- lib/py/src/server/TNonblockingServer.py
just a typo when I check the python version server
> [skip ci] fix typo

- CHANGES.md
- lib/go/test/ClientMiddlewareExceptionTest.thrift
- lib/go/test/Makefile.am
- lib/go/test/tests/client_middleware_exception_test.go
- lib/go/thrift/exception.go
- lib/go/thrift/middleware.go
Client: go
Provide ExtractIDLExceptionClientMiddleware client middleware
implementation to extract exceptions defined in thrift IDL into err
return so they are accessible from other client middlewares.
> THRIFT-5605: Client middleware to extract exceptions

- LANGUAGES.md
- build/docker/ubuntu-bionic/Dockerfile
- build/docker/ubuntu-disco/Dockerfile
- build/docker/ubuntu-xenial/Dockerfile
- go.mod
- lib/go/test/fuzz/go.mod
- lib/go/thrift/pointerize.go
Client: go
Also provide generic version of Pointer helper function.
> Update supported go version to 1.18.* and 1.19.*

- CHANGES.md
- lib/go/test/tests/json_protocol_deserializer_test.go
- lib/go/thrift/deserializer.go
- lib/go/thrift/serializer.go
- lib/go/thrift/simple_json_protocol.go
Client: go
Add Reset to TJSONProtocol, and call it in deserializer and serializer
to make sure that it's always safe to be used in the pool version.
> THRIFT-5609: Make TJSONProtocol safe to be used in deserializer pool

- lib/go/thrift/deserializer.go
- lib/go/thrift/framed_transport.go
- lib/go/thrift/header_transport.go
- lib/go/thrift/http_client.go
- lib/go/thrift/http_transport.go
- lib/go/thrift/pool.go
- lib/go/thrift/pool_test.go
- lib/go/thrift/protocol_test.go
- lib/go/thrift/serializer.go
- lib/go/thrift/simple_server_test.go
Since we dropped support of Go 1.18-, use generic to avoid dealing with
type assertions with interface{}/any.
While I'm here, also remove the usages of ioutil, as that's officially
marked as deprecated in Go 1.19.
Client: go
> Add a generic sync.Pool wrapper to go library

- compiler/cpp/src/thrift/generate/t_cpp_generator.cc
**_Generated was:_**
```CPP
class FU_LB : public virtual ::apache::thrift::TBase {
public:
FU_LB(const FU_LB&);
FU_LB(FU_LB&&) noexcept;
FU_LB& operator=(const FU_LB&);
FU_LB& operator=(FU_LB&&) noexcept;
FU_LB() noexcept
: ctrl(0),
op((FU_LIST_OP::type)0),
pos(0) {
op = (FU_LIST_OP::type)0;
}
virtual ~FU_LB() noexcept;
```
**_Generated became:_**
```CPP
class FU_LB : public virtual ::apache::thrift::TBase {
public:
FU_LB(const FU_LB&);
FU_LB(FU_LB&&) noexcept;
FU_LB& operator=(const FU_LB&);
FU_LB& operator=(FU_LB&&) noexcept;
FU_LB() noexcept
: ctrl(0),
op(static_cast<FU_LIST_OP::type>(0)),
pos(0) {
}
virtual ~FU_LB() noexcept;
```
> THRIFT-5576: fix old-style cast and redundant copy

- compiler/cpp/src/thrift/thriftl.ll
This PR contains mostly pedantic whitespace changes. Three arguments of type `char*` can be more pedantically set to `const char*` because they do not modify the values. This resolves a build error with Visual Studio 2022 (current latest).
> Minor fixes to satisfy MSVC 2022 in c++20 mode

- lib/netstd/Thrift/Transport/Client/TNamedPipeTransport.cs
- lib/netstd/Thrift/Transport/Server/TNamedPipeServerTransport.cs
- test/netstd/Server/TestServer.cs
> THRIFT-5624 suboptimal performance of the c# named pipe server transport in multithread servers

- lib/cpp/src/thrift/transport/TBufferTransports.h
- lib/cpp/src/thrift/transport/TFileTransport.cpp
- lib/cpp/src/thrift/transport/THeaderTransport.h
- lib/cpp/test/TransportTest.cpp
It seems that Apache Thrift wants to drop Boost dependency eventually.
See also: https://github.com/apache/thrift/blob/4646a3557b822c3893dc6773882a689118b77611/lib/cpp/CMakeLists.txt#L20-L21
include(BoostMacros)
This is a step for it. We don't need to use boost::scoped_array because
we can use std::unique_ptr. We require C++11 or later and std::unique_ptr
can be used with C++11 or later.
> THRIFT-5602: Use std::unique_ptr instead of boost::scoped_array

- compiler/cpp/src/thrift/thriftl.ll
- compiler/cpp/src/thrift/thrifty.yy
- lib/erl/Makefile.am
- test/v0.16/NameConflictTest.thrift
> THRIFT-5626 Parser should not confuse data types and field names

- lib/c_glib/CMakeLists.txt
- lib/cpp/CMakeLists.txt
If available the targets of OpenSSL and ZLIB should be used instead of library paths
> Use openssl and zlib targets

- compiler/cpp/test/compiler/Included.thrift
fix staleness check in cmake/ctest, the line was mistakenly removed in https://github.com/apache/thrift//commit/944b8e68a099392d80153ebcf26f32ff7f1d893a#diff-f5cd0615ff0ea8e5fb4cc8aae1b13f897a6386fe99238b93e1ea09a71d8c44c3L1
> fix staleness check in cmake/ctest

- compiler/cpp/src/thrift/generate/go_validator_generator.h
- compiler/cpp/src/thrift/generate/validator_parser.h
- compiler/cpp/src/thrift/thrifty.yy
THRIFT-5627 More consistent syntax for cpp_type
Second commit fixes a bunch of warnings that showed up in VS2022
> THRIFT-5627

- .github/workflows/build.yml
- .github/workflows/cmake.yml
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using https://github.com/step-security/secure-workflows. 
GitHub Actions workflows have a GITHUB_TOKEN with `write` access to multiple scopes. 
Here is an example of the permissions in one of the workflows:
https://github.com/apache/thrift/actions/runs/3045440603/jobs/4907003617#step:1:19
After this change, the scopes will be reduced to the minimum needed for each workflow. 
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced. 
- GitHub recommends defining minimum GITHUB_TOKEN permissions. 
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-githu …
> add minimum GitHub token permissions for workflows

- lib/netstd/Thrift/Protocol/TBinaryProtocol.cs
- lib/netstd/Thrift/Protocol/TCompactProtocol.cs
- lib/netstd/Thrift/Protocol/TJSONProtocol.cs
- lib/netstd/Thrift/Protocol/TProtocolDecorator.cs
- lib/netstd/Thrift/Transport/Layered/TBufferedTransport.cs
- lib/netstd/Thrift/Transport/Layered/TFramedTransport.cs
- lib/netstd/Thrift/Transport/Layered/TLayeredTransport.cs
- lib/netstd/Thrift/Transport/TEndpointTransport.cs
- lib/netstd/Thrift/Transport/TTransport.cs
Made ResetConsumedMessageSize  a public abstract member of TTransport.
Implemented on all inheritors.
Called ResetConsumedMessageSize from all ReadMessageEndAsync.
> Thrift-5628: Call ResetConsumedMessageSize from ReadMessageEndAsync

- .travis.yml
- build/docker/ubuntu-focal/Dockerfile
> THRIFT-5574: add ubuntu focal build

- lib/java/src/main/java/org/apache/thrift/TNonblockingMultiFetchClient.java
- lib/java/src/main/java/org/apache/thrift/server/AbstractNonblockingServer.java
- lib/java/src/main/java/org/apache/thrift/transport/TFileTransport.java
> THRIFT-5632: [java][lib] fix pmd main for java

- LANGUAGES.md
- https://issues.apache.org/jira/browse/THRIFT-5634
change :
https://thrift.apache.org/docs/doc/images/cgrn.png -> https://thrift.apache.org/doc/images/cgrn.png
https://thrift.apache.org/docs/doc/images/cred.png -> https://thrift.apache.org/doc/images/cred.png
> THRIFT-5634: thrift docs picture was broken

- .github/workflows/build.yml
- closes #2594 
as it replaces both
> add a rust GitHub action and cross test [skip ci]

- configure.ac
Gradle is required to build the Kotlin library so we should check for its presence during the configure process. Currently, it only checks for the presence of Java so if Java is installed but Gradle is not, the build will fail. This PR adds the Gradle check for Kotlin.
> THRIFT-5646 Check for the presence of Gradle to build the Kotlin library

- lib/rs/Cargo.toml
Version 2.0.0 had RUSTSEC advisory, see https://github.com/rustsec/advisory-db/blob/main/crates/ordered-float/RUSTSEC-2020-0082.md
2.0.1 resolved the issue but I figured this is a good opportunity to move to the latest version.
I did not create a JIRA issue since this is a trivial change, but I am happy to do that if needed.
> Update ordered-float dependency to latest version

- lib/d/src/thrift/async/socket.d
Other platforms seem to compile fine, ECONNRESET is undeclared on macOS. Add the appropriate definition so the library builds on macOS.
> THRIFT-5647: Add ECONNRESET definition for macOS.

- .github/workflows/build.yml
- lib/java/src/test/java/org/apache/thrift/server/ServerTestBase.java
> THRIFT-5649: add github action for go

- .github/workflows/build.yml
- LANGUAGES.md
- build/docker/README.md
- build/docker/ubuntu-bionic/Dockerfile
- build/docker/ubuntu-focal/Dockerfile
- debian/control
- doc/install/README.md
- lib/java/README.md
- lib/java/gradle/sourceConfiguration.gradle
- lib/java/gradle/unitTests.gradle
- lib/java/src/test/java/org/apache/thrift/partial/ThriftSerDe.java
- lib/java/src/test/java/org/apache/thrift/protocol/ProtocolTestBase.java
- lib/java/src/test/java/org/apache/thrift/test/ReadStruct.java
- lib/java/src/test/java/org/apache/thrift/test/WriteStruct.java
- lib/java/src/test/java/org/apache/thrift/transport/TestTSaslTransports.java
- lib/kotlin/build.gradle.kts
- lib/kotlin/cross-test-client/build.gradle.kts
- lib/kotlin/cross-test-server/build.gradle.kts
java to use jdk 17, this is a second try after #2662
> THRIFT-5644: java to use jdk 17 and upgrade minimal language level to 11

- contrib/thrift-maven-plugin/pom.xml
There are 2 security vulnerabilities found in com.google.guava:guava 14.0.1
- [CVE-2018-10237](https://www.oscs1024.com/hd/CVE-2018-10237)
- [CVE-2020-8908](https://www.oscs1024.com/hd/CVE-2020-8908)
Upgrade com.google.guava:guava from 14.0.1 to 30.0-jre for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> fix(sec): upgrade com.google.guava:guava to 30.0-jre

- compiler/cpp/src/thrift/generate/t_delphi_generator.cc
- lib/delphi/test/TestClient.pas
- lib/delphi/test/codegen/run-Pascal-Codegen-Tests.bat.tmpl
- lib/delphi/test/serializer/TestSerializer.Data.pas
> THRIFT-5656 Escape Delphi keywords with '&' prefix instead of '_' suffix

- lib/swift/Sources/TCompactProtocol.swift
- lib/swift/Sources/TProtocol.swift
Removes non-standard utf8 type with raw value 16 and replaces uuid raw value with 16. 
Brings Swift in compliance with spec: https://github.com/apache/thrift/blob/0223d6346675c5089c2a2de5fb6f3858e599c9a9/doc/specs/thrift-binary-protocol.md?plain=1#L204
This is technically a breaking change by removing the utf8 type, however this type was non-standard and not documented in the spec.
This causes new failing crosstests with Swift-Java with the binary protocol due to Java not yet being updated to match the spec.
> THRIFT-5653: UUID should use value 16 in Swift binary protocol

- build/docker/scripts/autotools.sh
Previously, when doing manual runs inside of the docker container, the `autotools.sh` script would fail if the `.m2/` directory already existed. This was a minor annoyance.
Simply pass the `-p` flag to `mkdir`.
> build: docker: scripts: autotools: do not fail if .m2/ exists

- lib/cpp/src/thrift/async/TAsyncBufferProcessor.h
- lib/cpp/src/thrift/async/TAsyncProcessor.h
- lib/cpp/src/thrift/concurrency/FunctionRunner.h
- lib/cpp/src/thrift/transport/TBufferTransports.cpp
- lib/cpp/src/thrift/transport/TServerSocket.h
Manual runs of the autotools docker script were failing due to `std::functional` not being a member of `std`. Similar error messages for `std::ceil` and `std::log`.
No
No
Yes
Yes
> lib: cpp: add missing functional and cmath includes

- lib/cpp/src/thrift/protocol/TProtocol.h
Zephyr's byteorder is defined in `<zephyr/sys/byteorder.h>`. However, the `bswap_xx` macros are also defined there. They need to be `#undef`d first when building for big-endian architectures, since the Thrift byteorder macros are no-ops for little-endian architectures.
> THRIFT-5658: lib: cpp: TProtocol: support zephyr byteorder

- lib/cpp/src/thrift/TOutput.cpp
In Zephyr, optimize `TOutput::strerror_s` to minimize (stack) space. The Zephyr string error table is in ROM in any case, so string values will not be overwritten (if they happen to be compiled-in).
> THRIFT-5661: lib: cpp: TOutput: add zephyr-specific strerror_s implementation

- compiler/cpp/src/thrift/generate/t_rb_generator.cc
- lib/rb/lib/thrift/client.rb
- lib/rb/spec/client_spec.rb
> THRIFT-5308 Implement Validate message reply seq ids

- lib/cpp/src/thrift/protocol/TBinaryProtocol.h
- lib/cpp/src/thrift/protocol/TCompactProtocol.h
- lib/cpp/src/thrift/protocol/TJSONProtocol.h
This avoids compiler warnings about inconsistent use of `override` like the one below.
```
In file included from /Users/cfriedt/workspace/thrift/test/cpp/src/TestServer.cpp:29:
/Users/cfriedt/workspace/thrift/lib/cpp/src/thrift/protocol/TJSONProtocol.h:255:8: warning: 'checkReadBytesAvailable' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
void checkReadBytesAvailable(TList& list)
^
/Users/cfriedt/workspace/thrift/lib/cpp/src/thrift/protocol/TProtocol.h:563:16: note: overridden virtual function is here
virtual void checkReadBytesAvailable(TList& list)
```
> THRIFT-5659: lib: cpp: protocol: declare  when methods override

- Makefile.am
- compiler/cpp/src/thrift/generate/t_java_generator.cc
I might have overlooked a few cases. I used the test case from that ticket.
> THRIFT-3956 Java keywords that are legal in IDL can lead to generated code that will not compile

- LANGUAGES.md
- build/docker/ubuntu-bionic/Dockerfile
- build/docker/ubuntu-focal/Dockerfile
- build/docker/ubuntu-jammy/Dockerfile
Standardizes the version of Swift used across all CI (actions + travis) to Swift 5.7 (the latest version)
This should fix the current Travis Swift build failure on Linux due to an older version being used:
```
/thrift/src/lib/swift/Sources/TSocketServer.swift:83:60: error: type 'CFSocketError' (aka 'Int') has no member 'success'
if CFSocketSetAddress(sock, cfaddr) != CFSocketError.success { //kCFSocketSuccess {
~~~~~~~~~~~~~ ^~~~~~~
```
> THRIFT-5657: Use Swift 5.7 in all CI (github actions + travis)

- lib/cpp/src/thrift/transport/TFDTransport.cpp
- lib/cpp/src/thrift/transport/TFileTransport.cpp
Several build failures in Travis resulted from an include-order problem in `TFileTransport.cpp`.
```
libtool: compile:  g++ -std=c++11 -DHAVE_CONFIG_H -I/usr/include -I./src -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wall -Wextra -pedantic -g -O2 -MT src/thrift/transport/TFDTransport.lo -MD -MP -MF src/thrift/transport/.deps/TFDTransport.Tpo -c src/thrift/transport/TFDTransport.cpp -o src/thrift/transport/TFDTransport.o >/dev/null 2>&1
libtool: compile:  g++ -std=c++11 -DHAVE_CONFIG_H -I/usr/include -I./src -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wall -Wextra -pedantic -g -O2 -MT src/thrift/transport/TFileTransport.lo -MD -MP -MF src/thrift/transport/.deps/TFileTransport.Tpo -c src/thrift/transport/TFileTransport.cpp  -fPIC -DPIC -o src/thrift/transport/.libs/TFileTransport.o
In …
```
> THRIFT-5663: lib: cpp: usleep was not declared in this scope

- lib/cpp/src/thrift/transport/TNonblockingServerSocket.cpp
- lib/cpp/src/thrift/transport/TSSLSocket.cpp
- lib/cpp/src/thrift/transport/TServerSocket.cpp
- lib/cpp/src/thrift/transport/TSocket.cpp
The `<sys/poll.h>` header is not actually where `poll(2)` must be defined according to the spec. However, it may be the case that some random UNIX-like OS uses `<sys/poll.h>` instead.
Both use cases can be supported simply by including the proper header, if it exists.
Tested with both the `autotools.sh` and `cmake.sh` build strategies, and is fine.
> THRIFT-5666: lib: cpp: prefer poll.h over sys/poll.h

- lib/cpp/src/thrift/numeric_cast.h
- lib/cpp/src/thrift/transport/TTransportException.h
This adds an equivalent implementation of `boost::numeric_cast` written purely in standard c++.
The implementation is relatively trivial and reduces the dependency on `boost`.
Adapted from
https://stackoverflow.com/a/49658950/5636218
> THRIFT-5660: lib: cpp: TTransportException: create thrift::numeric_cast

- LANGUAGES.md
A missing slash in the end `</td>` tag of field cell for Delphi and .NET Standard was generating an additional empty cell, breaking the table (and generating misleading info).
[skip ci]
Added missing slashes.
> [docs] Add missing slash to avoid empty cell

- lib/c_glib/test/testthrifttestclient.cpp
Previously, the c_glib library tests failed to compile due to implicit function declarations for `sleep()`, `fork()`, and `alarm()`.
Include `<unistd.h>` to address all of those issues (on platforms that have `<unistd.h>`).
Signed-off-by: Christopher Friedt <cfriedt@meta.com>
```
testthrifttestclient.cpp: In member function 'virtual void TestHandler::testOneway(int)':
testthrifttestclient.cpp:334:5: error: 'sleep' was not declared in this scope
334 |     sleep(sleepFor);
|     ^~~~~
testthrifttestclient.cpp: In function 'void test_thrift_client()':
testthrifttestclient.cpp:592:3: error: 'sleep' was not declared in this scope; did you mean 'g_usleep'?
592 |   sleep (5);
|   ^~~~~
|   g_usleep
testthrifttestclient.cpp: In function 'int main()':
testthrifttestclient.cpp:616:13: error: 'fork' …
```
> lib: c_glib: fix compile error due to missing unistd.h

- lib/netstd/Thrift/Transport/Server/TServerSocketTransport.cs
- lib/py/src/transport/TSocket.py
Unlike servers in other languages (tested: cpp & python), netstd (Csharp) listens only on IPv4. This can cause errors and delays on clients if they use "localhost" for hostname.
PS: Could you update PyPI when this gets released (I guess with version 0.18.0)?
> netstd Server: Add IPv6

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- compiler/cpp/src/thrift/generate/t_go_generator.h
- lib/go/test/ForwardTypedef.thrift
- lib/go/test/Makefile.am
Client: go
While https://github.com/apache/thrift/pull/951 fixed the bug with forward typedef used in container values, it also introduced a bug that broke forward typedef used in other cases in go code. Limit the fix of it to only the container key and value types to fix other cases.
> THRIFT-5601: Fix forward typedef in go compiler

- compiler/cpp/src/thrift/generate/t_json_generator.cc
- lib/json/schema.json
The json generator currently outputs the type `i32` for all enum fields. This commit changes it to output `enum` instead and output a `class` property with a reference to the actual enum type, similar to how it works for structs.
This is a breaking change for the json generator because it introduces a new type id (`enum`) which also includes a `class` reference.
> Improve enum support for json generator

- .github/workflows/build.yml
- LANGUAGES.md
- build/docker/ubuntu-bionic/Dockerfile
- build/docker/ubuntu-focal/Dockerfile
- build/docker/ubuntu-jammy/Dockerfile
- go.mod
- lib/go/test/fuzz/go.mod
- lib/go/test/go.mod
- test/go/go.mod
Following our policy regarding supported go releases, change the supported go versions to 1.19.* and 1.20.* with the release of go 1.20.
> Update supported go versions

- lib/go/thrift/serializer_test.go
- lib/go/thrift/simple_server.go
- lib/go/thrift/socket_conn.go
Those come with nocopy protection, so they can prevent bugs like people passing the types by value instead of by pointer from the compiler.
> go: Use new atomic types introduced in go1.19

- build/docker/README.md
- build/docker/old/debian-stretch/Dockerfile
- build/docker/old/ubuntu-artful/Dockerfile
- build/docker/old/ubuntu-disco/Dockerfile
- build/docker/old/ubuntu-xenial/Dockerfile
- build/docker/ubuntu-bionic/Dockerfile
- build/docker/ubuntu-focal/Dockerfile
- build/docker/ubuntu-jammy/Dockerfile
- compiler/cpp/src/thrift/generate/t_netstd_generator.cc
- configure.ac
- lib/netstd/Benchmarks/Thrift.Benchmarks/Thrift.Benchmarks.csproj
- lib/netstd/Tests/Thrift.IntegrationTests/Thrift.IntegrationTests.csproj
- lib/netstd/Tests/Thrift.PublicInterfaces.Compile.Tests/Thrift.PublicInterfaces.Compile.Tests.csproj
- lib/netstd/Tests/Thrift.Tests/Thrift.Tests.csproj
- lib/netstd/Thrift/Thrift.csproj
- lib/netstd/Thrift/Transport/Server/TNamedPipeServerTransport.cs
- test/netstd/Client/Client.csproj
- test/netstd/Client/TestClient.cs
- test/netstd/Server/Server.csproj
- test/netstd/Server/TestServer.cs
- tutorial/netstd/Client/Client.csproj
- tutorial/netstd/Interfaces/Interfaces.csproj
- tutorial/netstd/Server/Program.cs
- tutorial/netstd/Server/Server.csproj
Client: netstd
* Upgrade to net7.0 incl net7.0 library target
*  prevent against new warning [CS8981](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/warning-waves?f1url=%3FappId%3Droslyn%26k%3Dk(CS8981)#cs8981---the-type-name-only-contains-lower-cased-ascii-characters)"The type name only contains lower-cased ascii characters" that comes alomng with it,
*  also remove the already deprecated NamedPipeClientFlags enum for good.
> THRIFT-5684 upgrade to net7.0

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- compiler/cpp/src/thrift/generate/t_go_generator.h
- lib/go/test/ForwardType.thrift
- lib/go/test/Makefile.am
- lib/go/test/tests/forwardtype_test.go
This reverts commit b39370ec3bc96d201bbc82fbde136f98ae605ed1, and also adds a test case for THRIFT-5685.
> THRIFT-5685: Revert "THRIFT-5601: Fix forward typedef in go compiler"

- lib/cpp/test/SecurityFromBufferTest.cpp
- lib/cpp/test/SecurityTest.cpp
OpenSSLv3 does stricter protocol matching in the handshake.
This change adapts the test matrix to work with either both widespread versions of OpenSSL.
Partially fixes [THRIFT-5672](https://issues.apache.org/jira/browse/THRIFT-5672).
> Fix Security Tests for OpenSSLv3

- lib/cpp/libthrift.vcxproj
- lib/cpp/libthrift.vcxproj.filters
- lib/cpp/libthriftnb.vcxproj
- lib/cpp/libthriftnb.vcxproj.filters
The VisualStudio project files in lib/cpp are completely outdated.
This PR:
* Upgrades the project files to VisualStudio 2015.
* Fixes wrong source filenames in the project files.
* Adds thrift_EXPORTS symbol.
> Fix VisualStudio project files and upgrade to VS2015

- lib/cpp/src/thrift/protocol/TBinaryProtocol.tcc
MSVC warning C4706: assignment within conditional expression
> Fix MSVC warning C4706 (BinaryProtocol)

- lib/java/gradle/sourceConfiguration.gradle
It stated Java 8 but now we are on Java 11
Update Java lib gradle build script docs
> Update Java lib gradle build script docs

- lib/py/src/transport/TSocket.py
The changes introduced in 916ae8b8134630f49d32e47c3f0f3218f855a24c causes OSError when the socket is of IPv4 family.  This can be verified by the code snippet below (at least on RHEL 8 and RHEL 9 with Python 3.9):
```python
import socket
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 0)
```
This will raise an exception `OSError: [Errno 92] Protocol not available`.
My fix is pretty simply: only set that IPv6 option when the socket family is IPv6.
> py TSocket: Only disable socket.IPV6_V6ONLY when the family is AF_INET6

- lib/cpp/test/SecurityFromBufferTest.cpp
- lib/cpp/test/SecurityTest.cpp
Fixes a build error on msvc that was introduced with #2760.
> Add missing include for the security tests

- lib/java/src/main/java/org/apache/thrift/transport/TByteBuffer.java
- lib/java/src/test/java/org/apache/thrift/transport/TestTByteBuffer.java
Client: java
TByteBuffer.java does not allow passing custom TConfiguration into constructor
https://github.com/apache/thrift/blob/66aac4465926404c2bb0c450e80fac2c2824c04c/lib/java/src/main/java/org/apache/thrift/transport/TByteBuffer.java#L18-L22 
Default TConfiguration limit message size is 100MB maximum. TByteBuffer initialization will fail with "MaxMessageSize reached" error for ByteBuffer longer than 100MB.
```
org.apache.thrift.transport.TTransportException: MaxMessageSize reached
at org.apache.thrift.transport.TEndpointTransport.resetConsumedMessageSize(TEndpointTransport.java:58)
at org.apache.thrift.transport.TEndpointTransport.updateKnownMessageSize(TEndpointTransport.java:71)
at org.apache.thrift.transport.TByteBuffer.<init>(TByteBuffer.java:24) 
```
This PR adds one more …
> THRIFT-5696: Allow custom TConfiguration for TByteBuffer.java

- .github/workflows/build.yml
- build/docker/old/ubuntu-disco/Dockerfile
- build/docker/old/ubuntu-xenial/Dockerfile
- build/docker/ubuntu-bionic/Dockerfile
- build/docker/ubuntu-focal/Dockerfile
- build/docker/ubuntu-jammy/Dockerfile
- doc/install/README.md
- doc/install/debian.md
- lib/java/README.md
- lib/java/build.gradle
- lib/java/gradle/sourceConfiguration.gradle
- lib/java/gradle/unitTests.gradle
- upgrade gradle to version 8
- ~upgrade toolchain java version to 19~
- upgrade shadow plugin due to incompatible gradle dependency
note this does not change built java library version which is pinned to 11
> THRIFT-5699: java lib and build tool chain: gradle 8.0.2

- .github/workflows/build.yml
- lib/py/src/server/TNonblockingServer.py
- lib/py/src/server/TServer.py
- lib/py/test/_import_local_thrift.py
- lib/py/test/test_sslsocket.py
> THRIFT-5564: add GitHub action for python 2.x and 3.x

- .github/dependabot.yml
To keep up to date with the latest dependencies
> THRIFT-5701: Add dependabot

- lib/java/gradle.properties
- lib/java/gradle/environment.gradle
Migrate to JakartaEE 8 dependencies which use the same namespace as the JavaEE 8.
> Migration to JakartaEE 8

- compiler/cpp/src/thrift/generate/t_java_generator.cc
- compiler/cpp/src/thrift/generate/t_oop_generator.h
- lib/java/gradle/generateTestThrift.gradle
- lib/java/src/test/java/org/apache/thrift/TestDefinitionOrder.java
- lib/java/src/test/resources/JavaDefinitionOrderA.thrift
- lib/java/src/test/resources/JavaDefinitionOrderB.thrift
Client: java
This PR is a follow-up to #2619, and applies the same change to all other types. This way, the generated field meta data is the same for all types, regardless of the order of definitions in the `.thrift` file.
The main motivation for this PR was to extend the change in the previous PR to enums. Then in order to keep the behavior consistent across all types, I applied it to other types. I've extended the tests to cover all cases.
However, there is one behavioral change when it comes to typedefs. This PR and #2619 use `get_true_type()`, which means that whenever the field definition uses a typedef'd struct or enum (for example `typedef MyType MyTypedef`), the generated metadata will not use `FieldValueMetaData(..., "MyTypedef")`, but `FieldValueMetaData(..., MyType.class)` …
> THRIFT-4086: Use true type when generating field meta data

- lib/go/thrift/zlib_transport.go
There is a bad name in the NewTZlibTransportFactoryWithFactory function comment.
Found here: https://github.com/open-telemetry/opentelemetry-go/pull/4020
> Fix NewTZlibTransportFactoryWithFactory comment

- compiler/cpp/src/thrift/generate/t_java_generator.cc
The `FutureClient` should extend the parent service `FutureClient` because the `FutureIface` does that too. Without this change the `FutureClient` will get a compilation error that does not implement all the methods.
> THRIFT-5711: Fix FutureClient implementation when service extends from another service

- lib/cpp/src/thrift/TToString.h
Currently, the `to_string()` overloads in `TToString.h` call the `std::locale` constructor for every single call. Creating locales is surprisingly expensive. We have an application where we - especially during tests - write large amounts of Thrift dumps to disk, and is this application we currently spend around 17% of total CPU time in std::locale's constructor (building with MSVC, in a Release build - other compilers might optimize this away?). With this change, it's basically down to zero.
Since we always create the exact same locale anyways, using a `const static` one does not hurt.
> THRIFT-5709: Drastically improve to_string() performance.

- lib/swift/README.md
- lib/swift/Sources/TBase64Utils.swift
- lib/swift/Sources/TJSONProtocol.swift
- lib/swift/Tests/ThriftTests/TJSONProtocolTests.swift
The code contains the changes required to support TJSONProtocol in the Thrift-Swift. The codes are ported from C#.NET Thrift official library
Add support TJSONProtocol via implementing it.
Jira Ticket: https://issues.apache.org/jira/browse/THRIFT-5714
- [x ] Did you squash your changes to a single commit?  (not required, but preferred)
- [ x] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
> THRIFT-5714 add TJSONProtocol support for swift

- lib/cpp/src/thrift/transport/TBufferTransports.cpp
- lib/cpp/test/TMemoryBufferTest.cpp
This fixes the overflow in `TMemoryBuffer::ensureCanWrite()` when the current usage plus the length of new content exceeds the max of uint32_t (e.g. 4GB). The buggy code is
```cpp
const uint32_t current_used = bufferSize_ - avail;
const uint32_t required_buffer_size = len + current_used;
if (required_buffer_size > maxBufferSize_) {
throw TTransportException(...)
}
```
`len + current_used` could overflow in `uint32_t`, which results in not rejecting the write, i.e. not throwing TTransportException. The follow-up write on this TMemoryBuffer will write to invalid memory address and leads to a crash (e.g. [IMPALA-12223](https://issues.apache.org/jira/browse/IMPALA-12223))
We should define `current_used` as `uint64_t` so the result of the expression is also `uint64_t`. Changed the type of …
> THRIFT-5716: lib: cpp: Fix crash in TMemoryBuffer due to uint32_t overflow

- .github/workflows/build.yml
- lib/java/src/main/java/org/apache/thrift/protocol/TBinaryProtocol.java
- lib/java/src/main/java/org/apache/thrift/protocol/TCompactProtocol.java
- lib/java/src/main/java/org/apache/thrift/server/TThreadedSelectorServer.java
- lib/java/src/main/java/org/apache/thrift/transport/TIOStreamTransport.java
Although we haven't removed py2 support yet, it's no longer available in github actions so it's been consistently failing in recent github action runs.
Also add `fail-fast: false` to all matrices in github actions.
> Remove py2 from github actions

- lib/java/gradle/publishing.gradle
The [libthrift-0.17.0.pom](https://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.17.0/libthrift-0.17.0.pom) file downloaded from Maven Central does not have any `<dependencies>` section.
That happened due to the explicit listing of the artifacts in the publishing block
```gradle
publishing {
publications {
mavenJava(MavenPublication) {
artifactId = "libthrift"
// explicitly set 3 jars because calling "from components.java" will include shadow jar which isn't what we want
artifact jar
artifact sourcesJar
artifact javadocJar
```
Newer versions of `com.github.johnrengelman.shadow` include shadow jar in publishing so I used workaround from https://github.com/johnrengelman/shadow/issues/651 to skip it
extra info https://docs.gradle.org/current/userguide/publishing_customization.html …
> THRIFT-5671: return dependencies to POM

- compiler/cpp/src/thrift/generate/t_py_generator.cc
- test/py/explicit_module/EnumSerializationTest.py
- test/py/explicit_module/runtest.sh
- test/py/explicit_module/test5.thrift
When serializing and deserializing Enums for Structs, the current code expects Enum member variables to be a string instead of an Enum. What this means is that the thrift file shows that an Enum is passed in the struct, when actually a string is passed in. This is very confusing can arbitrarily lead to KeyError in the deserialization logic.
However, changing this behavior is potentially breaking. To avoid breaking existing users, check if the type is an Enum when setting the member variable and convert the type to an Enum if it is a string. This allows the actual type to be an Enum and simplifies the serialization/deserialization logic to use Enums instead of converting strings.
Given a thrift file like the following:
```python
enum TestEnum {
TestEnum0 = 0,
TestEnum1 = 1,
}
struct …
```
> Convert string types to Enums in Struct py:enum gen code

- lib/php/lib/Exception/TException.php
- lib/php/src/Thrift.php
In PHP 8.1 when creating new Exception with null message you will receive warning
E_DEPRECATED: Exception::__construct(): Passing null to parameter #1 ($message) of type string is deprecated
> THRIFT-5723 Php8.1 fix warnings

- compiler/cpp/src/thrift/generate/t_py_generator.cc
- test/py/TestClient.py
In Python 3.11 exceptions generated by the compiler can't be used with a
context manager because they are immutable. As of Python 3.11
`contextlib.contextmanager` sets `exc.__traceback__` in the event that
the code in the context manager errors.
As of Thrift v0.18.1 exceptions are generated as immutable by default.
See [PR#1835](https://github.com/apache/thrift/pull/1835) for more information about why exceptions were made
immutable by default.
This change makes all non-Thrift fields mutable when slots is used  without dynamic. This
will allow exceptions to be re-raised properly by the contextmanager in
Python 3.11.
With tutorial code generated from `head` this raises a `TypeError` not 
an `InvalidOperation`:
```
import contextlib
import sys
sys.path.append('gen-py')
from tutorial.ttypes …
```
> THRIFT-5715: Python non-user defined fields mutable with slots

- lib/kotlin/build.gradle.kts
- lib/kotlin/cross-test-client/build.gradle.kts
- lib/kotlin/cross-test-client/src/main/kotlin/org/apache/thrift/test/TestClient.kt
- lib/kotlin/cross-test-server/src/main/kotlin/org/apache/thrift/test/TestServer.kt
- lib/kotlin/settings.gradle.kts
reformat kotlin files to fix CI as the master branch is broken by it.
- changes made by using `ktfmtFormat`
- fixes #2827
> [CI] reformat kotlin files to fix CI as the master branch is broken by it

- lib/rs/src/server/threaded.rs
Resolve TFramedWriteTransport write message size 4 bytes causing approximately 40 milliseconds delay.
> Setting TCP_ NODELAY option for rust server

- lib/netstd/Benchmarks/Thrift.Benchmarks/Thrift.Benchmarks.csproj
- lib/netstd/Tests/Thrift.IntegrationTests/Thrift.IntegrationTests.csproj
- lib/netstd/Tests/Thrift.PublicInterfaces.Compile.Tests/Thrift.PublicInterfaces.Compile.Tests.csproj
- lib/netstd/Tests/Thrift.Tests/Thrift.Tests.csproj
- lib/netstd/Thrift/Protocol/TJSONProtocol.cs
- lib/netstd/Thrift/Thrift.csproj
- lib/netstd/Thrift/Transport/Client/THttpTransport.cs
- lib/netstd/Thrift/Transport/Client/TNamedPipeTransport.cs
- lib/netstd/Thrift/Transport/Client/TStreamTransport.cs
- lib/netstd/Thrift/Transport/Server/TNamedPipeServerTransport.cs
- test/netstd/Client/Client.csproj
- test/netstd/Server/Server.csproj
- tutorial/netstd/Interfaces/Interfaces.csproj
- tutorial/netstd/Server/Server.csproj
> THRIFT-5726 package upgrades and consolidation/improvement of build targets checks

- .github/workflows/build.yml
- LANGUAGES.md
- go.mod
- lib/go/test/fuzz/go.mod
- lib/go/test/go.mod
- test/go/go.mod
Getting the PR ready to be merged once go 1.21 releases.
> Update supported go versions to 1.20 and 1.21

- lib/kotlin/cross-test-client/build.gradle.kts
- lib/kotlin/cross-test-server/build.gradle.kts
fix kotlin cross test by downgrading to java 8
> fix kotlin cross test by downgrading to java 8

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- lib/go/README.md
- lib/go/test/tests/server_connectivity_check_test.go
- lib/go/thrift/simple_server.go
Also add a test to verify the behavior.
The test helped me to found a bug in TSimpleServer that didn't handle the ErrAbandonRequest case correctly, so fix the bug as well.
client: go
> THRIFT-5731: Handle ErrAbandonRequest automatically

- lib/java/src/main/java/org/apache/thrift/protocol/TType.java
It should be 16 not 17 according to the spec.
Currently ENUM holds 16, it's not in TBinaryProtocol spec and seems to be a Java implementation detail somehow got mixed inside TType, move that to ~255~ -1 (java's byte is signed) for now. Someone more familiar with Java can probably remove it from TType completely in the future.
client: java
> THRIFT-5653: Fix Java UUID typeid

- compiler/cpp/src/thrift/generate/t_java_generator.cc
Building 0.19.0 on Mac OS Ventura 13.6 (`Darwin J59JPHTWW7 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000 arm64`) yields this error:
```
src/thrift/generate/t_java_generator.cc:5759:9: error: variable 'j' set but not used [-Werror,-Wunused-but-set-variable]
int j = 0;
^
1 error generated.
make[1]: *** [src/thrift/generate/thrift-t_java_generator.o] Error 1
```
It's a pretty easy excision.
```
% gcc --version
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
With this change only, the compiler `make` succeeds.
```
% cd compiler/cpp
% make -j3 >&/dev/null
% ./thrift --version
Thrift version 0.19.0
% file thrift …
```
> THRIFT-5738: Unused variable fails mac builds

- compiler/cpp/src/thrift/generate/t_js_generator.cc
This fixes the following compiler error.
t_js_generator.cc:48:14: error: 'int64_t' does not name a type
48 | static const int64_t max_safe_integer = 0x1fffffffffffff;
|              ^~~~~~~
t_js_generator.cc:50:14: error: 'int64_t' does not name a type
50 | static const int64_t min_safe_integer = -max_safe_integer;
|              ^~~~~~~
> Fix building with gcc 13

- composer.json
This change excludes different languages from composer package, that will results in decrease of package size:
- packed .zip: from 4.8M to 0.2M (less traffic, faster installs)
- unpacked (in vendor directory): 22M->0.2M (smaller application dependencies, faster deploys)
What will be excluded from final package:
- other languages
- helpful repository files (.gitignore/.editorconfig/etc)
- compiler
- tests
- tutorial
- PHP sources/tests
What will final package contain of:
- README/LICENSE/CHANGES
- PHP library itself
- composer.json
There is no code change so [skip ci]
> fix(php): exclude most part of the repo for php package

- lib/cpp/test/SecurityFromBufferTest.cpp
- lib/cpp/test/SecurityTest.cpp
This commit fixes the current build problem on MSVC (see i.e. https://ci.appveyor.com/project/ApacheSoftwareFoundation/thrift/builds/48238772/job/cyh9vdh0xsiadd01)
```
C:\projects\thrift\lib\cpp\test\SecurityFromBufferTest.cpp(202): error C2065: 'OPENSSL_VERSION_MAJOR': undeclared identifier [C:\projects\build\MSVC2017\x64\lib\cpp\test\SecurityFromBufferTest.vcxproj]
C:\projects\thrift\lib\cpp\test\SecurityTest.cpp(224): error C2065: 'OPENSSL_VERSION_MAJOR': undeclared identifier 
```
> lib/cpp/test/Security*Test.cpp: Fix the check for OpenSSL version macro

- compiler/cpp/src/thrift/generate/t_rs_generator.cc
- lib/rs/Cargo.toml
- lib/rs/src/errors.rs
- lib/rs/src/protocol/binary.rs
- lib/rs/src/protocol/compact.rs
- lib/rs/src/protocol/mod.rs
- lib/rs/src/protocol/multiplexed.rs
- lib/rs/src/protocol/stored.rs
- lib/rs/test/Cargo.toml
- lib/rs/test/thrifts/Base_One.thrift
- test/crossrunner/util.py
- test/rs/Cargo.toml
- test/rs/Makefile.am
- test/rs/src/bin/test_client.rs
- test/rs/src/bin/test_server.rs
> THRIFT-5648: add uuid support in rust

- build/cmake/GenerateConfigModule.cmake
When libevent is not used, the script `FindLibevent.cmake` may be confusing to downstream projects. Do not install it.
> Do not install `FindLibevent.cmake` when libevent is disabled

- .github/workflows/build.yml
- build/docker/old/ubuntu-disco/Dockerfile
- build/docker/old/ubuntu-xenial/Dockerfile
- build/docker/ubuntu-bionic/Dockerfile
- build/docker/ubuntu-focal/Dockerfile
- build/docker/ubuntu-jammy/Dockerfile
- doc/install/README.md
- doc/install/debian.md
- lib/java/README.md
> [ci] use gradle 8.4 (trivial build env change)

- lib/cpp/src/thrift/transport/TSocket.cpp
We've seen a strange timeout error message like this:
```
TSocket::read() THRIFT_EAGAIN (timed out) after %f ms: Unknown error 30000
```
The log comes from this line:
```cpp
GlobalOutput.perror("TSocket::read() THRIFT_EAGAIN (timed out) after %f ms", recvTimeout_);
```
The second argument of GlobalOutput.perror() is an errno. We should not use `recvTimeout_` on it:
https://github.com/apache/thrift/blob/a2a1f535813511aa274ed328b2318cb2beb7bb08/lib/cpp/src/thrift/TOutput.h#L40
```cpp
class TOutput {
...
void perror(const char* message, int errno_copy);  // <-- The second arg is errno
...
void printf(const char* message, ...);
};
THRIFT_EXPORT extern TOutput GlobalOutput;
```
The implementation of perror():
```cpp
void TOutput::perror(const char* message, int errno_copy) {
std::string out = …
```
> THRIFT-5670: lib: cpp: Fix wrong timeout error message

- aclocal/ax_thrift_internal.m4
- configure.ac
- contrib/fb303/aclocal/ax_thrift_internal.m4
> THRIFT-5747 warning: The macro `AC_HELP_STRING' is obsolete. You should run autoupdate.

- lib/cpp/Makefile.am
This reverts commit 779deabf0e1fdefe4f6340546181ac9d81fcf670.
> Revert "lib: cpp: automake: ship thrift/numeric_cast.h"

- lib/py/test/test_sslsocket.py
Add a dummy test in test_sslsocket.py to workaround an issue in Python
3.12.
> Fix github actions for python3 tests

- .github/workflows/build.yml
This is the combination of https://github.com/apache/thrift/pull/2910 & https://github.com/apache/thrift/pull/2912. It looks like these 2 changes need to be done together, doing them individually will break CI.
> Bump upload/download-artifacts from v3 to v4

- .github/workflows/build.yml
This reverts commit 85400668007ea1938c250e01a7c4763ecfef3c71.
https://github.com/actions/upload-artifact/issues/478 will impact us.
> Revert "Bump upload/download-artifacts from v3 to v4"

- lib/php/lib/Protocol/TJSONProtocol.php
- lib/php/lib/StringFunc/Core.php
- lib/php/lib/StringFunc/Mbstring.php
- lib/php/lib/TMultiplexedProcessor.php
- lib/php/src/TStringUtils.php
PHP 8.1 has deprecated passing null values to non-nullable internal function parameters:
https://wiki.php.net/rfc/deprecate_null_to_scalar_internal_arg
This can lead to deprecation warnings and potential errors in future versions.
Example of a deprecation warning:
`PHP Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in Thrift/StringFunc/Core.php on line 38`
The changes in this PR will not affect previous versions of PHP, meaning these changes are backwards compatible.
> THRIFT-5754: Fix PHP 8.1 deprecates passing null to non-nullable internal function parameters

- compiler/cpp/src/thrift/generate/t_php_generator.cc
In PHP 8.1 a "mixed" return type was added to the "JsonSerializable::jsonSerialize()" method.
This triggers a deprecation warning for generated PHP classes:
`Return type of TestClass::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ...`
This will not affect previous versions of PHP, meaning these changes are backwards compatible.
> THRIFT-5753: PHP 8.1 deprecated warning about return type in jsonSerialize functions

- compiler/cpp/src/thrift/generate/t_delphi_generator.cc
Client: delphi
This patch is just the deprecation notice, feature will be removed in 0.21.0
> THRIFT-5750 deprecate "ansistr_binary_" option

- compiler/cpp/src/thrift/generate/t_js_generator.cc
The generated typescript client includes type definitions like this:
```typescript
addProfile(profile: types_ttypes.Profile): Promise<types_ttypes.Profile>;
addProfile(profile: types_ttypes.Profile, callback?: (error: void, response: types_ttypes.Profile)=>void): void;
```
This is ambigous as the second definition overrides the first one since callback is optional. And is in fact not how the client works.
The correct types should be:
```typescript
addProfile(profile: types_ttypes.Profile): Promise<types_ttypes.Profile>;
addProfile(profile: types_ttypes.Profile, callback: (error: void, response: types_ttypes.Profile)=>void): void;
```
My current workaround is to run this nasty sed, so it would be nice to get this fix in. 😄 
```bash
find "$out_dir" -name '*.d.ts' -type f -exec sed -i '' -e …
```
> Fix ambigous typescript definitions

- .github/workflows/build.yml
- LANGUAGES.md
- go.mod
- lib/go/test/fuzz/go.mod
- lib/go/test/go.mod
- lib/go/thrift/debug_protocol.go
- lib/go/thrift/logger.go
- lib/go/thrift/simple_server.go
- test/go/go.mod
- test/go/go.sum
> THRIFT-5744: Switch to slog for go library

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- lib/go/test/tests/slog_tstruct_wrapper_test.go
- lib/go/thrift/slog.go
- lib/go/thrift/slog_test.go
Client: go
Implement slog.LogValuer for all TStruct and TException generated by the compiler for go code. Also add SlogTStructWrapper in the library so we don't have to repeat it in the compiler generated go code.
> THRIFT-5745: Implement slog.LogValuer on go TStructs

- .github/workflows/pypi.yml
This is tested with https://github.com/apache/thrift/pull/2927, which published to https://test.pypi.org/project/thrift-test/. I tested locally with:
(venv) fishy@penguin:~/work/test$ pip install -i https://test.pypi.org/simple/ thrift-test
Looking in indexes: https://test.pypi.org/simple/
Collecting thrift-test
Downloading https://test-files.pythonhosted.org/packages/e6/02/5885ea1406f560d0a23351f68acc2892d7f6495b16bfc2eeee8de4649777/thrift-test-0.21.0.tar.gz (62 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 1.4 MB/s eta 0:00:00
Preparing metadata (setup.py) ... done
Collecting six>=1.7.2 (from thrift-test)
Downloading https://test-files.pythonhosted.org/packages/b3/b2/238e2590826bfdd113244a40d9d3eb26918bd798fc187e2360a8367068db/six-1.10.0.tar.gz (29 kB)
Preparing metadata …
> THRIFT-5688: Add PyPI publishing github actions

- .github/workflows/build.yml
- .gitignore
- build/docker/ubuntu-bionic/Dockerfile
- composer.json
- lib/php/README.apache.md
- lib/php/phpunit.xml
- lib/php/test/Fixtures/Fixtures.php
- lib/php/test/Fixtures/TJSONProtocolFixtures.php
- lib/php/test/Fixtures/TSimpleJSONProtocolFixtures.php
- lib/php/test/Makefile.am
- lib/php/test/Resources/ThriftTest.thrift
- lib/php/test/Unit/BaseValidatorTest.php
- lib/php/test/Unit/BinarySerializerTest.php
- lib/php/test/Unit/JsonSerializeTest.php
- lib/php/test/Unit/TJSONProtocolTest.php
- lib/php/test/Unit/TSimpleJSONProtocolTest.php
- lib/php/test/Unit/ValidatorTest.php
- lib/php/test/Unit/ValidatorTestOop.php
Before updating minimum version of php to 7.4 or 8.0 we should start running php tests on every pull request.
In this pull request i also maid such things:
- add xdebug to Docker instance ubuntu-bionic
- combine all php tests in one folder and add configuration file for running them
- add to github action running of tests for php versions 5.6 - 8.3
- for versions php greater than 7.1 in github action using dirty hack with update code of php tests, due to the BC in php
- modify README for better view
Next steps:
- increase code coverage for php code
- update min version of php to 7.4
- update generation of php code for 7.4
Also it will be great to update code style to PSR-12 and add code style check to github actions
> THRIFT-5756 Run php tests in github actions

- .github/workflows/build.yml
- composer.json
- doc/install/README.md
- lib/php/README.md
- lib/php/test/Unit/BinarySerializerTest.php
- lib/php/test/Unit/JsonSerializeTest.php
- lib/php/test/Unit/TJSONProtocolTest.php
- lib/php/test/Unit/TSimpleJSONProtocolTest.php
- lib/php/test/Unit/ValidatorTest.php
- lib/php/test/Unit/ValidatorTestOop.php
Update minimal version of php to 7.1
I know that currently 8.* is main version, but current code has to much dependencies on version 5, so let's move step by step.
> THRIFT-5760 Update minimal version of php

- .github/workflows/build.yml
- lib/php/lib/Base/TBase.php
- lib/php/lib/Exception/TException.php
- lib/php/src/Thrift.php
- lib/php/test/Unit/Lib/Exception/TExceptionTest.php
In php 8.2 dynamic properties will generate a deprecation
https://www.php.net/releases/8.2/en.php#deprecate_dynamic_properties
In Tbase and TException dynamic properties is used.
> THRIFT-5758 PHP 8.2 Deprecate dynamic properties

- lib/py/src/protocol/TBinaryProtocol.py
- lib/py/test/thrift_TBinaryProtocol.py
In the function `transport.TTransport.readAll`, when the `sz<0`, the type of name is `str`.
But when the `sz>0`, the type of name is `bytes`.
They should return the same types.
I use the `binary_to_str` to convert the type of `name`
I write a unittest method `test_TBinaryProtocol_no_strict_write_read` to test my changes. It passed.
> Fix: fix python readMessageBegin return value type error

- lib/json/schema.json
Fix the test to expect `typeId` and `class` inside the `type` object instead of on the root level.
This is the way the compiler generates is.
Old output:
```json
"constants": [
{
"name": "myNumberz",
"typeId": "enum",
"type": {
"typeId": "enum",
"class": "Numberz"
},
"value": 1
}
],
```
New output:
```
"constants": [
{
"name": "myNumberz",
"typeId": "enum",
"class": "Numberz",
"value": 1
}
],
```
> THRIFT-5761 Lib/json tests fail

- compiler/cpp/src/thrift/generate/t_java_generator.cc
- lib/java/src/main/java/org/apache/thrift/AsyncProcessFunction.java
- lib/java/src/main/java/org/apache/thrift/ProcessFunction.java
- lib/java/src/main/java/org/apache/thrift/TBaseAsyncProcessor.java
- lib/java/src/main/java/org/apache/thrift/TBaseProcessor.java
- lib/java/src/main/java/org/apache/thrift/server/TSaslNonblockingServer.java
Some libraries want to bypass the TServer class and handle the full service startup manually. For example when building a service that hosts multiple thrift services where the IFace type is unknown when handling a request.
For example when you host multiple services on top of netty and through an HTTP path you want to route to the correct thrift service. In this situation you treat can treat an IFace as an Object and use the `getProcessMapView()` method to parse a byte array into a thrift message and pass let the `AsyncProcessFunction` handle the invocation.
To return a correct thrift response it's necessary to write the `{service_name}_result` that contains the response args. While it is possible to get an incoming args object from the (Async)ProcessFunction its unfortunately not …
> THRIFT-5762 Expose service result objects in Java

- lib/nodejs/lib/thrift/framed_transport.js
- lib/nodejs/test/header.test.js
- lib/nodejs/test/testAll.sh
Fixes https://issues.apache.org/jira/browse/THRIFT-5769.
Replaces `residual` `Array` with `Buffer` to fix crash caused by large messages.
> THRIFT-5769: fix invalid size error on large messages

- lib/go/test/Makefile.am
- lib/go/test/StringParseAllocationTest.thrift
- lib/go/test/tests/string_parse_allocation_test.go
- lib/go/thrift/simple_json_protocol.go
The code in `ParseQuotedStringBody()` was recursing in our application every time there was an escaped quote in strings  and generated a new string buffer for every recursive call. This was a real issue for escaped JSON in our application in particular.
So this pull requests moves that logic into a loop, and uses a string builder to avoid re-allocating buffers for every iteration.
We observed an ~40x decrease in p99 latency from 2 seconds -> 50 milliseconds on our servers when implementing this change. So it is a substantial performance improvement for this particular use case.
> THRIFT-5767: Go Simple JSON Protocol re-allocates memory for every escaped quote

- configure.ac
The Kotlin autoconfig script was missing a `test` causing it to try and execute `x/usr/local/bin/gradle` instead of test for its existence. This resulted in the following error:
```
./configure: line 15049: x/usr/local/bin/gradle: No such file or directory
```
Adding `test` results in the configuration succeeding. Configure output now:
```
thrift 0.21.0
Building C (GLib) Library .... : yes
Building C++ Library ......... : yes
Building Common Lisp Library.. : yes
Building D Library ........... : yes
Building Dart Library ........ : yes
Building .NET Standard Library : yes
Building Erlang Library ...... : yes
Building Go Library .......... : yes
Building Haxe Library ........ : yes
Building Java Library ........ : yes
Building Kotlin Library ...... : yes
Building Lua Library ......... : yes …
```
> THRIFT-5768 Add missing test in configure.ac for kotlin

- compiler/cpp/src/thrift/generate/t_kotlin_generator.cc
- lib/java/src/main/java/org/apache/thrift/ProcessFunction.java
- lib/java/src/main/java/org/apache/thrift/TBaseAsyncProcessor.java
- lib/java/src/main/java/org/apache/thrift/TBaseProcessor.java
Run `gradlew :spotlessApply` to apply the correct coding style.
> THRIFT-5762 Fix spotless errors

- compiler/cpp/src/thrift/generate/t_netstd_generator.cc
- compiler/cpp/src/thrift/generate/t_netstd_generator.h
> THRIFT-5781 implement full deprecation support

- compiler/cpp/src/thrift/generate/t_delphi_generator.cc
- compiler/cpp/src/thrift/generate/t_netstd_generator.cc
Client: Delphi
plus a minor netstd fix
> THRIFT-5782 implement full deprecation support

- lib/go/thrift/rich_transport.go
Client: go
TBinaryProtocol and TCompactProtocol (and as an extension,
THeaderProtocol) use TRichTransport's ReadByte/WriteByte functions a lot
under the hood, and in some extreme cases those ReadByte/WriteByte calls
can generate a lot of allocation syscalls for the byte they used.
Use a resource pool to help reduce the allocations.
> go: Define a bytePool for TRichTransport

- lib/go/thrift/rich_transport.go
This reverts commit 344498b67f42af38118cc250b0b1ec212f09d927.
In our extreme case this actually made things worse. On 30s cpu profiles, although mallocgc reduced from 27.13s to 26.30s, the byte pool itself costed 11.9s. Looking at writeByte and readByte, writeByte increased from 3.69s to 5.89s, and readByte increased from 11.36s to 16.09s.
> Revert "go: Define a bytePool for TRichTransport"

- lib/go/thrift/header_transport.go
- lib/go/thrift/simple_json_protocol.go
Client: go
Fix 2 instances we are using == to check on error but should have used errors.Is instead.
> go: Use errors.Is over ==

- lib/go/test/tests/header_zlib_test.go
- lib/go/thrift/configuration.go
- lib/go/thrift/header_protocol.go
- lib/go/thrift/header_protocol_test.go
- lib/go/thrift/header_transport.go
Client: go
While I'm here, also auto add compression transforms read (currently only zlib is supported) to writeTransforms so that a server will auto use the same compression on the responses as the client chose to use in the requests.
> THRIFT-5784: Add THeaderTransforms to TConfiguration

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- compiler/cpp/src/thrift/generate/t_go_generator.h
This is a "trivial" change for go compiler to always use the combination of indent_up, indent_down, and indent, over manual indentation (by adding 2 spaces at the beginning of the string). Also change go compiler's indent_str to tab over 2 spaces.
While I'm here, also made a few minor tweaks on generated go code.
> go: Proper indent in compiler

- lib/rb/thrift.gemspec
This change simply removes the deprecated `has_rdoc` usage from the gemspec. Due to this deprecated usage end users will see the following message in their console at times. Would be ideal if we can remove this noise.
```console
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed in Rubygems 4
Gem::Specification#has_rdoc= called from /Users/larouxn/.gem/ruby/ruby-3.3.0/bundler/gems/thrift-b109bdd1a4aa/lib/rb/thrift.gemspec:15.
```
Looks like it has been deprecated for at least 5 years based on tickets raised about this back in ~2018.
> Remove deprecated has_rdoc from gemspec

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- compiler/cpp/src/thrift/generate/t_go_generator.h
Client: go
This should got most of them. Also fixed an indentation bug from 4930ca.
> THRIFT-5786: Full deprecation support in go

- compiler/cpp/src/thrift/generate/t_go_generator.cc
This fixes a small case I missed in 4930caca.
Before:
func NewFoo() *Foo {
return &Foo{
DefDef: 10,
DefOpt: 11,
}
}
After:
func NewFoo() *Foo {
return &Foo{
DefDef: 10,
DefOpt: 11,
}
}
> go: Fix indentation in compiler

- lib/cpp/src/thrift/server/TNonblockingServer.cpp
- lib/cpp/src/thrift/server/TNonblockingServer.h
When the number of client connection exceeds 100000, especially when it reaches 500000, there will be serious performance issues if thousands of level links are constantly created and deleted.
> optimizing performance issues under large-scale connection

- lib/py/src/transport/TSocket.py
- lib/py/test/test_socket.py
- lib/py/test/test_sslsocket.py
When the Python client times out while reading content from the server, the exception thrown is not "read timeout," but rather "unexpected exception."
I try to make a timeout error on my pc, it only contains the error string.
```
Python 3.11.1 (main, Jan  5 2023, 14:25:08) [GCC 11.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.13.2 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import socket
...: from urllib.request import urlopen
...:
...: url = 'http://httpbin.org/get'
...:
...: socket.setdefaulttimeout(0.01)
...: try:
...:     urlopen(url)
...: except Exception as e:
...:     err1 = e.reason
...:
...:
In [2]: type(err1)
Out[2]: TimeoutError
In [3]: err1.args
Out[3]: ('timed out',)
```
And my system is ubuntu 22.04
```
ø> uname -a
Linux …
```
> THRIFT-5777: python fix mismatched timeout exceptions.

- lib/py/Makefile.am
Use pip install instead of deprecated python setup.py install command.
Egg formats will be deprecated in pip v24.3 (planned for October). Users are required to use `pip install` instead.
For reference : https://github.com/pypa/pip/issues/12330
> Use pip install instead of deprecated python setup.py install command

- lib/cpp/src/thrift/TNonCopyable.h
- lib/cpp/src/thrift/async/TConcurrentClientSyncInfo.h
- lib/cpp/src/thrift/async/TEvhttpServer.h
- lib/cpp/src/thrift/transport/TFileTransport.h
- lib/cpp/src/thrift/windows/OverlappedSubmissionThread.h
- lib/cpp/src/thrift/windows/Sync.h
- lib/cpp/src/thrift/windows/TWinsockSingleton.h
Commit 042580f53441efe1bc5c80c89351fcb30740659e removed the `virtual` keyword from the declaration of `~TConnectedClient()`.
While mostly benign, it does cause a warning in some versions  of GCC (non-virtual destructors can result in undefined behaviour), which can throw off CI sometimes when building with `-Werror`.
> THRIFT-5678: lib: cpp: TConnectedClient: warning due to non-virtual dtor

- compiler/cpp/src/thrift/generate/t_netstd_generator.cc
- lib/netstd/Tests/Thrift.PublicInterfaces.Compile.Tests/Thrift.PublicInterfaces.Compile.Tests.csproj
- lib/netstd/Tests/Thrift.PublicInterfaces.Compile.Tests/Thrift5795.thrift
> THRIFT-5795 namespace not properly escaped

- build/appveyor/MSVC-appveyor-full.bat
Current build seem to fail on downloading flex-SDK. Use new location according to https://stackoverflow.com/a/21269691/19761878
> CI/appveyor: fix download location for flex-sdk

- compiler/cpp/src/thrift/generate/t_netstd_generator.cc
> THRIFT-5797 HashSet() CTOR takes no argument for net < 5

- lib/py/src/transport/TSSLSocket.py
- lib/py/src/transport/TSocket.py
- lib/py/src/transport/sslcompat.py
Need for Python 3.13
https://github.com/python/cpython/issues/105376: Remove undocumented and untested Logger.warn() and LoggerAdapter.warn() methods and logging.warn() function.
> Switch from `logger.warn` to `logger.warning`

- .github/workflows/build.yml
- .github/workflows/cmake.yml
upgrade artifact-actions from v3 to v4
* v3 uses Node.js 16, which is deprecated and causes warning messages
* < v4 will get deprecated in Nov 2024 (https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)
switch to ubuntu-22.04 by default
* Ubuntu 20.04 will go EoL in Aril 2025
* build the compiler on ubuntu-24.04, ubuntu-22.04 and ubuntu-20.04
> CI bump versions of GitHubActions and Ubuntu

- lib/java/src/main/java/org/apache/thrift/server/AbstractNonblockingServer.java
- lib/java/src/main/java/org/apache/thrift/server/TThreadedSelectorServer.java
Adds validity checks before trying to use the `SelectionKey` in `AbstractNonBlockingServer.FrameBuffer`.
> THRIFT-4847: CancelledKeyException causes TThreadedSelectorServer to fail

- lib/cpp/test/SecurityFromBufferTest.cpp
- lib/cpp/test/SecurityTest.cpp
This PR fixes the Security tests to build on a clean install of ubuntu
20.04 and ubuntu 22.04 without modifications to the systems openssl
configuration.
* Enable TLS 1.0 and TLS 1.1 on OpenSSL 1.1 with the seclevel=0 flag
* Disable TLS 1.0 and TLS 1.1 on OpenSSL 3.0
While its technically possible to enable it on OpenSSL 3 I think because
of all the issues with these old TLS versions dropping support for it is
better.
This PR builds forth on the work done here: https://github.com/apache/thrift/pull/2811
Tested with the ubuntu 20.04 (OpenSSL 1.1) and 22.04 (OpenSSL 3.0) docker containers.
All lib/cpp tests succeed in both.
> THRIFT-5706: lib/cpp Fix the Security tests on openssl 1.1 and 3.0

- lib/java/src/main/java/org/apache/thrift/server/AbstractNonblockingServer.java
- lib/java/src/main/java/org/apache/thrift/server/TThreadedSelectorServer.java
I think this was a bug from d4503a1f0e62d38f7a12ba9748744c5490c915c4.
> Fix failed java build

- test/go/src/bin/testserver/main.go
- test/go/src/common/server.go
Client: go
This was a bug introduced by 91565d490e98306ac6797dd6ed4f72c0e8222e78 that broke go's cross-test server, but because other CI issues we didn't run cross-test so we didn't notice the issue.
> go: Fix cross test server

- .github/workflows/build.yml
There were some recent changes causing six to be installed on the `make
install` step instead of (implicitly) on the `Python setup` step before,
and the six installed on `make install` step was not available to the
next `make check` step and causing errors.
Install six on `Python setup` step explicitly instead.
> Fix python build on Github Actions

- compiler/cpp/src/thrift/generate/t_py_generator.cc
- test/py/Makefile.am
- test/py/RunClientServer.py
- test/py/TestTypes.py
- test/py/generate.cmake
Add type hinting (with native enums (IntEnum)) for python generated code
1. Squashed and rebased changes from [stale PR](https://github.com/apache/thrift/pull/2523)
2. Removed the controversial runtime type check as it goes beyond strictly annotations
3. Added type_hints as a default option to `RunClientServer.py` and `generate.cmake`. 
4. Enabled testing against thrift test suite
5. Made enum regeneration explicitly required instead of implied when this flag is provided
6. Added python tests to verify basic annotations are getting added
7. Generate a thrift_spec attribute variable declaration for all generated thrift structures and optionally type hint it if type_hints are enabled
Note: Appveyor x86 / Python 3.5 build is failing since this PR generates variable type hints (`x: int = 1`), …
> THRIFT-5139/THRIFT-4181: Python3 type hints

- lib/py/src/transport/TSocket.py
- lib/py/test/test_socket.py
> THRIFT-5813: Close the socket in TSocket.isOpen() when peek() fails

- lib/cpp/src/thrift/TToString.h
- lib/cpp/src/thrift/TUuid.h
- lib/cpp/test/CMakeLists.txt
- lib/cpp/test/Makefile.am
- lib/cpp/test/Thrift5272.cpp
- lib/cpp/test/Thrift5272.thrift
- lib/cpp/test/ThrifttReadCheckTests.cpp
This fixes [Thift5272](https://issues.apache.org/jira/browse/THRIFT-5272). Using the patch provided with the issue and adding a test for it.
There is one commit for the test, which includes related build-files (Makefile + CMake). So you can see the test is actually detecting the issue.
There is 2nd commit for the fix, this also makes the test pass.
The 3rd commit is just updating a deprecated and a missing header
If needed I can squash commits of test and fix.
> THRIFT-5272 printTo does not properly handle i8 datatypes

- compiler/cpp/src/thrift/generate/t_js_generator.cc
If a thrift struct has a member named `read`, it causes a naming collision. This change renames `read` to `thriftRead` and `write` to `thriftWrite` on generated JavaScript classes.
I reviewed the NodeJS library code to see if read or write was called directly on the generated classes:
<details>
<summary>`read` calls in NodeJS library</summary>
```
❯ rg '\.read\('
binary_protocol.js
193:    name = this.trans.read(sz);
271:  var buff = this.trans.read(8);
288:  return this.trans.read(len);
compact_protocol.js
727:  var buff = this.trans.read(8);
769:  return this.trans.read(size);
header_transport.js
280:  this.read(endOfHeaders);
```
</details>
So `.read` is only called on the transports.
<details>
<summary>write calls in NodeJS library</summary>
```
server.js
49: …
```
> Fix JS property/method collisions for fields named read/write

- build/cmake/DefineInstallationPaths.cmake
With THRIFT-5109 the LIB_INSTALL_DIR for MSVC libs chanaged from lib/ to bin/ which makes sense for shared libs but is not consistent with the usual treatment of static libs.
Install the static libs to lib/, similar to other platforms and projects.
> THRIFT-5810: install static MSVC libraries to lib/

- lib/java/README.md
- lib/java/gradle/environment.gradle
- lib/java/gradle/unitTests.gradle
- lib/kotlin/build.gradle.kts
* Specify JUnit platform explicitly
* Remove unused system property (build.test) from unit test environment that relied on a deprecated task property (destinationDir)
* Replace kotlinOptions.jvmTarget with compilerOptions replacement
* Update README to avoid incorrect specification of gradle 8.0, when other gradle 8 versions are acceptable
> Remove some gradle deprecation warnings

- lib/go/thrift/socket_aix_syscall.go
- lib/go/thrift/socket_non_aix_syscall.go
- lib/go/thrift/socket_unix_conn.go
This PR adds support for AIX by splitting the `syscall.Recvfrom()` call into AIX and non-AIX variants. This split is necessary because AIX does not have a `MSG_DONTWAIT` flag, but has an equivalent called `MSG_NONBLOCK`.
> THRIFT-5818: Add AIX support

- lib/py/src/transport/TSSLSocket.py
In python 3.12, ssl.match_hostname has been removed.
ssl.PROTOCOL_SSSLV23 has been deprecated since python 3.6.
> Make ssl work with python 3.12

- build/cmake/DefineOptions.cmake
- lib/cpp/src/thrift/transport/TSSLSocket.cpp
To use AWS-LC (a BoringSSL derivitive maintained by AWS) instead of openssl for libcrypto, a few lines needed to be patched.
> THRIFT-5821: support building against AWS-LC

- aclocal/ax_boost_base.m4
update ax_boost_base.m4 from http://www.gnu.org/software/autoconf-archive/ for adding loongarch information
about loongarch：https://docs.kernel.org/arch/loongarch/introduction.html
> add loongarch info from http://www.gnu.org/software/autoconf-archive

- .github/workflows/build.yml
- build/appveyor/MSVC-appveyor-full.bat
- build/docker/ubuntu-focal/Dockerfile
- build/docker/ubuntu-jammy/Dockerfile
- contrib/Vagrantfile
- debian/control
- lib/nodejs/examples/httpServer.py
- lib/py/setup.py
- lib/py/src/TSCons.py
- lib/py/src/protocol/TProtocol.py
- lib/py/src/server/THttpServer.py
- lib/py/src/server/TNonblockingServer.py
- lib/py/src/server/TServer.py
- lib/py/src/transport/THttpClient.py
https://wiki.debian.org/Python3-six-removal
> remove dependency on Six

- lib/php/lib/Type/TConstant.php
remove deprecated use of static callables
> THRIFT-5829 - Update TConstant.php to remove deprecated PHP code

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- lib/go/test/tests/processor_middleware_test.go
- lib/go/thrift/processor_factory.go
- lib/go/thrift/simple_server_test.go
Client: go
Provide ProcessorError as the combined error of write i/o error and original error returned by the endpoint implementation, and update compiler to use that in Process functions.
> THRIFT-5833: Add ProcessorError

- lib/cpp/test/Makefile.am
> THRIFT-5836 No rule to make target 'Thrift5272.thrift', needed by 'gen-cpp/Thrift5272_types.h'

- lib/erl/rebar.config
- lib/erl/src/thrift.app.src
Client: Erlang
Since [erlfmt](https://github.com/WhatsApp/erlfmt/releases/tag/v1.5.0) is a build dependency, and the currently used version generates build warnings with latest OTP 27, we lift its version.
Example of warnings that are fixed:
```
===> Compiling erlfmt
┌─ _build/default/plugins/erlfmt/src/erlfmt_parse.yrl:
│
96 │  node -> standalone_exprs exprs dot : {exprs, (?range_anno('$1', '$3'))#{dot => true}, '$2'}.
│                                                                        ╰── Warning: expression updates a literal
┌─ _build/default/plugins/erlfmt/src/erlfmt_parse.yrl:
│
149 │      {record, (?range_anno('$1', '$3'))#{macro_record => true}, '$1', []}.
│                                        ╰── Warning: expression updates a literal
...
```
Includes a formatting …
> Fix build warnings for Erlang/OTP 27

- compiler/cpp/src/thrift/generate/t_java_generator.cc
C-style array declarations (e.g. `Foo foos[]`) is discouraged by the JLS. Java style (e.g., `Foo[] foos`) should be preferred.
> Update generated array style

- lib/cpp/src/thrift/concurrency/Mutex.h
Client: cpp
GCC 15 (not released yet) requires `#include <cstdint>` for `int64_t` but `lib/cpp/src/thrift/concurrency/Mutex.h` doesn't have it. So we can't build Thrift with GCC 15:
[80/359] Building CXX object lib/cpp/CMakeFiles/thrift.dir/src/thrift/transport/TSSLServerSocket.cpp.o
FAILED: lib/cpp/CMakeFiles/thrift.dir/src/thrift/transport/TSSLServerSocket.cpp.o
/bin/g++-15 -DBOOST_ALL_DYN_LINK -DBOOST_TEST_DYN_LINK -DTHRIFT_STATIC_DEFINE -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/kou/work/cpp/thrift.kou.build/lib/cpp -I/home/kou/work/cpp/thrift.kou/lib/cpp -I/home/kou/work/cpp/thrift.kou.build -I/home/kou/work/cpp/thrift.kou/lib/cpp/src -g -std=c++11 -MD -MT lib/cpp/CMakeFiles/thrift.dir/src/thrift/transport/TSSLServerSocket.cpp.o -MF …
> THRIFT-5842: Add missing cstdint include for int64_t in Mutex.h

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- lib/go/test/UnionBinaryTest.thrift
- lib/go/test/tests/write_texception_test.go
Client: go
In compiler generated Write method for union types, return a TException (TProtocolException) when the number of fields set is not exactly 1, to help customer logic to decide whether to reuse a connection after an error.
While I'm here, also do the same thing for the uniqueness check failure for set fields in Write as well.
> THRIFT-5845: Return TException for union check in Write

- .github/workflows/build.yml
- lib/nodejs/lib/thrift/thrift.js
- lib/nodejs/test/deep-constructor.test.js
These tests exist, but don't currently run on github actions. This adds a new job to run these.
This also fixes the regression in the tests caused by https://github.com/apache/thrift/pull/3014.
> THRIFT-5564: Add nodejs tests to github actions

- lib/cpp/test/CMakeLists.txt
> lib/cpp/test/CMakeLists.txt: Fix building with OpenBSD

- lib/cpp/src/thrift/transport/THttpServer.cpp
- lib/cpp/src/thrift/transport/TPipeServer.cpp
- lib/cpp/src/thrift/transport/TServerSocket.cpp
- lib/cpp/src/thrift/transport/TWebSocketServer.h
- lib/cpp/src/thrift/windows/SocketPair.cpp
- lib/cpp/src/thrift/windows/Sync.h
Analogous to https://github.com/apache/thrift/pull/2518, improve case-sensitive mingw capitalization
Upstream mingw capitalization patch [https://github.com/JuliaPackaging…](https://github.com/JuliaPackaging/Yggdrasil/blob/6e82040941e891288e394713ee64562698b7ab0d/T/Thrift/bundled/patches/mingw-capitalization.patch)
> Upstream mingw capitalization patch

- compiler/cpp/src/thrift/generate/t_go_generator.h
- compiler/cpp/src/thrift/parse/t_function.h
- compiler/cpp/src/thrift/parse/t_list.h
- compiler/cpp/src/thrift/parse/t_map.h
- compiler/cpp/src/thrift/parse/t_set.h
- compiler/cpp/src/thrift/parse/t_struct.h
- tutorial/rs/src/bin/tutorial_client.rs
This PR fixes the clang build (for the thrift compiler) and makes the Rust tutorial build pass as well.
The C++ changes fix `inconsistent override` compiler warnings, and the Rust change fixes a clippy warning about an unnecessary dereference.
I tested this with the below, which now passes (previously failed):
```
./configure --disable-dependency-tracking --without-python --without-ruby --without-perl  --without-py3 --without-swift --without-nodejs
make -j16
```
> Various build fixes for clang and rust builds

- lib/netstd/Thrift/Protocol/TBinaryProtocol.cs
- lib/netstd/Thrift/Protocol/TCompactProtocol.cs
- lib/netstd/Thrift/Protocol/TJSONProtocol.cs
- lib/netstd/Thrift/Protocol/TProtocolDecorator.cs
- lib/netstd/Thrift/Transport/Client/THttpTransport.cs
- lib/netstd/Thrift/Transport/Client/TMemoryBufferTransport.cs
- lib/netstd/Thrift/Transport/Client/TNamedPipeTransport.cs
- lib/netstd/Thrift/Transport/Client/TStreamTransport.cs
- lib/netstd/Thrift/Transport/Layered/TBufferedTransport.cs
- lib/netstd/Thrift/Transport/Layered/TFramedTransport.cs
- lib/netstd/Thrift/Transport/Layered/TLayeredTransport.cs
- lib/netstd/Thrift/Transport/Server/TNamedPipeServerTransport.cs
- lib/netstd/Thrift/Transport/TEndpointTransport.cs
- lib/netstd/Thrift/Transport/TTransport.cs
> THRIFT-5852 Promote known total stream sizes for seekable stream transports

- lib/cpp/src/thrift/Thrift.h
- lib/cpp/src/thrift/windows/Operators.h
We want to enable the compile option `-D_GLIBCXX_DEBUG` to find potential bugs, but we meet compile errors: [error_log.txt](https://issues.apache.org/jira/secure/attachment/13046360/13046360_error_log.txt)
Let's see the code in apache arrow project: https://github.com/apache/arrow/blob/984b59a2b4edb03479947c46007fc6142447f759/cpp/src/generated/parquet_types.cpp#L36
It constructs a std::map from a pair of iterators. However, in the debug mode of std::map (say, std::__debug::map), it will add additional check (such as boundary check) and need an operator == for these iterators.
So, I want to add an operator ==.
Apache Jira ticket: https://issues.apache.org/jira/browse/THRIFT-5603
> THRIFT-5603: add operator == for TEnumIterator

- lib/nodejs/lib/thrift/browser.js
- lib/nodejs/lib/thrift/index.js
- lib/nodejs/test/exceptions.js
Client: nodejs
When implementing a custom `Connection`, it is very useful to be able to respond to `InputBufferUnderrunError` to roll back the position of the transport. This is now exposed through the root module, so that custom connections can use this.
> THRIFT-5848: Expose InputBufferUnderrunError in nodejs client

- .github/workflows/build.yml
Client: nodets
This adds the tests for the "nodets" library. This isn't an actual library, and are just another set of tests for the nodejs library, but using typescript. Therefore I have added them in the existing "nodejs" job.
> THRIFT-5564: Add nodets tests to Github Actions

- compiler/cpp/src/thrift/generate/t_cpp_generator.cc
This PR adds the option `no_constructors` in the C++ generator. This option elides declaring and defining:
* constructor/destructor
* move/copy constructor/assignment
In addition this PR fixes some minor issues:
1. `gen_no_skeleton_` documentation was incorrect
2. when `templates` are requested, avoid any `virtual` functions
Allowing the compiler to emit the default set of constructor/destructor/assignment operators makes the code faster as it allows inlining when they are trivial. This improves creating deep/elaborate thrift objects.
> THRIFT-5637: Add `no_constructors` option to C++ compiler

- test/crossrunner/compat.py
- test/crossrunner/report.py
- test/crossrunner/run.py
- test/crossrunner/test.py
> test/crossrunner: merge in old Py2vs3 compat.py

- lib/py/src/transport/THttpClient.py
Because removed in Python 3.12 https://docs.python.org/3/whatsnew/3.12.html#others
Solves to [THRIFT-5847](https://issues.apache.org/jira/browse/THRIFT-5847)
> THRIFT-5847: http.client.HTTPSConnection: drop key_file, cert_file

- lib/cpp/src/thrift/protocol/TCompactProtocol.h
- lib/cpp/src/thrift/protocol/TCompactProtocol.tcc
- lib/cpp/src/thrift/protocol/TProtocol.h
- lib/cpp/src/thrift/transport/TBufferTransports.cpp
- lib/cpp/src/thrift/transport/TBufferTransports.h
Removes all oldstyle casts from the library parts needed to parse with TCompactProtocol in memory, like when using thrift for parquet. Thus, it is now possible to compile it with -Wno-old-style-casts
> THRIFT-5853: Remove oldstyle casts from TBufferTransports and TCompactProtocol

- compiler/cpp/src/thrift/generate/t_go_generator.cc
- lib/go/test/tests/enum_values_test.go
Client: go
The generated code looks like this:
type Foo int64
const (
Foo_One Foo = 1
Foo_Two Foo = 2
)
var knownFooValues = []Foo{
Foo_One,
Foo_Two,
}
func FooValues() iter.Seq[Foo] {
return func(yield func(Foo) bool) {
for _, v := range knownFooValues {
if !yield(v) {
return
}
}
}
}
> THRIFT-5859: Generate a values iterator for enum types for go

- lib/cpp/src/thrift/transport/TSSLSocket.cpp
`SSL_get_verify_result()` is [documented to return `long`](https://docs.openssl.org/master/man3/SSL_get_verify_result/).   This change updates the calling code to store the result in `long` instead of `int`.
> Change SSL_get_verify_result() return value from int to long

- compiler/cpp/src/thrift/generate/t_erl_generator.cc
Add some minor improvements to Erlang generator:
- Mark records generated from union as 'union' instead of 'struct'
- Allow choose type for string, can be 'string', 'binary' or 'both' (default)
- Allow sets to be initialised with new(fast) backend (default is old)
> Erlang generator improvements

- lib/py/src/TTornado.py
Normally I include a check like this before closing Thrift connections:
```
if transport and transport.isOpen():
    transport.close()
```
However, for Tornado, `TTornadoStreamTransport.isOpen()` is not implemented, so the call falls back to `TTransportBase`'s empty implementation which just returns `None`. As a result, the above condition to close the connection never gets satisfied, and my application accumulates open connections until eventually it crashes with error message `OSError: [Errno 24] Too many open files`.
To fix this, this patch implements `TTornadoStreamTransport.isOpen()`, using Tornado's [`BaseIOStream.closed()`](https://www.tornadoweb.org/en/stable/iostream.html#tornado.iostream.BaseIOStream.closed
), which returns `True` if the stream has been closed. Before checking …
> THRIFT-5861: Add isOpen method to TTornadoStreamTransport

- lib/go/thrift/duplicate_protocol.go
- lib/go/thrift/duplicate_protocol_test.go
When generated code reads a struct, it runs a `for` loop calling `ReadFieldBegin` at the top, but breaks if the field type ID is `thrift.STOP`.
With TDuplicateToProtocol naively performing an equivalent write for every read, this results in extra bytes, which breaks just about any protocol in the `DuplicateTo` struct field.
The proposed fix is to simply add special handling for `thrift.STOP` to `ReadFieldBegin`.
I'm no thrift expert, so I have no idea how other libraries handle this concern.  Ideally, it seems like each protocol should understand and enforce the invariant that an attempt to call `WriteFieldBegin` with type ID 0 either isn't valid or is a misguided attempt to call `WriteFieldStop`, which could be performed instead, perhaps with the additional guardrail that a sequence of …
> Fix field stop read in duplicate_protocol.go

- CMakeLists.txt
- compiler/cpp/CMakeLists.txt
- compiler/cpp/tests/CMakeLists.txt
This PR updates the minimum required version of CMake. This change is necessary because the CMake 4.0 release [removed policies that allowed supporting such old versions of CMake](https://cmake.org/cmake/help/latest/release/4.0.html#deprecated-and-removed-features), so having such a low required minimum version of CMake prohibits using the latest versions. CMake 3.16 is already quite old (the release was [back in 2019](https://www.kitware.com/cmake-3-16-0-available-for-download/)) and it is a reasonable choice based on Linux distro support (for example, [it is the supported version for Ubuntu's 20.04 LTS release](https://packages.ubuntu.com/search?suite=focal&searchon=names&keywords=cmake)).
I can mark this PR as breaking if desired, but I assume that in general breaking changes are …
> THRIFT-5860: Update minimum required CMake version for CMake 4.0 compatibility

- Package.swift
This will allow the Swift client library to be used with Swift Package Manager, as SPM requires a Package.swift to be at the root of the repository (much like we already have `Thrift.podspec`, `package.json`, `composer.json`, etc).
I did not see the need to create a Jira ticket given how trivial this change is, but I can create one if preferred.
> Add Package.swift to root of repo

- compiler/cpp/src/thrift/generate/t_go_generator.cc
Client: go
Before:
thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("%T error writing set field: slice is not unique", p.Foo))
After:
thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("%T error writing set field %q: slice is not unique", p.Foo, "p.Foo"))
Currently when there are more than one field inside a struct being sets and this error happens, it's impossible to tell which field contains duplications to cause this error.
> Put field name in error message for set duplication check on write

- lib/js/src/thrift.js
readMessageBegin doesn't declare received as a variable.
> Fix received keyword

- lib/java/src/main/java/org/apache/thrift/server/AbstractNonblockingServer.java
- lib/java/src/main/java/org/apache/thrift/transport/sasl/NonblockingSaslHandler.java
> THRIFT-5869: Close the transport after TServerEventHandler deleteContext

- .github/workflows/build.yml
- test/test.py
1. Comment in the middle of multi-line shell command joined by \ does not work, change to multiple individual commands instead.
2. Fix a py 2vs3 compat issue missed in 24df0a5 used in cross runner.
> Fix cross-test

- lib/go/thrift/compact_protocol_test.go
- lib/go/thrift/header_transport.go
- lib/go/thrift/pool.go
- lib/go/thrift/zlib_pool.go
- lib/go/thrift/zlib_pool_test.go
- lib/go/thrift/zlib_transport.go
We implemented a zlib writer pool for default level when implementing THeader, this change also add a zlib reader pool to help speed up things when zlib is used.
Also make TZlibTransport to use the zlib writer pool when it's using the default compression level.
> go: Add a zlib reader pool

- lib/c_glib/src/thrift/c_glib/protocol/thrift_binary_protocol.c
- lib/c_glib/src/thrift/c_glib/protocol/thrift_binary_protocol.h
- lib/c_glib/src/thrift/c_glib/protocol/thrift_compact_protocol.c
- lib/c_glib/src/thrift/c_glib/transport/thrift_transport.c
- lib/cpp/src/thrift/protocol/TBinaryProtocol.tcc
- lib/cpp/src/thrift/protocol/TCompactProtocol.tcc
- lib/cpp/src/thrift/protocol/TJSONProtocol.cpp
- lib/cpp/src/thrift/transport/TTransport.h
- lib/delphi/src/Thrift.Protocol.Compact.pas
- lib/delphi/src/Thrift.Protocol.JSON.pas
- lib/delphi/src/Thrift.Protocol.pas
- lib/go/thrift/binary_protocol.go
- lib/go/thrift/compact_protocol.go
- lib/go/thrift/json_protocol.go
- lib/haxe/src/org/apache/thrift/protocol/TBinaryProtocol.hx
- lib/haxe/src/org/apache/thrift/protocol/TCompactProtocol.hx
- lib/haxe/src/org/apache/thrift/protocol/TJSONProtocol.hx
- lib/haxe/src/org/apache/thrift/transport/TEndpointTransport.hx
- lib/java/src/main/java/org/apache/thrift/protocol/TBinaryProtocol.java
- lib/java/src/main/java/org/apache/thrift/protocol/TCompactProtocol.java
- lib/java/src/main/java/org/apache/thrift/protocol/TJSONProtocol.java
- lib/java/src/main/java/org/apache/thrift/protocol/TSimpleJSONProtocol.java
- lib/java/src/main/java/org/apache/thrift/transport/TEndpointTransport.java
- lib/netstd/Thrift/Protocol/TBinaryProtocol.cs
- lib/netstd/Thrift/Protocol/TCompactProtocol.cs
- lib/netstd/Thrift/Protocol/TJSONProtocol.cs
This makes a number of changes, following the spec laid out in the ticket. The high level goal is to ensure that these checks are consistent throughout the various implementations.
Concretely:
* Some implementations checked for numBytes < 0 in the checkReadBytesAvailable() call. Do this everywhere  
* Always ensure we call checkReadBytesAvailable() with the number of bytes to read, not just container size
* The C glib binary protocol was missing some checks the compact protocol had (I just wholesale copied them, replacing 'compact' with 'binary')
* Some string length checks weren't consistently applied
* getMinSerializedSize() should generally return a minimum of 1, if my understanding of the spec and the context in which it's called in is correct.
I made one PR touching all languages, I …
> [THRIFT-5871] Improve MAX_MESSAGE_SIZE_CHECK and friends

- compiler/cpp/src/thrift/generate/t_erl_generator.cc
Another bunch of Erlang generator improvements. This time changes in type and enum generation with some minor typos. 
Changes:
> Erlang generator improvements for enum and type

- lib/cpp/src/thrift/Thrift.h
- lib/cpp/src/thrift/transport/TSocketUtils.h
Client: cpp
C++17 deprecated std::iterator.
See
https://www.fluentcpp.com/2018/05/08/std-iterator-deprecated/
Prior to this change, compiling while targeting C++17 or higher results in warnings.
> THRIFT-5698: remove use of deprecated std::iterator

- compiler/cpp/src/thrift/generate/t_cpp_generator.cc
swap function should be noexcept
> Generate swap noexcept

- lib/cpp/src/thrift/Thrift.h
- lib/cpp/src/thrift/transport/TSocketUtils.h
https://github.com/apache/thrift/pull/3165 broke the build with c++11.
I split out the compile time fix from https://github.com/apache/thrift/pull/3167/files#diff-d8d7400cdf01511c2ad2df7caf958173c2e96e8633271709c9b0b5cd8e89215c to ensure we have a clean trunk (so I can have other changes on top). I can't take credit for the fixes.
I verified this compiles with gcc, clang (on c++11) and also on clang with c++1z
> Fix C++ build

- .github/workflows/build.yml
- LANGUAGES.md
- go.mod
- lib/go/test/fuzz/go.mod
- lib/go/test/go.mod
- test/go/go.mod
Drop support for go 1.23 as it's no longer supported by upstream.
> Update supported go versions to 1.24+1.25
