apache/thrift

.gitattributes, CONTRIBUTING.md, compiler/cpp/coding_standards.md, doc/coding_standards.md, doc/committers.md, lib/as3/coding_standards.md, lib/c_glib/coding_standards.md, lib/cocoa/coding_standards.md, lib/cpp/coding_standards.md, lib/csharp/coding_standards.md, lib/d/coding_standards.md, lib/delphi/coding_standards.md, lib/erl/coding_standards.md, lib/go/coding_standards.md, lib/haxe/coding_standards.md, lib/hs/coding_standards.md, lib/java/coding_standards.md, lib/javame/coding_standards.md, lib/js/coding_standards.md, lib/lua/coding_standards.md, lib/nodejs/coding_standards.md, lib/ocaml/coding_standards.md, lib/perl/coding_standards.md, lib/php/coding_standards.md, lib/py/coding_standards.md, lib/rb/coding_standards.md, lib/st/coding_standards.md, lib/ts/coding_standards.md
Initial coding standards commit - making work more public
=> THRIFT-2724 - Coding standards template added all over project

compiler/cpp/src/generate/t_cpp_generator.cc, lib/cpp/CMakeLists.txt, lib/cpp/Makefile.am, lib/cpp/src/thrift/protocol/TProtocol.cpp, lib/cpp/src/thrift/protocol/TProtocol.h
Client: cpp
Patch: Ben Craig <bencraig@apache.org>
=> THRIFT-3231 CPP: Limit recursion depth to 64

lib/java/src/org/apache/thrift/server/TThreadPoolServer.java
=> THRIFT-3769 : Fix logic of THRIFT-2268

compiler/cpp/src/thrift/generate/t_rs_generator.cc
Just simplify the rust code generated by the generator. 😀
=> [Rust] Simplify the rust code generated by the generator

doc/specs/idl.md
Fixes a small documentation typo.
=> THRIFT-4569: Fix 'requiredness' typo

lib/swift/README.md, lib/swift/Sources/TBinaryProtocol.swift, lib/swift/Sources/TClient.swift, lib/swift/Sources/TCompactProtocol.swift, lib/swift/Sources/TList.swift, lib/swift/Sources/TMap.swift, lib/swift/Sources/TSet.swift, lib/swift/Sources/TSocketTransport.swift, lib/swift/Sources/Thrift.swift, lib/swift/Tests/ThriftTests/TBinaryProtocolTests.swift, lib/swift/Tests/ThriftTests/TCompactProtocolTests.swift, lib/swift/Tests/ThriftTests/ThriftTests.swift
Some minor updates to the Swift library (mirrored here [apocolipse/thrift-swift](https://github.com/apocolipse/thrift-swift) for package management usage)
Updates are backwards/forwards compatible with Swift 3/4
Swift native tests added as well
=> Update Swift Library and Tests

compiler/cpp/CMakeLists.txt, compiler/cpp/src/thrift/generate/t_generator.cc, compiler/cpp/src/thrift/generate/t_generator.h, compiler/cpp/src/thrift/generate/t_py_generator.cc, compiler/cpp/src/thrift/main.cc, compiler/cpp/src/thrift/thriftl.ll, compiler/cpp/test/CMakeLists.txt, compiler/cpp/test/keyword-samples/const1_return.thrift, compiler/cpp/test/keyword-samples/enum1_return.thrift, compiler/cpp/test/keyword-samples/enum2_return.thrift, compiler/cpp/test/keyword-samples/exception1_return.thrift, compiler/cpp/test/keyword-samples/exception2_return.thrift, compiler/cpp/test/keyword-samples/service1_return.thrift, compiler/cpp/test/keyword-samples/service2_return.thrift, compiler/cpp/test/keyword-samples/service3_return.thrift, compiler/cpp/test/keyword-samples/service4_return.thrift, compiler/cpp/test/keyword-samples/struct1_return.thrift, compiler/cpp/test/keyword-samples/struct2_return.thrift, compiler/cpp/test/keyword-samples/typedef1_return.thrift, compiler/cpp/test/keyword-samples/union1_return.thrift, compiler/cpp/test/keyword-samples/union2_return.thrift
=> THRIFT-4496: python specific list of keywords for python generator

compiler/cpp/src/thrift/generate/t_py_generator.cc
=> THRIFT-4644: Compiler cannot be compiled on macOS

lib/java/src/org/apache/thrift/transport/TFileTransport.java
Some helpful tips for a successful Apache Thrift PR:
* Did you test your changes locally or using CI in your fork?
* Is the Apache Jira THRIFT ticket identifier in the PR title?
* Is the Apache Jira THRIFT ticket identifier in the commit message?
* Did you squash your changes to a single commit?
* Are these changes backwards compatible? (please say so in PR description)
* Do you need to update the language-specific README?
Example ideal pull request title:
THRIFT-9999: an example pull request title
Example ideal commit message:
THRIFT-9999: [summary of fix, one line if possible]
Client: [language(s) affected, comma separated, use lib/ directory names please]
For more information about committing, see CONTRIBUTING.md
=> THRIFT-4499: Remove Magic Number In TFIleTransport (BELUGA BEHR)

lib/java/src/org/apache/thrift/transport/TSocket.java
@jeking3 Could you please review this as well. Thank you
=> THRIFT-4494: Increase Java Socket Buffer Size (BELUGA BEHR)

lib/rs/src/protocol/binary.rs
=> THRIFT-4658: TBinaryInputProtocol fails when strict is false

compiler/cpp/src/thrift/generate/t_rs_generator.cc, lib/rs/test/thrifts/Base_One.thrift
Client: rs
Fix with simple test
=> THRIFT-4662: Rust const string calls function at compile time

compiler/cpp/src/thrift/generate/t_rs_generator.cc
=> Fix function name in Rust generator (does not affect generated code)

lib/php/lib/Transport/THttpClient.php
This PR adds stream context options support into PHP/THttpClient.
=> THRIFT-4674 Added stream context support for PHP THttpClient

lib/go/thrift/server_socket.go
Some helpful tips for a successful Apache Thrift PR:
* Did you test your changes locally or using CI in your fork? 
Tested changes locally
* Is the Apache Jira THRIFT ticket identifier in the PR title?
Yes
* Is the Apache Jira THRIFT ticket identifier in the commit message?
Yes
* Did you squash your changes to a single commit?
Yes
* Are these changes backwards compatible? (please say so in PR description)
* Do you need to update the language-specific README?
Client: [go]
=> THRIFT-4659 golang race detected when closing listener socket

lib/rs/Cargo.toml, lib/rs/RELEASING.md, lib/rs/release.sh
=> Update Cargo.toml, release instructions and release script

lib/java/src/org/apache/thrift/TBaseHelper.java
@jeking3 Hey, I was already working on this one, so I'll submit it.  However, I'll take a look at any existing tickets now.
=> THRIFT-4713: Review of TBaseHelper

compiler/cpp/src/thrift/generate/t_js_generator.cc
This fixes some problems with the generated `.d.ts` files
=> THRIFT-4738: Fix typescript declaration generation

.travis.yml, lib/java/CMakeLists.txt, lib/java/README.md, lib/java/build.gradle, lib/java/gradle.properties, lib/java/gradle/publishing.gradle, lib/java/gradle/wrapper/gradle-wrapper.properties, test/dart/test_client/bin/main.dart, test/tests.json
Also fix java debug vs. release build with cmake.
=> THRIFT-4746: changes for publishing 0.12.0 to maven (WORKING ON CROSS TEST DART FAILURES)

lib/py/src/transport/TSSLSocket.py, lib/py/src/transport/TSocket.py
The [Contributing Guide](https://github.com/apache/thrift/blob/master/CONTRIBUTING.md) has more details and tips for
committing properly.
Review the following checklist to ensure a smooth pull request experience.
</details>
</details>
</details> …
=> THRIFT-4767: Added TSocket/TSSLSocket support tcp keep-alive in python

lib/c_glib/src/thrift/c_glib/transport/thrift_socket.c
Simple fix for a warning
Review the following checklist to ensure a smooth pull request experience.
</details>
</details>
</details>
- `No` for …
=> fix minor glib warning

lib/py/src/protocol/TBinaryProtocol.py, lib/py/src/protocol/TCompactProtocol.py, lib/py/src/protocol/THeaderProtocol.py, lib/py/src/protocol/TJSONProtocol.py
The protocol factory classes were not inheriting from the correct base class in python.
</details>
</details>
</details>
- `No` for …
=> THRIFT-4778: fix inheritance for protocol factories

LANGUAGES.md, build/appveyor/MSVC-appveyor-install.bat, build/docker/msvc2017/Dockerfile, build/docker/msvc2017/build.bat
Added appveyor and windows docker build image support for building AS3 on windows through cmake (which invokes gradle - same as linux).
Review the following checklist to ensure a smooth pull request experience.
</details>
</details>
</details>
- …
=> THRIFT-4037: get as3 builds working in cmake for windows too

lib/as3/src/org/apache/thrift/protocol/TProtocolUtil.as
=> THRIFT-4784 Thrift should throw when skipping over unexpected data

lib/py/src/transport/TSSLSocket.py
=> Fix spelling errors in TSSLSocket.py

tutorial/rs/src/bin/tutorial_client.rs
A clarification on the docs of where a value comes from  
You should enable it in Github tho
=> [RS] Add clarification of where a constant comes from

configure.ac, lib/hs/thrift.cabal
…iled to load interface for `Network' is solved
=> THRIFT-4834 CI error at Haskell: Failed to load interface for 'Network'

CHANGES.md, build/docker/ubuntu-bionic/Dockerfile, build/docker/ubuntu-xenial/Dockerfile, lib/rs/README.md
Update dockerfiles to use rust stable, call out required rust version in
breaking changes.
=> THRIFT-4536: Rust 1.34.0

compiler/cpp/src/thrift/generate/t_erl_generator.cc
Client: erl
Add missing autogenerated comment to Erlang's header files
=> Add missing autogenerated comment to header files

lib/erl/src/thrift_socket_server.erl
Client: erl
This change suppress error reporting for normal server shutdown.
=> Report error for abnormal server termination only

lib/go/thrift/socket.go
=> spelling mistake, perhaps

test/README.md
=> Fix environment spelling

test/ThriftTest.thrift
=> Fix some typos in ThriftTest.thrift

compiler/cpp/src/thrift/generate/t_js_generator.cc
This changes makes the follow updates for TypeScript generation: 
- Ensures imports are generated for includes in *_types.d.ts files
- Ensures generated type names for struct fields and function arguments are prefixed with import name if the type is not defined within the same program.
Prior to this change it was possible to generate invalid TypeScript definitions if the generated service or types included types from other programs. 
**Before**
```ts
// foo_types.d.ts
import other_types = require("./other"); 
declare class MyStruct {
public field: OtherType; // !!! Compile failure, unknown type OtherType
}
// foo_service.d.ts
import other_types = require("./other"); 
class MyService {
public magic(request: OtherRequest) : Promise<OtherResponse> // !!! Compile failure, unknown type …
```
=> THRIFT-4899 - Fix typescript generation for multi include cases

lib/go/thrift/header_transport.go
client: go
This was missing from
https://github.com/apache/thrift/commit/4d46c1124450eeb77d2a6adc7ea5fab304bfeb4a
- [Y] Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?  (not required for trivial changes)
- [Y] Did you squash your changes to a single commit?  (not required, but preferred)
- [Y] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
=> THRIFT-4612: Add THeaderTransportFactory to go library

compiler/cpp/src/thrift/generate/t_rs_generator.cc, lib/rs/src/autogen.rs, lib/rs/src/errors.rs, lib/rs/src/lib.rs, lib/rs/src/protocol/binary.rs, lib/rs/src/protocol/compact.rs, lib/rs/src/protocol/mod.rs, lib/rs/src/protocol/stored.rs, lib/rs/src/server/mod.rs, lib/rs/src/server/multiplexed.rs, lib/rs/src/server/threaded.rs, lib/rs/src/transport/buffered.rs, lib/rs/src/transport/framed.rs, lib/rs/src/transport/mod.rs, lib/rs/test/Makefile.am, test/Identifiers.thrift
When identifiers are not specified, negative id will be converted to a valid
rust identifier.
This is building on the work in #1851, and could either replace it or be merged after.
=>  THRIFT-4953: Missing Field Identifiers

tutorial/php/PhpClient.php, tutorial/php/PhpServer.php
Client: PHP
This PR updates the PHP tutorial in accordance with the following instruction in lib/php/README.md:
```
2. If using PSR-4, use `$thriftClassLoader->registerNamespace('namespace', '<path>')` instead of `$thriftClassLoader->registerDefinition('namespace', '<path>')`.
```
I confirmed this fix works as follows:
Console #1:
```sh
thrift$ cd tutorial
thrift/tutorial$ ../compiler/cpp/thrift -r -gen php:server tutorial.thrift
thrift/tutorial$ php/runserver.py
```
Console #2:
```
thrift$ cd tutorial
thrift/tutorial$ php/PhpClient.php --http
ping()
1+1=2
InvalidOperation: Cannot divide by 0
15-10=5
Log: PHP is stateless!
```
Console #1:
```
127.0.0.1 - - [05/Oct/2019 17:07:16] "POST /php/PhpServer.php HTTP/1.0" 200 -
ping()
127.0.0.1 - - [05/Oct/2019 17:07:16] "POST /php/PhpServer.php …
```
=> THRIFT-4970: PHP tutorial doesn't work with Thrift v0.12.0+

doc/specs/idl.md
=> fix typo in idl.md

lib/nodejs/README.md
This change is a Nodejs example for browsers in lib/nodejs/README.md.
=> Nodejs example for browsers in README.md

configure.ac, tutorial/Makefile.am, tutorial/php/Makefile.am, tutorial/php/PhpClient.php, tutorial/php/PhpServer.php
Client: php
This PR adds Makefile.am to the PHP tutorial so that users can run it easily.
=> THRIFT-4975: Add Makefile.am to the PHP tutorial

lib/go/thrift/simple_server.go
Client: go
Since we are already ignoring some other EOF errors in
TSimpleServer.processRequest[0], this would help us reducing the spammy
and scary logs.
Also give the user more control on how TSimpleServer does the logging.
[0]: https://github.com/apache/thrift/blob/cecee50308fc7e6f77f55b3fd906c1c6c471fa2f/lib/go/thrift/simple_server.go#L265-L266
=> THRIFT-4984: Ignore EOF error in TSimpleServer ReadFrame call

lib/java/src/org/apache/thrift/transport/TIOStreamTransport.java
Make it clear about input/output only transport.
=> THRIFT-5031: Fix TIOStreamTransport javadoc

lib/nodejs/README.md, lib/nodejs/lib/thrift/browser.js, lib/nodejs/lib/thrift/ws_connection.js, lib/nodejs/lib/thrift/ws_transport.js, package-lock.json, package.json
After some changes to the ws_connection.js file in the nodejs code, I could create a version of the WSConnection, createWSConnection and createWSClient which is able to run similar code of WebSocket connections in the browser and NodeJS.
Solution is package, `isomorphic-ws` which provides the proper Websocket libs depending on the env (browser or node)
https://issues.apache.org/jira/browse/THRIFT-5003
- [] If your change does not involve any code, add ` [skip ci]` at the end of your pull request to free up build resources.
=> THRIFT-5003: Websocket Connection in Browsers with nodejs code

configure.ac
`--with-py3` was not working as expected before, so I did a quick investigation and found there was a typo.
=> Fix typo for python 3 support

test/c_glib/src/test_client.c, test/c_glib/src/test_server.c, test/c_glib/src/thrift_test_handler.c
Client: c_glib
Patch: wangyunjian
Signed-off-by: wangyunjian <wangyunjian@huawei.com>
=> THRIFT-5157 Fix memory leak in c_glib unit tests

lib/py/CMakeLists.txt, lib/py/Makefile.am, lib/py/test/thrift_TBinaryProtocol.py
=> Supplement TBinaryprotocol module testcase

lib/go/thrift/framed_transport.go
Client: go
While debugging the issue in THRIFT-5214, I original thought that was a
bug in TFramedTransport implementation, so I took some time scrutinize
the TFramedTransport code. Although in the end there's no bug, the
current implementation of TFramedTransport, especially in the Read
function, has some weird handling while at frame boundary, which is both
error-prone and hard to follow (I did found and fixed one bug there in
https://github.com/apache/thrift/pull/1810 before).
The new implementation reads the whole frame into a buffer, which would
use slightly more memory, but it follows the pattern of TFramedTransport
implementation of other languages (e.g. Java), and also the pattern we
handle frame in THeaderTransport. It also reduced the complexity and
weirdness of the frame …
=> THRIFT-5214: Partial rewrite of TFramedTransport

lib/py/setup.py
=> THRIFT-5249 Fix Failed to run FastbinaryTest.py

lib/go/thrift/deserializer.go, lib/go/thrift/serializer.go
Client: go
Cleanup the default NewTSerializer and NewTDeserializer implementations
to save an unnecessary allocation, and provide
NewTSerializerPoolSizeFactory and NewTDeserializerPoolSizeFactory for
easier non-default pool usages.
=> THRIFT-5279: Go serializer/deserializer cleanups

lib/c_glib/test/CMakeLists.txt
=> c_glib add the test case into cmake

lib/c_glib/src/thrift/c_glib/transport/thrift_server_transport.c, lib/c_glib/src/thrift/c_glib/transport/thrift_server_transport.h, lib/c_glib/src/thrift/c_glib/transport/thrift_ssl_socket.c, lib/c_glib/src/thrift/c_glib/transport/thrift_transport.c, lib/c_glib/test/testmemorybuffer.c, lib/c_glib/test/testthriftbinaryreadcheck.c, lib/c_glib/test/testthriftbufferedreadcheck.c, lib/c_glib/test/testthriftcompactreadcheck.c, lib/c_glib/test/testtransportsslsocket.c
=> fix warning in c_glib from add max_message_size code

build/appveyor/MING-appveyor-install.bat, build/appveyor/MSYS-appveyor-install.bat
=> Thrift-5296 Fix Download fail in the appveyor

lib/c_glib/src/thrift/c_glib/transport/thrift_framed_transport.c, lib/c_glib/src/thrift/c_glib/transport/thrift_framed_transport.h
=> Fix Missed check in c_glib for frame max message size check

lib/go/thrift/http_client.go
Client: go
The fix in https://github.com/apache/thrift/pull/2293 doesn't work for
go1.10.8 due to the possibility of data races. This exposes a bigger,
underlying issue regarding the ownership of the request buffer in
THttpClient between THttpClient itself and the http request it creates.
Instead of reset and reuse the same buffer, always give up the ownership
of it and create a new buffer after each Flush call.
=> THRIFT-5324: Create new req buffer for every http request

lib/cpp/src/thrift/transport/TServerSocket.cpp
There is a small chance that a server side domain socket file is not reported as existing on the file system despite the server socket already being open. This can happen i.e. on Windows. But its generally a good idea if the server checks for existence before reporting the socket as being open. This helps i.e. with automatic testing, when clients must not try to connect before the file exists.
=> TServerSocket.cpp::isOpen(): Check that a domain socket really exists

build/appveyor/MING-appveyor-install.bat
=> Fix appveyor again

lib/java/src/org/apache/thrift/server/ServerContext.java, lib/java/test/org/apache/thrift/test/TestServer.java
=> THRIFT-5345: Allow the ServerContext to be Unwrapped Programmatically

compiler/cpp/src/thrift/generate/t_rs_generator.cc, lib/rs/README.md, lib/rs/test/src/bin/kitchen_sink_server.rs, test/rs/src/bin/test_client.rs, test/rs/src/bin/test_server.rs, tutorial/rs/src/bin/tutorial_client.rs, tutorial/rs/src/bin/tutorial_server.rs
=> [THRIFT-5314][THRIFT-4101] Generate enums that don't error on unexpected values

compiler/cpp/src/thrift/generate/t_rs_generator.cc, lib/rs/Makefile.am, lib/rs/test/Makefile.am, test/rs/Makefile.am, tutorial/rs/Makefile.am, tutorial/rs/src/bin/tutorial_server.rs
=> Enable clippy in all Rust targets and ensure that all existing code is clippy-clean

.gitignore, compiler/cpp/src/thrift/generate/t_rs_generator.cc, configure.ac, lib/rs/test_recursive/Cargo.toml, lib/rs/test_recursive/Makefile.am, lib/rs/test_recursive/src/Makefile.am, lib/rs/test_recursive/src/Vehicles.thrift, lib/rs/test_recursive/src/lib.rs, lib/rs/test_recursive/src/maintenance/MaintenanceFacility.thrift, lib/rs/test_recursive/src/maintenance/Makefile.am, lib/rs/test_recursive/src/maintenance/mod.rs, lib/rs/test_recursive/src/transit/Buses.thrift, lib/rs/test_recursive/src/transit/Makefile.am, lib/rs/test_recursive/src/transit/Trains.thrift, lib/rs/test_recursive/src/transit/Transporters.thrift, lib/rs/test_recursive/src/transit/light/LightRail.thrift, lib/rs/test_recursive/src/transit/light/Makefile.am, lib/rs/test_recursive/src/transit/light/Streetcars.thrift, lib/rs/test_recursive/src/transit/light/mod.rs, lib/rs/test_recursive/src/transit/mod.rs, lib/rs/test_recursive/src/transit/services/CityServices.thrift, lib/rs/test_recursive/src/transit/services/Makefile.am, lib/rs/test_recursive/src/transit/services/mod.rs
=> THRIFT-4098 Namespace support for generated Rust code

lib/go/thrift/protocol.go
Do error checkin in golang, while reading a `STRUCT`
Cf https://github.com/google/oss-fuzz/pull/5264#issuecomment-787546749
Change looks trivial to me
No ticket exists
Trivial change should not break anything
This change involves code
=> Early error check in golang struct reading

configure.ac, lib/go/test/fuzz/Makefile.am, lib/go/test/fuzz/fuzz.go, lib/go/test/fuzz/fuzz_test.go
Adds a fuzz target for oss-fuzz integration cf https://github.com/google/oss-fuzz/pull/5264  
This change is about adding a fuzz target, ie a new testing methodology... I do not know if you want a ticket for it
No ticket exists
This only adds a fuzz target, and does not touch the existing code
This change adds code, but it is testing code, so I do not know if it should skip ci
=> Adds fuzz target for oss-fuzz integration

compiler/cpp/src/thrift/generate/t_netstd_generator.cc
=> THRIFT-5414 Use of specific parameter names generates uncompileable code

lib/c_glib/src/thrift/c_glib/transport/thrift_server_socket.c
=> THRIFT-5399: Fix socket leak in abnormal situation(c_glib)

lib/java/src/org/apache/thrift/transport/TIOStreamTransport.java
=> THRIFT-5411: Catch SocketTimeoutException in TIOStreamTransport read

lib/java/src/org/apache/thrift/server/TThreadPoolServer.java
=> THRIFT-5433: Add Counter To Thread Name of TThreadPoolServer

composer.json
=> THRIFT-5440: Allow php8 in composer.json

lib/c_glib/src/thrift/c_glib/transport/thrift_socket.c
…ome files
Client: c_glib
Patch: lm2048
=> THRIFT-5421: [c_glib]Fix the problem of incorrect setting of errno

lib/java/src/org/apache/thrift/EncodingUtils.java, lib/java/src/org/apache/thrift/TDeserializer.java, lib/java/src/org/apache/thrift/TMultiplexedProcessor.java, lib/java/src/org/apache/thrift/TNonblockingMultiFetchClient.java, lib/java/src/org/apache/thrift/TSerializer.java, lib/java/src/org/apache/thrift/TServiceClientFactory.java, lib/java/src/org/apache/thrift/TUnion.java, lib/java/src/org/apache/thrift/async/TAsyncClient.java, lib/java/src/org/apache/thrift/transport/TByteBuffer.java
fix javadoc warnings
[skip ci] No code change, just update javadoc comments so that warnings are not shown during build.
=> fix javadoc warnings

lib/rs/Cargo.toml, lib/rs/src/lib.rs
=> THRIFT-5452: Made Rust server optional

compiler/cpp/src/thrift/generate/t_go_generator.cc, test/ThriftTest.thrift
=> THRIFT-4868: Golang: Fix compilation for optional set<binary> with default values

lib/rs/test/Cargo.toml, test/rs/Cargo.toml, tutorial/rs/Cargo.toml
=> THRIFT-5457 Pin bitflags to 1.2 to maintain MSRV

lib/py/setup.cfg, lib/py/setup.py
These are changes I made to improve the pypi description for the release of 0.14.0 through 0.15.0.
=> minor changes to make pypi distribution look better (long desc)

lib/perl/build-cpan-dist.sh
Fix an issue with perl packaging.
=> fix perl packaging issue

lib/netstd/Thrift/Server/TSimpleAsyncServer.cs, lib/netstd/Thrift/Server/TThreadPoolAsyncServer.cs, test/netstd/Client/Performance/PerformanceTests.cs, test/netstd/Client/Program.cs, test/netstd/Client/TestClient.cs, test/netstd/Server/Program.cs, test/netstd/Server/TestServer.cs
=> THRIFT-5481 consolidate netstd server implementation details into one common model

lib/java/src/org/apache/thrift/partial/README.md
[skip ci] : updated README.md to reflect final merged changes (THRIFT-5443). There are no code change.
=> [skip ci] updated README.md to reflect final merged changes (THRIFT-5443)

build/docker/README.md, build/docker/old/debian-stretch/Dockerfile, build/docker/old/ubuntu-artful/Dockerfile, build/docker/ubuntu-bionic/Dockerfile, build/docker/ubuntu-disco/Dockerfile, build/docker/ubuntu-xenial/Dockerfile, debian/control, doc/install/debian.md, lib/netstd/Benchmarks/Thrift.Benchmarks/Thrift.Benchmarks.csproj, lib/netstd/Tests/Thrift.IntegrationTests/Thrift.IntegrationTests.csproj, lib/netstd/Tests/Thrift.PublicInterfaces.Compile.Tests/Thrift.PublicInterfaces.Compile.Tests.csproj, lib/netstd/Tests/Thrift.Tests/Thrift.Tests.csproj, lib/netstd/Thrift/Collections/THashSet.cs, lib/netstd/Thrift/Thrift.csproj, lib/netstd/Thrift/Transport/Server/TNamedPipeServerTransport.cs, test/netstd/Client/Client.csproj, test/netstd/Server/Server.csproj, tutorial/netstd/Client/Client.csproj, tutorial/netstd/Client/Program.cs, tutorial/netstd/Interfaces/Interfaces.csproj, tutorial/netstd/Server/Program.cs, tutorial/netstd/Server/Server.csproj
=> THRIFT-5479 Add net 6 support

lib/netstd/Thrift/GlobalSuppressions.cs, lib/netstd/Thrift/Processor/TMultiplexedProcessor.cs, lib/netstd/Thrift/Protocol/TBinaryProtocol.cs, lib/netstd/Thrift/Protocol/TCompactProtocol.cs, lib/netstd/Thrift/Protocol/TJSONProtocol.cs, lib/netstd/Thrift/Protocol/TProtocol.cs, lib/netstd/Thrift/Protocol/ToString.cs, lib/netstd/Thrift/Server/TServer.cs, lib/netstd/Thrift/Server/TServerEventHandler.cs, lib/netstd/Thrift/Server/TSimpleAsyncServer.cs, lib/netstd/Thrift/Server/TThreadPoolAsyncServer.cs, lib/netstd/Thrift/Transport/Client/THttpTransport.cs, lib/netstd/Thrift/Transport/Client/TMemoryBufferTransport.cs, lib/netstd/Thrift/Transport/Layered/TBufferedTransport.cs, lib/netstd/Thrift/Transport/Layered/TFramedTransport.cs, lib/netstd/Thrift/Transport/Server/TServerSocketTransport.cs
=> THRIFT-5504 CA2254 Message template should be compile time constant

lib/go/thrift/socket_conn.go
Client: go
When the connectivity check failed in IsOpen, close the connection
explicitly to avoid connection leaks.
This is Path 2 of THRIFT-5509.
=> THRIFT-5509: Close connection in IsOpen

lib/go/thrift/simple_server.go
Client: go
This is a follow up of 6f33b0470. After we proactively closed the client
connection, processor.Process could return NOT_OPEN as a result, and
those errors being logged will cause the log to be very noisy.
This will also be cherry-picked into 0.16.0 branch.
=> THRIFT-5509: Suppress noisy log from go's TSimpleServer

lib/java/src/org/apache/thrift/Option.java
=> THRIFT-5520 [java lib] add support for converting to java optional

lib/java/build.gradle, lib/java/gradle/codeQualityChecks.gradle, lib/java/gradle/wrapper/gradle-wrapper.properties
=> THRIFT-5522: update to gradle 6.9, update findbugs

lib/netstd/Thrift/Transport/Server/TTlsServerSocketTransport.cs
=> Pass cancellation token to AcceptTcpClientAsync() in net6

compiler/cpp/src/thrift/generate/t_json_generator.cc
- THRIFT-5549: json gen should indent while printing include strings
```json
{
"name": "Include",
"namespaces": {
},
"includes": [
"ThriftTest"
],
"enums": [
],
"typedefs": [
],
"structs": [
{
"name": "IncludeTest",
"isException": false,
"isUnion": false,
"fields": [
{
"key": 1,
"name": "bools",
"typeId": "struct",
"type": {
"typeId": "struct",
"class": "ThriftTest.Bools"
},
"required": "required"
}
]
}
],
"constants": [
],
"services": [
]
}
```
```json
{
"name": "Include",
"namespaces": {
},
"includes": [
"ThriftTest"
],
"enums": [
],
"typedefs": [
],
"structs": [
{
"name": "IncludeTest",
"isException": false,
"isUnion": false,
"fields": [
{
"key": 1,
"name": "bools",
"typeId": "struct",
"type": {
"typeId": "struct",
"class": "ThriftTest.Bools"
},
"required": "required"
}
]
}
], …
```
=> THRIFT-5549: json gen should indent while printing include strings

compiler/cpp/src/thrift/generate/t_java_generator.cc
apply clang-format to java generator, all changes are formatting changes, no actual code logic changes.
steps:
```bash
apt install clang-format
clang-format -i <file>
```
=> THRIFT-5552: apply clang-format to java generator

compiler/cpp/src/thrift/generate/t_java_generator.cc, lib/java/gradle/generateTestThrift.gradle, lib/java/src/org/apache/thrift/async/AsyncMethodFutureAdapter.java
Java codegen and library to support future-returning client interface and implementation
=> THRIFT-5555: Java codegen and library to support future-returning client interface and implementation

compiler/cpp/src/thrift/generate/t_java_generator.cc
THRIFT-5485: change the java gen @SuppressWarnings location
=> THRIFT-5485: change the java gen @SuppressWarnings location

lib/cpp/test/TMemoryBufferTest.cpp
My main use case with the original code change was that I wanted to be able to call `resetBuffer()` on `OBSERVE` buffers and reuse the contents for test cases over and over. While the default `resetBuffer()` cannot be used for that purpose, the same result can be achieved by calling `resetBuffer(ro_mem, ro_mem_size, OBSERVE)` as well, so the workaround is fairly trivial.
While the former implementation would be more convenient in some cases, it makes more sense to have consistent behaviour for all `resetBuffer()` implementations.
Added test cases to clarify the effect of `MemoryPolicy` on  `TMemoryBuffer` behaviour.
=> THRIFT-5093: lib: cpp: test: clarify effect of MemoryPolicy on TMemoryBuffer

lib/py/src/server/TNonblockingServer.py
Use poll instead of select if possible
Currently, Python TNonblockingServer uses `select.select` to monitor the IO of all existing connections. The value of file descriptors monitored by `select()` is limited to be lower than FD_SETSIZE (1024). Any file descriptor higher than 1024 will trigger the `fd out of range` error in `select.select`
Switching to `select.poll` can solve this problem. However, as noted in the [official documentation](https://docs.python.org/3/library/select.html#select.poll), `select.poll` is not supported in all operating systems. We should also check whether the current system has `poll` in the select module, and use `poll` if it's available. 
Another advantage of `poll` came up while I was debugging my original draft: `poll` is able to explicitly catch the case …
=> THRIFT-5449: Use poll instead of select in Python TNonblockingServer if available

lib/netstd/Thrift/Thrift.csproj
=> THRIFT-5585 net5.0 end of support May 2022

lib/rs/Cargo.toml
=> rust lib: fix integer-encoding to 3.0.3

lib/rs/src/protocol/mod.rs
=> [skip ci] fix typo

.github/workflows/build.yml, build/docker/ubuntu-bionic/Dockerfile, build/docker/ubuntu-disco/Dockerfile, build/docker/ubuntu-xenial/Dockerfile, doc/install/debian.md, lib/java/README.md
=> update gradle version to 7.5.1 and update hashes

compiler/cpp/src/thrift/generate/t_ocaml_generator.cc
Fix https://issues.apache.org/jira/browse/THRIFT-5208
=> THRIFT-5208: capitalize exception ctor

lib/netstd/Thrift/Transport/Client/TSocketTransport.cs
I've created this PR to address the issue THRIFT-5610 I raised.
This PR should have no breaking changes, it adds a single additional ctor to TSocketTransport.
=> Add TSocketTransport ctor

lib/erl/test/test_thrift_socket_transport.erl
=> THRIFT-5636: Fix tests for new thrift_socket_transport:read/2

build/docker/ubuntu-bionic/Dockerfile, build/docker/ubuntu-focal/Dockerfile
disable opam sandboxing for ubuntu focal, in order to fix error message https://app.travis-ci.com/github/apache/thrift/jobs/583252815
=> [build infra][ocaml] disable opam sandboxing for ubuntu bionic and focal

.travis.yml
fix travis config where distro=bionic was missing
=> [build infra] fix travis config where distro=bionic was missing

build/docker/ubuntu-bionic/Dockerfile
remove --disable-sandboxing in bionic, partly reverting #2671
=> THRIFT-5642: [build infra][ocaml] remove --disable-sandboxing in bionic

.travis.yml
use bionic for almost all tasks for now in travis, because focal is too new for some of the language library code
=> [build infra] use bionic for almost all tasks for now in travis

.travis.yml, README.md, lib/java/src/test/java/org/apache/thrift/partial/ThriftSerDe.java, lib/java/src/test/java/org/apache/thrift/protocol/ProtocolTestBase.java, lib/java/src/test/java/org/apache/thrift/test/ReadStruct.java, lib/java/src/test/java/org/apache/thrift/test/WriteStruct.java
=> [docs] update travis ci links - [skip ci]

LANGUAGES.md, build/docker/ubuntu-bionic/Dockerfile, build/docker/ubuntu-focal/Dockerfile, go.mod
Updated the max Golang version to latest 1.19.2
=> Bump go version to 1.19.2 and update hashes

.github/workflows/build.yml, .travis.yml, build/docker/ubuntu-jammy/Dockerfile
add ubuntu jammy in build infra
=> THRIFT-5633: [build infra] add ubuntu jammy in build infra

lib/cpp/src/thrift/server/TServerFramework.cpp
Use of `std::placeholders::_1` requires `<functional>`.
No
No
Yes
Change"?
Yes
=> lib: cpp: thrift: include functional in TServerFramework

compiler/cpp/src/thrift/generate/t_go_generator.cc, compiler/cpp/src/thrift/generate/validator_parser.cc, lib/go/test/EqualsTest.thrift, lib/go/test/tests/equals_test.go, lib/go/thrift/json_protocol.go, test/ConstantsDemo.thrift, test/go/Makefile.am, test/go/src/bin/testclient/main.go, test/go/src/common/clientserver_test.go, test/go/src/common/printing_handler.go, test/go/src/common/simple_handler.go
=> THRIFT-5650: Implement UUID in Go compiler

lib/cpp/Makefile.am, lib/cpp/src/thrift/transport/TFDTransport.cpp
2 commits to address 2 issues:
* lib: cpp: transport: include thrift/config.h in TFDTransport
- Fixes https://app.travis-ci.com/github/apache/thrift/jobs/589120685
* lib: cpp: automake: ship thrift/numeric_cast.h
- Fixes https://app.travis-ci.com/github/apache/thrift/jobs/589120686
cc @Jens-G
=> Fix cpp header issues

compiler/cpp/src/thrift/generate/t_js_generator.cc, tutorial/nodejs/NodeClientPromise.js
=> THRIFT-5674: Catch and handle server implementation exceptions

test/go/go.mod, test/go/go.sum
=> Fix github actions error on go tests

test/go/go.mod, test/go/go.sum
This replaces and closes https://github.com/apache/thrift/pull/2774.
=> Bump test/go dependency

lib/java/src/main/java/org/apache/thrift/server/TThreadPoolServer.java, lib/java/src/test/resources/log4j.properties
reduce excesive java logging in tthreaded server
=> reduce excesive java logging in tthreaded server

.github/workflows/build.yml, build/docker/old/ubuntu-disco/Dockerfile, build/docker/old/ubuntu-xenial/Dockerfile, build/docker/ubuntu-bionic/Dockerfile, build/docker/ubuntu-focal/Dockerfile, build/docker/ubuntu-jammy/Dockerfile, doc/install/README.md, doc/install/debian.md, lib/java/README.md
=> update gradle to version 7.6

.github/workflows/build.yml
update .github workflow to consolidate config in order to reduce duplications
=> update .github workflow to consolidate config

lib/java/build.gradle, lib/java/gradle.properties, lib/java/gradle/environment.gradle, lib/java/gradle/generateTestThrift.gradle, lib/java/gradle/unitTests.gradle, lib/java/src/test/java/org/apache/thrift/TestMultiplexedProcessor.java
=> Upgrade java mockito from version 1.x to version 5

compiler/cpp/src/thrift/generate/t_java_generator.cc
IDE whitespaces fixes, very nit.
=> Remove unnecessary empty spaces form t_java_generator.cc

compiler/cpp/src/thrift/generate/t_java_generator.cc
Small cleanup for extend logic for both sync and async clients. No behavior change.
=> [Java]: Cleanup extend client logic for sync and async clients

compiler/cpp/src/thrift/generate/t_haxe_generator.cc
=> THRIFT-5717 uuid sets and map keys may throw on some Haxe targets

compiler/cpp/src/thrift/generate/t_py_generator.cc, test/py/explicit_module/runtest.sh, test/py/explicit_module/shared_types.thrift, test/py/explicit_module/test4.thrift
In Python, when using map with enums, the generated code would not output the full path for the enum that was defined in a separate file. This change outputs the full path for the type so that the generated code is correct.
There is a test case the shows the code is properly generated.
Previously the code would output this - 
```python
from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec
from enum import IntEnum
import sys
from .ttypes import *
typeConversion = {
TestEnum.TestEnum0:     SharedEnum.SharedEnum0,
TestEnum.TestEnum1:     SharedEnum.SharedEnum1,
}
```
And now it outputs this - 
```python
from thrift.Thrift import TType, TMessageType, …
```
=> Fix typename for enum value in map for python gen code

.github/workflows/build.yml, LANGUAGES.md, compiler/cpp/src/thrift/generate/t_go_generator.cc, go.mod, lib/go/README.md, lib/go/test/fuzz/go.mod, lib/go/test/go.mod, lib/go/test/tests/server_connectivity_check_test.go, lib/go/thrift/simple_server.go, lib/java/src/main/java/org/apache/thrift/protocol/TType.java, lib/kotlin/build.gradle.kts, lib/kotlin/cross-test-client/build.gradle.kts, lib/kotlin/cross-test-client/src/main/kotlin/org/apache/thrift/test/TestClient.kt, lib/kotlin/cross-test-server/build.gradle.kts, lib/kotlin/cross-test-server/src/main/kotlin/org/apache/thrift/test/TestServer.kt, lib/kotlin/settings.gradle.kts, test/go/go.mod
@Jens-G I'm cherry picking some changes we merged into master branch into the 0.19.0 release branch, mainly THRIFT-5633 and THRIFT-5731 but also a cross test failure fix.
there are also some other dependency changes we merged into master branch not in 0.19.0 release branch yet, I'm not sure whether they are important enough to be included in the 0.19.0 release.
=> Cherry picks into 0.19.0 release branch

lib/go/thrift/socket.go
Client: ["go"]
fix `NewTSocketConf` function comment error in golang client
=> fix: fix golang NewTSocketConf comment error

lib/cpp/test/concurrency/Tests.cpp
This commit makes very minor code cleanup improvements to file `lib/cpp/test/concurrency/Tests.cpp`, and adds a missing include.
=> Very minor code cleanup (whitespace changes only)

lib/netstd/Thrift/Transport/Client/TTlsSocketTransport.cs, lib/netstd/Thrift/Transport/Server/TTlsServerSocketTransport.cs, test/netstd/Client/TestClient.cs, test/netstd/Server/TestServer.cs
=> THRIFT-5743 add TLS1.3 to default protocols where available

lib/netstd/Benchmarks/Thrift.Benchmarks/Thrift.Benchmarks.csproj, lib/netstd/Tests/Thrift.IntegrationTests/Thrift.IntegrationTests.csproj, lib/netstd/Tests/Thrift.PublicInterfaces.Compile.Tests/Thrift.PublicInterfaces.Compile.Tests.csproj, lib/netstd/Tests/Thrift.Tests/Thrift.Tests.csproj, lib/netstd/Thrift/Thrift.csproj, test/netstd/Client/Client.csproj, test/netstd/Server/Server.csproj, tutorial/netstd/Interfaces/Interfaces.csproj
Client: netstd
**This updates certain packages that became available now for 8.0.0**
=> THRIFT-5746 Upgrade to net8 (continued)

compiler/cpp/src/thrift/generate/t_delphi_generator.cc, lib/delphi/src/Thrift.Protocol.pas
=> THRIFT-5749 Option to enable RTTI info

lib/haxe/src/org/apache/thrift/helper/IntSet.hx, lib/haxe/src/org/apache/thrift/helper/StringSet.hx
=> FIX: Unused import Map

compiler/cpp/src/thrift/generate/t_delphi_generator.cc, lib/delphi/src/Thrift.Protocol.pas, lib/delphi/test/serializer/TestSerializer.dproj, lib/delphi/test/server.dproj, lib/delphi/test/skip/skiptest_version2.dproj
Client: Delphi
Followup to issues with the first patch
=> THRIFT-5749 Option to enable RTTI info (2nd attempt)

.github/workflows/build.yml, LANGUAGES.md, compiler/cpp/src/thrift/generate/t_go_generator.cc, go.mod, lib/go/test/fuzz/go.mod, lib/go/test/go.mod, lib/go/test/tests/slog_tstruct_wrapper_test.go, lib/go/thrift/debug_protocol.go, lib/go/thrift/logger.go, lib/go/thrift/simple_server.go, lib/go/thrift/slog.go, lib/go/thrift/slog_test.go, test/go/go.mod, test/go/go.sum
Cherry picks https://github.com/apache/thrift/pull/2882 and https://github.com/apache/thrift/pull/2884 to 0.20.0 release branch.
=> Cherry picks to 0.20.0 branch

.github/workflows/build.yml, lib/php/lib/ClassLoader/ThriftClassLoader.php, lib/php/lib/Factory/TBinaryProtocolFactory.php, lib/php/lib/Factory/TCompactProtocolFactory.php, lib/php/lib/Factory/TJSONProtocolFactory.php, lib/php/lib/Factory/TProtocolFactory.php, lib/php/lib/Factory/TStringFuncFactory.php, lib/php/lib/StringFunc/Core.php, lib/php/lib/StringFunc/Mbstring.php, lib/php/test/Makefile.am, lib/php/test/Unit/Lib/ClassLoader/Fixtures/A/TestClass.php, lib/php/test/Unit/Lib/ClassLoader/Fixtures/B/TestClass.php, lib/php/test/Unit/Lib/ClassLoader/Fixtures/C/TestClass.php, lib/php/test/Unit/Lib/ClassLoader/Fixtures/D/TestClass.php, lib/php/test/Unit/Lib/ClassLoader/Fixtures/E/TestClass.php, lib/php/test/Unit/Lib/ClassLoader/ThriftClassLoaderTest.php, lib/php/test/Unit/Lib/Factory/TBinaryProtocolFactoryTest.php, lib/php/test/Unit/Lib/Factory/TCompactProtocolFactoryTest.php, lib/php/test/Unit/Lib/Factory/TFramedTransportFactoryTest.php, lib/php/test/Unit/Lib/Factory/TJSONProtocolFactoryTest.php, lib/php/test/Unit/Lib/Factory/TStringFuncFactoryTest.php, lib/php/test/Unit/Lib/Factory/TTransportFactoryTest.php, lib/php/test/Unit/Lib/StringFunc/CoreTest.php, lib/php/test/Unit/Lib/StringFunc/MbStringTest.php
After running PHP unit tests for each pull request [THRIFT-5756](https://issues.apache.org/jira/browse/THRIFT-5756)
Next step is writing test for php lib.
It will be several pull request for this task.
=> THRIFT-5757 Unit tests for php lib

compiler/cpp/src/thrift/generate/t_delphi_generator.cc, lib/delphi/src/Thrift.Protocol.pas
=> THRIFT-5750 Remove "ansistr_binary_" option

lib/netstd/Benchmarks/Thrift.Benchmarks/Thrift.Benchmarks.csproj, lib/netstd/Tests/Thrift.IntegrationTests/Thrift.IntegrationTests.csproj, lib/netstd/Tests/Thrift.PublicInterfaces.Compile.Tests/Thrift.PublicInterfaces.Compile.Tests.csproj, lib/netstd/Tests/Thrift.Tests/Thrift.Tests.csproj, lib/netstd/Thrift/Thrift.csproj, test/netstd/Client/Client.csproj, test/netstd/Server/Server.csproj, tutorial/netstd/Interfaces/Interfaces.csproj
=> THRIFT-5783 drop net7 support

doc/specs/thrift-compact-protocol.md
This updates the compact protocol documentation to simplify the explanation of Zigzag and ULEB128 encoding, along with links to wikipedia. In addition it uses varing instead of var int since the former is more common.
=> Update compact-protocol docs [skip ci]

lib/go/thrift/header_transport.go
When enabled zlib in THeaderTransport we observed very high cpu overhead, use a pool for zlib writers to improve efficiency.
=> go: Improve efficiency with zlib in THeaderTransport

compiler/cpp/src/thrift/generate/t_delphi_generator.cc, lib/delphi/test/codegen/run-Pascal-Codegen-Tests.ps1
=> THRIFT-5825 UUID constants lead to uncompileable Delphi code

compiler/cpp/src/thrift/generate/t_delphi_generator.cc, lib/delphi/test/codegen/run-Pascal-Codegen-Tests.ps1
=> THRIFT-5826 binary constants create uncompilable Delphi code

.github/workflows/cmake.yml
=> GitHub cmake workflow to build libraries as well [skip ci]

compiler/cpp/src/thrift/parse/t_function.h, compiler/cpp/src/thrift/parse/t_map.h, compiler/cpp/src/thrift/parse/t_set.h, compiler/cpp/src/thrift/parse/t_struct.h, compiler/cpp/src/thrift/parse/t_type.h, test/ExceptionStruct.thrift
=> THRIFT-5835 Allow exceptions to be used as regular struct datatype

compiler/cpp/src/thrift/generate/t_delphi_generator.cc
=> THRIFT-5837 FIX: error: unused parameter etc

.github/workflows/build.yml
This is fully unsupported [1], and prevents further tests from running.
[1]: https://github.com/actions/runner-images/issues/11101
=> Remove ubuntu-20.04 from github actions

lib/java/src/crossTest/java/org/apache/thrift/test/TestTServletServer.java
=> TestTServletServer doesn't accept the request

compiler/cpp/src/thrift/generate/t_c_glib_generator.cc
This copies the code structure in other parts of the file, to be more consistent.
Change is trivial, so I didn't file a ticket.
=> [nit] Use more consistent free method in c_glib generated code for binary types

.github/workflows/build.yml
=> swift CI broken & no maintainer around to fix (temporary workaround re THRIFT-5864 )

lib/py/src/transport/THttpClient.py
This fixes a regression in 0.22.0 (#3108)
=> THRIFT-5873: py: fix client auth support for THttpClient

lib/netstd/Thrift/Protocol/TJSONProtocol.cs, lib/netstd/Thrift/Transport/Client/THttpTransport.cs, lib/netstd/Thrift/Transport/TEndpointTransport.cs, lib/netstd/Thrift/Transport/TTransportException.cs
=> THRIFT-5874 Introduce new type MESSAGE_SIZE_LIMIT in TTransportException

lib/cpp/src/thrift/protocol/TJSONProtocol.cpp, lib/cpp/test/JSONProtoTest.cpp
This is a bit easier to read -- and I added some tests that ensure it doesn't regress behavior compared to previous implementation.
=> [nit] Adjust base64 padding parsing in TJSONProtocol

lib/netstd/Benchmarks/Thrift.Benchmarks/Thrift.Benchmarks.csproj, lib/netstd/Tests/Thrift.Compile.Tests/Thrift.Compile.net8/Thrift.Compile.net8.csproj, lib/netstd/Tests/Thrift.Compile.Tests/Thrift.Compile.net9/Thrift.Compile.net9.csproj, lib/netstd/Tests/Thrift.IntegrationTests/Thrift.IntegrationTests.csproj, lib/netstd/Tests/Thrift.Tests/Thrift.Tests.csproj, lib/netstd/Thrift/Thrift.csproj, test/netstd/Client/Client.csproj, test/netstd/Server/Server.csproj, tutorial/netstd/Client/Client.csproj, tutorial/netstd/Interfaces/Interfaces.csproj
=> nuget package update

FUZZING.md, test/FuzzTest.thrift, test/v0.16/FuzzTestNoUuid.thrift
This PR adds a basic readme describing the upcoming fuzzing support (it's forward looking, I have local commits that add support to all the languages that I'll re-test and submit once this merges).
It also adds 2 files with test structures - the main difference just being one is for languages with UUID support and one without.
I'm gonna [skip ci] here as this doesn't need CI.
=> THRIFT-5855: Add FUZZING.md and test structures

FUZZING.md, configure.ac, lib/c_glib/test/Makefile.am, lib/c_glib/test/fuzz/Makefile.am, lib/c_glib/test/fuzz/README.md, lib/c_glib/test/fuzz/fuzz_parse_binary.c, lib/c_glib/test/fuzz/fuzz_parse_compact.c
Add fuzzers for c_glib support, to improve the reliability/robustness of the implementation
=> THRIFT-5855: Add c_glib fuzzers

FUZZING.md, lib/go/test/fuzz/Makefile.am, lib/go/test/fuzz/README.md, lib/go/test/fuzz/fuzz.go, lib/go/test/fuzz/fuzz_test.go
Add fuzzers for go support, to improve the reliability/robustness of the implementation
=> THRIFT-5855: Add go fuzzers

FUZZING.md, lib/swift/FuzzTesting/Package.swift, lib/swift/FuzzTesting/README.md, lib/swift/FuzzTesting/Sources/FuzzCommon/FuzzUtils.swift, lib/swift/FuzzTesting/Sources/FuzzParseBinary/main.swift, lib/swift/FuzzTesting/Sources/FuzzParseCompact/main.swift, lib/swift/FuzzTesting/Sources/FuzzParseJSON/main.swift, lib/swift/FuzzTesting/Sources/FuzzRoundtripBinary/main.swift, lib/swift/FuzzTesting/Sources/FuzzRoundtripCompact/main.swift, lib/swift/FuzzTesting/Sources/FuzzRoundtripJSON/main.swift, lib/swift/Makefile.am
Add fuzzers for Swift support, to improve the reliability/robustness of the implementation
=> THRIFT-5855: Add swift fuzzers

lib/cpp/src/thrift/transport/TSSLSocket.cpp
This is a rebased copy of #3055 (an older PR which appears to be abandoned) with a couple of additional comments.
=> Add support for boringssl
